### ISSUE TITLE
Issue with recovering TCRs from 10X bam file.

### ISSUE THREAD

**Issue by svalkiers** [liulab-dfci/TRUST4#103]
Hi,

I am trying to extract V(D)J information from a scRNA-seq experiment performed using 10X Genomics technology (without dedicated V(D)J amplification). I am running TRUST4 with the following parameters:

`./run-trust4 -t 8 -b /path_to_10x_bam_file/possorted_genome_bam.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa`

Unfortunately, I keep running into the following error:

`[Thu Dec  2 15:25:12 2021] Start to extract candidate reads from bam file.
Unknown genome name: chr22
system /path_to_trust4_folder/TRUST4/bam-extractor -b /path_to_10x_bam_file/possorted_genome_bam.bam -t 8 -f hg38_bcrtcr.fa -o TRUST_possorted_genome_bam_toassemble  failed: 256 at ./run-trust4 line 48.`

I compiled TRUST4 from source (git pull + make).
Any idea how I can solve this issue?

Best regards,
Sebastiaan

**Comment by mourisl** [comment]
Resolved in another repository.
