### ISSUE TITLE
barcode error: "could not find file CB"

### ISSUE THREAD

**Issue by Tobey-Huang** [liulab-dfci/TRUST4#109]
Hi,

I'm trying to run TRUST4 on a 10x bam file. And I use “--barcode CB" to designate barcode as the tutorial goes.  But there is an error: "could not find file CB", as the following shows:
![image](https://user-images.githubusercontent.com/51221144/148027858-520a36d8-cd1b-4682-9375-846b4766c6fb.png)
The command I'm using:

_run-trust4 -o 1kPBMC \
--od  ./1kPBMC_bam/ \
-t 20   \
-b   ./pbmc_1k_v3_possorted_genome_bam.bam \
-f ./hg38_bcrtcr.fa  \
--ref ./human_IMGT+C.fa  \
--barcode CB_

Could you please help me with this? Thank you in advance ^-^

**Comment by mourisl** [comment]
Thanks for finding this error. I have updated the wrapper and it should be fixed now. Could you give the new version a try? Thanks.

**Comment by Tobey-Huang** [comment]
It works successfully now, thanks for your help and work!
