### ISSUE TITLE
perl: warning: Setting locale failed

### ISSUE THREAD

**Issue by zhudakai** [liulab-dfci/TRUST4#11]
Hi there, I've run this:

singularity exec trust4-singularity.sif /TRUST4/run-trust4 -b M1500497.bam

then met with the following errors:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
[Mon Apr  6 23:59:06 2020] TRUST4 begins.
Need to use -f to specify the sequence of annotated V/D/J/C genes' sequence.

Please could you help? Thanks!

Dakai

**Comment by mourisl** [comment]
The warning is fine. There are two required option -f and --ref, e.g: 
singularity exec trust4-singularity.sif /TRUST4/run-trust4 -b M1500497.bam -f  hg38_bcrtcr.fa --ref human_IMGT+C.fa .
You can add other options like "-t" for multithreading.
