### ISSUE TITLE
Is it possible for support for _toassemble*.fq.gz

### ISSUE THREAD

**Issue by ma-tongji** [liulab-dfci/TRUST4#110]
Hi,

I have some toassemble*.fq.gz files from first step but were gzipped, now the program cannot recognize gz files

my command:
```
run-trust4         -u ./trust/SRR8613812_toassemble.fq.gz         --stage 1         -f /home/ubuntu/TRUST4/hg38_bcrtcr.fa         --ref /home/ubuntu/TRUST4/human_IMGT+C.fa         -o ./trust/SRR8613812/SRR8613812
```

log file
```
[Tue Jan 11 07:56:44 2022] TRUST4 begins.
Could not find files like ./trust/SRR8613812/SRR8613812_toassemble*.fq
```

**Comment by mourisl** [comment]
The --stage 1 assume the parameter set is the same, and still looks for the intermediate ungzipped read file.

I think you can run TRUST4 with the option --noExtraction, e.g:
run-trust4         -u ./trust/SRR8613812_toassemble.fq.gz ...  --noExtraction

**Comment by ma-tongji** [comment]
Thanks, it works well
