### ISSUE TITLE
Question about `-f` and `--ref` parameters

### ISSUE THREAD

**Issue by alienzj** [liulab-dfci/TRUST4#114]
Dear **TURST4** developer,

**Question 1**:
In the documentations, you mentioned:
`./run-trust4 -f human_IMGT+C.fa --ref human_IMGT+C.fa -1 example/example_1.fq -2 example/example_2.fq -o TRUST_example`,
does it mean `-f` and `--ref` can accept the same file ? For `-f` parameter, it requires FASTA file which header contain coordinate information for each gene, `human_IMGT+C.fa` didn't contain coordinate information.

**Question 2**:
How to generate `bcr_tcr_gene_name` or `human_vdjc.list`, and `human_bcrtcr.fa` ?
Can I just get it using bellow command line ?
```
perl BuildImgtAnnot.pl Homo_sapien > human_IMGT+C.fa
grep "^>" human_IMGT+C.fa | awk -F\* '{print $1}' | awk -F\> '{print $2}' | sort | uniq > human_IMGT+C.gene.list
```
Then:
```
wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/gencode.v39.primary_assembly.annotation.gtf.gz  
pigz -dk gencode.v39.primary_assembly.annotation.gtf.gz

wget http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/GRCh38.primary_assembly.genome.fa.gz  
pigz -dk GRCh38.primary_assembly.genome.fa.gz

perl BuildDatabaseFa.pl GRCh38.primary_assembly.genome.fa \
gencode.v39.primary_assembly.annotation.gtf \
human_IMGT+C.gene.list > human_bcrtcr.fa
```

I found some gene name of `human_IMGT+C.gene.list` is not consistent with `gencode.v39.primary_assembly.annotation.gtf`.
For example,
![image](https://user-images.githubusercontent.com/8847420/154900918-f23025b1-33d3-42e7-8829-2330ea72b1df.png)

**Comment by mourisl** [comment]
1. When using BAM file as input, the "-f" file should contain coordinate information in the header. If your input is the raw fastq files, then "-f" and "--ref" can be the same, and there is no need to contain coordinate information. 

2. Your way of generating the gene list and human_bcrtcr.fa file looks right to me. There are some of the IMGT genes not presented in gencode, and even vice versa. I usually use command like `grep "\"TRB\|\"TRA\|XXXX"  gencode.gtf > gene.list` and then manually remove the irrelevant genes, like IGHEP1, to get the final gene list. 

If your input data is the raw fastq files, then you can directly use the human_IMGT+C.fa you created for the "-f" and "--ref" options.
Hope this helps.

**Comment by alienzj** [comment]
Thanks for your quick reply.
Yes, my input data is the raw FASTQ files. Now, I just use human_IMGT+C.fa.

Appreciated a lot for your help.
