### ISSUE TITLE
Segmentation fault with annotator 

### ISSUE THREAD

**Issue by Rmulet** [liulab-dfci/TRUST4#116]
Hi,

I have tried TRUST4 on RNA-seq data, but unfortunately the program crashes with a segmentation fault in the annotation step:

![image](https://user-images.githubusercontent.com/13835031/155941632-e72dec02-c307-451c-9022-d783bde84be9.png)

However, the program finishes successfully with the example dataset. I compiled TRUST4 using the latest version available in the GitHub repository, but I also tried with the conda version and the problem remains.

I have noticed this problem has been reported before, but those issues were solved and closed in the past. Therefore, I have created a new thread, I hope this is alright.

Update: I ran TRUST4 with a separate dataset and I got a slightly different error. This time, it reported "double free or corruption" followed by "Aborted (core dumped)".

![image](https://user-images.githubusercontent.com/13835031/155949757-f1150f37-e4b4-465d-97c6-f67f9faef984.png)

**Comment by mourisl** [comment]
Hello, I would suggest using human_IMGT+C.fa for the --ref option. Could you please rerun TRUST4 using this file for --ref? You can add the option "--stage 2" to just start from the annotation step, which it crashed when using hg38_tcrbcr.fa file. If it still crashed, could you please share the 1299_final.out file with me? Thanks.

**Comment by Rmulet** [comment]
Thanks a lot for the quick reply. That solved the problem! Sorry for the inconvenience, I should have read the documentation better. Now I realize that all the examples use human_IMGT+C.fa for `--ref`.
