### ISSUE TITLE
Concatenating FASTQs

### ISSUE THREAD

**Issue by kanefos** [liulab-dfci/TRUST4#117]
Hi authors,

Love the tool, super useful idea. 

I'm working with some public data and (predictably) having some Qs about hoe it was processed. Each sample has lanes 1/2 (L1/2), but additionally the data seems to have gone through two sequencing runs (for a total of 4 "lanes" per individual biological sample).

My question is do you think I would be able to concatenate the FASTQ files together ([a la this thread](https://www.biostars.org/p/317385/)), in terms of the L1/2 and/or across the sequencing runs? I am basically being lazy and just want to run TRUST4 on each biological sample vs each set of FASTQs

Thanks, Kane

**Comment by mourisl** [comment]
TRUST4 supports multiple fastq input files separated by commas or using wild card, so you can run TRUST4 like:

run-trust4 -f xxx --ref XXX -1 read_L*_1.fq -2 read_L*_2.fq -t XXX

**Comment by kanefos** [comment]
aha I see, apologies I thought that was just a dummy placeholder for the benefit of the tutorial. Thanks very much
