### ISSUE TITLE
trust4 for RedHat 6?

### ISSUE THREAD

**Issue by zhudakai** [liulab-dfci/TRUST4#12]
Hi, Although trust4 works beautifully in our SMP that is running RedHat 7, our HPC however is still at RedHat 6 level. All dependency libraries are too old to cope with trust4 -  not even when we used singularity. I wonder if it's possible for you to produce a distribution from an older OS or you are willing to release source code for native compilation in our HPC. Thanks!  Dakai

**Comment by mourisl** [comment]
I may need some time to find this older OS.  We are working on the manuscript for TRUST4, and will release the source upon submitting.

**Comment by whitehilltea** [comment]
> 
> 
> Hi, Although trust4 works beautifully in our SMP that is running RedHat 7, our HPC however is still at RedHat 6 level. All dependency libraries are too old to cope with trust4 - not even when we used singularity. I wonder if it's possible for you to produce a distribution from an older OS or you are willing to release source code for native compilation in our HPC. Thanks! Dakai

Hi, zhudakai,

I am glad to share my experience using Trust4 these days. It might help you to run through the process easily

Trust4's aligner is "MapSplice" or "SpliceMap", or something like that. So if the input of the trust4 is fastq files, the aligning process will exhaust your computer or server's memory easily, because of the memory-inefficient aligner. To circumvent this difficulty, I used Hisat2 to align the fastq files to bam file. Aligners like Hisat2 or STAR are very memory-efficient.

Then I use trust4 to process the bam files produced by Hisat2 on my old laptop (ThinkPad W520), which has 8 cores and 32 GB memory and runs Linux Mint system. The bam files are on the external hard drives connecting to the USB3.0 port of my laptop. I ran Trust4, then the miracle happened. Each sample only needs around 30 minutes to finish! 32 GB memory is enough!

Best Wishes.

**Comment by mourisl** [comment]
@whitehilltea TRUST4 does not use other aligners. The alignment for the fastq input uses a quite simple method and only uses the sequences of TCR, BCR region, so it should be very memory efficient. I'm wondering what is your command line for the fastq input? The -f,--ref file should be the human_IMGT+C.fa from the repo. If you used hg38.fa.gz, the whole genome, then it could exceed your memory limit.

**Comment by whitehilltea** [comment]
Hi, Li, Thanks for the discussion. I will look up my command history and update you later.

**Comment by whitehilltea** [comment]
Hi, Li,

I did not use the hg38.fa.gz. My command is generally like this:
../TRUST4-master/run-trust4 -t 8 -1 SRRxxxxxx_1.fastq.gz -2 SRRxxxxxx_2.fastq.gz -f ../TRUST4-master/hg38_bcrtcr.fa --ref ../TRUST4-master/human_IMGT+C.fa

I am still trying to repeat the so-called "memory issue". I plan on running all the samples without Hisat2, just starting from fastq files. I use Hisat2 to align the reads to use the whole reference genome. The whole genome might absorb some reads that should have been mapped to the TCR/BCR region. Trust4 only tries to align the reads to the BCR and TCR region. Thereby, starting from fastq using Trust4 might have a little better result than starting from Hisat2-aligned bam using Trust4.

Here comes another question. I have paired-end bulk RNA-seq data. However, I have several fastq files for R1 and several fastq files for R2. Can I input them together like what HiSat2 does? Like this:

**-1** input_file_1_R1,input_file_2_R1,input_file_3_R1 **-2** input_file_1_R2,input_file_2_R2,input_file_3_R2

https://ccb.jhu.edu/software/hisat2/manual.shtml

![image](https://user-images.githubusercontent.com/45578740/85881992-602f2780-b793-11ea-9146-4678689fb7bc.png)


If not, perhaps I need to manually concatenate the R1 fastq files and R2 fastq files, respectively.

Thanks for your suggestions.

**Comment by mourisl** [comment]
@whitehilltea TRUST4 does not support the comma-separated file list. If you bash environment supports, you can try to run it as:
-1 <(zcat input_file_1_R1.gz input_file_2_R1.gz input_file_3_R1.gz) -2 <(zcat input_file_1_R2, ...)

**Comment by whitehilltea** [comment]
Hi, Li,



After testing, I found that there was no memory issue. Luckily, I figured out the source of so-called "memory issue".



Recently, I tested how to run trust4 using my laptop and our lab server. These tests use the trust4 downloaded directly from github, namely, Clone and then download Zip. Thereby, on my laptop and our lab server, the trust version is the latest version that support raw fastq files as input. I used [memory-profiler](https://pypi.org/project/memory-profiler/) to monitor the memory usage of the trust4 on one of my largest samples. The sample has two fastq files, R1 and R2. Each fastq file contains 96049473 reads with the file size of 5.7G.  My monitoring command is like this:

```shell
mprof run --include-children bash trust4_run.sh
```

In the shell script, the command to run trust4 is like this:

```shell
../TRUST4-master/run-trust4 -t 8 -1 /xxx/xxx/xxx/xxx/xxx/SRRxxxxxx_1.fastq.gz -2 /xxx/xxx/xxx/xxx/xxx/SRRxxxxxx_2.fastq.gz -f ../TRUST4-master/hg38_bcrtcr.fa --ref ../TRUST4-master/human_IMGT+C.fa
```

I got a benchmark picture as follows. The picture shows that the memory usage is less than 17 GB throughout the whole process.

![8_cores](https://user-images.githubusercontent.com/45578740/86080435-bfb55d80-ba47-11ea-8b87-cf797142f2d2.png)


However, when I ran a lot of samples,  I ran the trust4 on Terra, a Google Cloud Platform, where a docker image of trust4 is used. There are many docker images on [dockerhub for trust4](https://hub.docker.com/search?q=trust4&type=image) . I did not noticed that your latest release was 3 month ago, which started to support raw fastq sequence as input.  So I chose a working version [preinink/trust4](https://hub.docker.com/r/preinink/trust4), which was updated 5 month ago. It gave me the impression that this older version can handle fastq files as input, but it needs too much memory. I thought it was extracting too many reads until the memory was exhausted. I set the memory from 16 GB to 32 GB, 64GB, and 108 GB, but some samples still can not go through trust4. So I thought Trust4 was not memory efficient. So I used Hisat2 to align the fastq files first and then used the older version of trust4 to identify TCR and BCRs.



Given you suggestions, I inspected my running history and did some comparison tests. I found out the version discrepancy. Now I use the docker image [jemimalwh/trust4](https://hub.docker.com/r/jemimalwh/trust4) , which was updated 8 days ago. Running this latest version of trust4, I get through the samples on the Terra platform easily with the memory setting of 32 GB. There is no memory issue with this new version.



Thanks again for your explanation about the so-called memory issue. Without your clues, I can not come back to the correct path.



Best Wishes

**Comment by mourisl** [comment]
Sorry for the late reply. Yes, the version issue makes sense, in the early release (<0.2.0), the -1, -2/-u option (which were hidden I think) supposes that the input fastq reads are all from BCR/TCR region. So if you directly give the raw data in those versions, it will store lots of irrelevant information and consumes too much memory.

**Comment by whitehilltea** [comment]
Got it. Thanks.

**Comment by mourisl** [comment]
@zhudakai We have released the source code of TRUST4, can you compile it on your RedHat 6 system? Thanks.

**Comment by zhudakai** [comment]
Great! Will try
