### ISSUE TITLE
No report output

### ISSUE THREAD

**Issue by dsrai** [liulab-dfci/TRUST4#123]
I did this:

 trust4 -f human_IMGT+C.fa -u r1.fastq.gz -o TRUST

ANd my outputs are:
TRUST_assembled_reads
TRUST_final
TRUST_raw

with no 'report' file

**Comment by dsrai** [comment]
Fixed: Did run-trust4 instead of trust4

**Comment by QianRongAn** [comment]
I have the same output files, and my code is 
`trust4.exe -f hg38_bcrtcr.fa -1 DHL2_R1_001.fastq.gz -2 DHL2_R2_001.fastq.gz -t 16 -o DHL2`
when I use code `run-trust4 -f hg38_bcrtcr.fa -1 DHL2_R1_001.fastq.gz -2 DHL2_R2_001.fastq.gz -t 16 -o DHL2` it will tell :
![](https://user-images.githubusercontent.com/95024649/225219432-32034e2b-a7ce-4a71-8299-3e6863c14c82.png)
Any help would be appreciated！

**Comment by QianRongAn** [comment]
And my trust4 seem don't need parameter “--ref” when I want to use it:
![](https://user-images.githubusercontent.com/95024649/225220321-78a6a73a-a5da-413a-bbc8-049338b4e359.png)
