### ISSUE TITLE
open: No such file or directory

### ISSUE THREAD

**Issue by lothm2014** [liulab-dfci/TRUST4#13]
I am able to successfully run the example, but I am unable to run on my own .bam file. I have code below to show my run on the example and my attempt using my own .bam. 

$  singularity exec trust4-singularity.sif /TRUST4/run-trust4 -b example/example.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa
[Tue Apr 28 17:51:19 2020] TRUST4 begins.
[Tue Apr 28 17:51:19 2020] SYSTEM CALL: /TRUST4/bam-extractor -b example/example.bam -t 1 -f hg38_bcrtcr.fa -o TRUST_example_toassemble 
[Tue Apr 28 17:51:19 2020] Start to extract candidate reads from bam file.
[Tue Apr 28 17:51:19 2020] Finish obtaining the candidate read ids.
[Tue Apr 28 17:51:19 2020] Finish extracting reads.
[Tue Apr 28 17:51:19 2020] SYSTEM CALL: /TRUST4/trust4  -f hg38_bcrtcr.fa -o TRUST_example -1 TRUST_example_toassemble_1.fq -2 TRUST_example_toassemble_2.fq
[Tue Apr 28 17:51:19 2020] Found 394 reads.
[Tue Apr 28 17:51:19 2020] Finish sorting the reads.
[Tue Apr 28 17:51:19 2020] Finish rough annotations.
[Tue Apr 28 17:51:19 2020] Assembled 389 reads.
[Tue Apr 28 17:51:19 2020] Try to rescue 0 reads for assembly.
[Tue Apr 28 17:51:19 2020] Rescued 0 reads.
[Tue Apr 28 17:51:19 2020] Extend assemblies by mate pair information.
[Tue Apr 28 17:51:19 2020] Remove redundant assemblies.
[Tue Apr 28 17:51:19 2020] Finish assembly.
[Tue Apr 28 17:51:19 2020] SYSTEM CALL: /TRUST4/annotator -f human_IMGT+C.fa -a TRUST_example_final.out -t 1 -o TRUST_example  -r TRUST_example_assembled_reads.fa > TRUST_example_annot.fa
[Tue Apr 28 17:51:20 2020] Start to annotate assemblies.
[Tue Apr 28 17:51:20 2020] Start to realign reads for CDR3 analysis.
[Tue Apr 28 17:51:20 2020] Compute CDR3 abundance.
[Tue Apr 28 17:51:20 2020] Finish annotation.
[Tue Apr 28 17:51:20 2020] SYSTEM CALL: perl /TRUST4/trust-simplerep.pl TRUST_example_cdr3.out  > TRUST_example_report.tsv
[Tue Apr 28 17:51:20 2020] TRUST4 finishes.
[    2.377463] reboot: Power down
melanie (master *) TRUST4
$  singularity exec trust4-singularity.sif /TRUST4/run-trust4 -b /Volumes/MelHD/Patient1207/TRUST4/possorted_genome_bam.bam  -f hg38_bcrtcr.fa --ref human_IMGT+C.fa
[Tue Apr 28 17:51:28 2020] TRUST4 begins.
[Tue Apr 28 17:51:28 2020] SYSTEM CALL: /TRUST4/bam-extractor -b /Volumes/MelHD/Patient1207/TRUST4/possorted_genome_bam.bam -t 1 -f hg38_bcrtcr.fa -o TRUST_possorted_genome_bam_toassemble 
open: No such file or directory
system /TRUST4/bam-extractor -b /Volumes/MelHD/Patient1207/TRUST4/possorted_genome_bam.bam -t 1 -f hg38_bcrtcr.fa -o TRUST_possorted_genome_bam_toassemble  failed: 11 at /TRUST4/run-trust4 line 37.
[    1.343459] reboot: Power down

**Comment by mourisl** [comment]
I think Singularity parses /Volumes/MelHD/Patient1207/TRUST4/possorted_genome_bam.bam as it is from the image. You may need to mount your host path to the Singularity virtual environment. Can you try to run it as: 
singularity exec --bind /Volumes/MelHD/Patient1207/TRUST4/:/mnt trust4-singularity.sif /TRUST4/run-trust4 -b /mnt/possorted_genome_bam.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa

**Comment by lothm2014** [comment]
After running the command you provided, I got the following error: 

melanie (master *) TRUST4
$ singularity exec --bind /Volumes/MelHD/Patient1207/TRUST4/:/mnt trust4-singularity.sif /TRUST4/run-trust4 -b /mnt/possorted_genome_bam.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa
[Tue Apr 28 19:16:15 2020] TRUST4 begins.
[Tue Apr 28 19:16:15 2020] SYSTEM CALL: /TRUST4/bam-extractor -b /mnt/possorted_genome_bam.bam -t 1 -f hg38_bcrtcr.fa -o TRUST_possorted_genome_bam_toassemble 
[Tue Apr 28 19:16:15 2020] Start to extract candidate reads from bam file.
[Tue Apr 28 19:38:36 2020] Finish obtaining the candidate read ids.
[Tue Apr 28 20:00:59 2020] Finish extracting reads.
[Tue Apr 28 20:00:59 2020] SYSTEM CALL: /TRUST4/trust4  -f hg38_bcrtcr.fa -o TRUST_possorted_genome_bam -1 TRUST_possorted_genome_bam_toassemble_1.fq -2 TRUST_possorted_genome_bam_toassemble_2.fq
[Tue Apr 28 20:01:01 2020] Read in and count kmers for 100000 reads.
[Tue Apr 28 20:01:02 2020] Read in and count kmers for 200000 reads.
[Tue Apr 28 20:01:03 2020] Read in and count kmers for 300000 reads.
[Tue Apr 28 20:01:05 2020] Read in and count kmers for 400000 reads.
[Tue Apr 28 20:01:06 2020] Read in and count kmers for 500000 reads.
[Tue Apr 28 20:01:08 2020] Read in and count kmers for 600000 reads.
[Tue Apr 28 20:01:09 2020] Read in and count kmers for 700000 reads.
[Tue Apr 28 20:01:10 2020] Read in and count kmers for 800000 reads.
[Tue Apr 28 20:01:17 2020] Found 795190 reads.
[Tue Apr 28 20:01:18 2020] Finish sorting the reads.
[Tue Apr 28 20:01:52 2020] Finish rough annotations.
[Tue Apr 28 20:01:53 2020] Processed 100000 reads (87331 are used for assembly).
[Tue Apr 28 20:01:53 2020] Processed 200000 reads (173467 are used for assembly).
[Tue Apr 28 20:01:53 2020] Processed 300000 reads (265352 are used for assembly).
[Tue Apr 28 20:01:54 2020] Processed 400000 reads (353816 are used for assembly).
[Tue Apr 28 20:01:55 2020] Processed 500000 reads (443995 are used for assembly).
[Tue Apr 28 20:01:56 2020] Processed 600000 reads (533646 are used for assembly).
[Tue Apr 28 20:02:00 2020] Processed 700000 reads (617757 are used for assembly).
[Tue Apr 28 20:02:17 2020] Assembled 693379 reads.
[Tue Apr 28 20:02:17 2020] Try to rescue 3862 reads for assembly.
[Tue Apr 28 20:02:20 2020] Rescued 2085 reads.
system /TRUST4/trust4  -f hg38_bcrtcr.fa -o TRUST_possorted_genome_bam -1 TRUST_possorted_genome_bam_toassemble_1.fq -2 TRUST_possorted_genome_bam_toassemble_2.fq failed: 9 at /TRUST4/run-trust4 line 37.
[ 2766.437823] reboot: Power down

**Comment by mourisl** [comment]
Can you find the newly generated TRUST_possorted_genom_bam_raw.out and TRUST_possorted_genom_bam_assembled_reads.fa files in your folder?

**Comment by lothm2014** [comment]
There are the following files:
- TRUST_possorted_genome_bam_raw.out
- TRUST_possorted_genome_bam_toassemble_2.fq
-TRUST_possorted_genome_bam_toassemble_1.fq

**Comment by mourisl** [comment]
Could you please show me the last few (say 8) lines of each file? Thanks.

**Comment by lothm2014** [comment]
![image](https://user-images.githubusercontent.com/59892258/80537751-8b9fbc80-8972-11ea-9bf7-f195c44b8054.png)

**Comment by mourisl** [comment]
Feels like the length of the quality score string is different from the read length for the second mate (the character seems of equal width). In that case, can you check whether the length is the same in bam file? Thanks.

**Comment by lothm2014** [comment]
Thank you for your help, I reran the code you provided above with the addition of "--barcode CB" and "-o p1207" and was able to complete a run with no indication of errors. 

melanie (master *) TRUST4
$ singularity exec --bind /Volumes/MelHD/Patient1207/TRUST4/:/mnt trust4-singularity.sif /TRUST4/run-trust4 -b /mnt/possorted_genome_bam.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa --barcode CB -o p1207
[Wed Apr 29 12:31:57 2020] TRUST4 begins.
[Wed Apr 29 12:31:57 2020] SYSTEM CALL: /TRUST4/bam-extractor -b /mnt/possorted_genome_bam.bam -t 1 -f hg38_bcrtcr.fa -o p1207_toassemble  --barcode CB
[Wed Apr 29 12:31:57 2020] Start to extract candidate reads from bam file.
[Wed Apr 29 12:55:21 2020] Finish obtaining the candidate read ids.
[Wed Apr 29 13:18:43 2020] Finish extracting reads.
[Wed Apr 29 13:18:43 2020] SYSTEM CALL: /TRUST4/trust4  -f hg38_bcrtcr.fa -o p1207 -1 p1207_toassemble_1.fq -2 p1207_toassemble_2.fq --barcode p1207_toassemble_bc.fa
[Wed Apr 29 13:18:45 2020] Read in and count kmers for 100000 reads.
[Wed Apr 29 13:18:46 2020] Read in and count kmers for 200000 reads.
[Wed Apr 29 13:18:48 2020] Read in and count kmers for 300000 reads.
[Wed Apr 29 13:18:49 2020] Read in and count kmers for 400000 reads.
[Wed Apr 29 13:18:51 2020] Read in and count kmers for 500000 reads.
[Wed Apr 29 13:18:56 2020] Found 523457 reads.
[Wed Apr 29 13:18:56 2020] Finish sorting the reads.
[Wed Apr 29 13:19:21 2020] Finish rough annotations.
[Wed Apr 29 13:19:21 2020] Processed 100000 reads (97230 are used for assembly).
[Wed Apr 29 13:19:21 2020] Processed 200000 reads (188494 are used for assembly).
[Wed Apr 29 13:19:22 2020] Processed 300000 reads (278197 are used for assembly).
[Wed Apr 29 13:19:22 2020] Processed 400000 reads (367490 are used for assembly).
[Wed Apr 29 13:19:25 2020] Processed 500000 reads (449997 are used for assembly).
[Wed Apr 29 13:19:27 2020] Assembled 468408 reads.
[Wed Apr 29 13:19:27 2020] Try to rescue 180 reads for assembly.
[Wed Apr 29 13:19:27 2020] Rescued 27 reads.
[Wed Apr 29 13:19:30 2020] Processed 100000 reads for extension.
[Wed Apr 29 13:19:30 2020] Processed 200000 reads for extension.
[Wed Apr 29 13:19:31 2020] Processed 300000 reads for extension.
[Wed Apr 29 13:19:32 2020] Processed 400000 reads for extension.
[Wed Apr 29 13:19:35 2020] Extend assemblies by mate pair information.
[Wed Apr 29 13:19:38 2020] Remove redundant assemblies.
[Wed Apr 29 13:19:40 2020] Finish assembly.
[Wed Apr 29 13:19:41 2020] SYSTEM CALL: /TRUST4/annotator -f human_IMGT+C.fa -a p1207_final.out -t 1 -o p1207  > p1207_annot.fa
[Wed Apr 29 13:19:41 2020] Start to annotate assemblies.
[Wed Apr 29 13:19:48 2020] Finish annotation.
[Wed Apr 29 13:19:48 2020] SYSTEM CALL: perl /TRUST4/trust-simplerep.pl p1207_cdr3.out  --barcodeCnt --noPartial > p1207_report.tsv
[Wed Apr 29 13:19:48 2020] SYSTEM CALL: perl /TRUST4/trust-barcoderep.pl p1207_cdr3.out -a p1207_annot.fa > p1207_barcode_report.tsv
[Wed Apr 29 13:19:48 2020] TRUST4 finishes.
[ 2872.630850] reboot: Power down
