### ISSUE TITLE
What does the meaning of cid_full_length in trust report?

### ISSUE THREAD

**Issue by Chenjunjie1996** [liulab-dfci/TRUST4#131]
Firstly, whether the definition of cid_full_length is the same as 10X?
(10X:Full-length A contig is full-length if it matches the initial part of a V gene, continues on, and ultimately matches the terminal part of a J gene.)
Besides, as the report shown, some contigs have both V(D)JC genes, but cid_full_length equals zero, is that reasonable?
Finally, After using [GetFullLengthAssembly.pl](https://github.com/liulab-dfci/TRUST4/blob/master/scripts/GetFullLengthAssembly.pl) script i get a full length file from annot.fa. Theoretically, the number of contigs in full length file should equal to contigs whose cid_full_length is "1" in report, but unequal.
Looking forward to your reply.

**Comment by mourisl** [comment]
1. The definition is the same, it means the sequence is from the 5' end of the V gene to the 3' of the J gene.
2. The full-length means the sequence must be full-length. In many cases, we don't need full length to know its V, J gene names. For example, if the sequence covers half of the V gene, we can be pretty sure about its V gene name.
3. GetFullLengthAssembly.pl only extracts full length assemblies from the annotation file. However, the annotated contigs are consensus motifs, which implicitly encodes minor CDR3s. These minor CDR3s are output in the report file, so there should be more full_length in the report than using the script. 
Hope this helps.

**Comment by Chenjunjie1996** [comment]
About Q3
According to my statistics, there are much more contigs in full length file than report.

**Comment by mourisl** [comment]
Could you please show me some examples? The perl script might be a bit out-of-date, but the results should be similar.

**Comment by Chenjunjie1996** [comment]
![image](https://user-images.githubusercontent.com/74704889/168217751-7805a194-129a-45f2-804b-90e7fdb9b7a4.png)
![image](https://user-images.githubusercontent.com/74704889/168217782-282aa192-1f11-47f5-b6a8-47d14c899974.png)
perl script is the latest.

**Comment by mourisl** [comment]
I mean the examples that the full-length assemblies from the perl script but are not found in the report file. The out-of-date is because after adding the cid_full_length feature I did not maintain the perl script. But the criteria are the same though.

**Comment by Chenjunjie1996** [comment]
![image](https://user-images.githubusercontent.com/74704889/168219228-4c5d416c-9279-4d8d-a131-c546235b548e.png)

**Comment by mourisl** [comment]
Oh, you can see that these contigs have the same CDR3 sequence, and differs in other regions. For this case, the report file will coalesce the entries with the same CDR3, V, J, C genes, and only use one contig id as the representative. Therefore, in your case you see more full-length sequences in the annotation contig file.

**Comment by Chenjunjie1996** [comment]
Thank you.
So, these contigs are still called full length but just be coalesced?

**Comment by Chenjunjie1996** [comment]
many thanks.
