### ISSUE TITLE
fastq-extractor fails with barcode whitelist

### ISSUE THREAD

**Issue by thisishcb** [liulab-dfci/TRUST4#132]
Hi TRUST4 team, I encountered this problem when I tried to run TRUST4 on 10x single cell data.
The program works perfectly without specifying barcodeWhitelist. However, when I offer the barcode list, the program fails.
```
[Mon May 16 16:40:23 2022] TRUST4 begins.
[Mon May 16 16:40:23 2022] SYSTEM CALL: /home/me/miniconda3/bin/fastq-extractor -t 16 -f hg38_bcrtcr.fa -o TRUST_G6_S5_L004_R2_001_toassemble  --barcodeWhitelist 737K-august-2016.txt --barcodeStart 0 --barcodeEnd 15 -u $PATH/XXXXX_R2_001.fastq.gz --barcode $PATH/XXXXX_R1_001.fastq.gz
[Mon May 16 16:40:27 2022] Start to extract candidate reads from read files.
system /home/me/miniconda3/bin/fastq-extractor -t 16 -f hg38_bcrtcr.fa -o TRUST_G6_S5_L004_R2_001_toassemble  --barcodeWhitelist 737K-august-2016.txt --barcodeStart 0 --barcodeEnd 15 -u $PATH/XXXXX_R2_001.fastq.gz --barcode $PATH/XXXXX_R1_001.fastq.gz failed: 139 at /home/me/miniconda3/bin/run-trust4 line 48.
```
I ran the fastq-extractor command called by TRUST4, and Segmentation fault occured.
```
[Mon May 16 16:53:02 2022] Start to extract candidate reads from read files.
/var/spool/slurmd/job121813/slurm_script: line 127: 13568 Segmentation fault      (core dumped) /home/me/miniconda3/bin/fastq-extractor -t 16 -f hg38_bcrtcr.fa -o TRUST_XXXXX_R2_001_toassemble --barcodeWhitelist 737K-august-2016.txt --barcodeStart 0 --barcodeEnd 15 -u $PATH/XXXXX_R2_001.fastq.gz --barcode $PATH/XXXXX_S5_L004_R1_001.fastq.gz
```
The problem still exists after I allocate more memory for the task.
Is there any solution to this problem?

Also, I have some data in `fastq.bz2` format. TRUST4 is able to run after converting the data to `gz` compression (but this is very time consuming). TRUST4 also fails with the original `bz2` file input at the fastq-extractor step. `Read file and barcode file have different number of reads.` was reported by the fastq-extractor. this should not be caused by the data itself since the same data worked well after being converted to `gz` compression. 
Is `bz2` compression supported by TRUST4?

**Comment by mourisl** [comment]
Hello, the fastq-extractor's "mysterious" failure with whitelist is fixed in a recent release. Which TRUST4 version are you using?

TRUST4 does not support bz2 format directly.  Is your fastq.bz2 for each file or contains mate-pair fastqs? If you have bz2 files for each mate, you may try to decompress to a stream, you may try command line like: "run-trust4 -1 <(bzcat read1.bz2) -2 <(bzcat read2.bz2) -f ..." .  You might lose 1000 reads since TRUST4 will use them to collect some statistics, and the streamed input can not be rewind back. But unless very unlucky, these 1000 reads should be from other irrelevant genes.  If you are concerned about those, you may try: 
"run-trust4 -1 <(bzcat read1.bz2 | head -4000) -2 <(bzcat read2.bz2 | head -4000) -1 <(bzcat read1.bz2) -2 <(bzcat read2.bz2) -f ..." I think this would work.

**Comment by mourisl** [comment]
I forgot your data is single-cell. For data with barcodes, you also need to duplicate the first 2000,000 barcode sequences, where TRUST4 needs to estimate barcode distribution for error correction.

**Comment by thisishcb** [comment]
> Hello, the fastq-extractor's "mysterious" failure with whitelist is fixed in a recent release. Which TRUST4 version are you using?
> 
> TRUST4 does not support bz2 format directly. Is your fastq.bz2 for each file or contains mate-pair fastqs? If you have bz2 files for each mate, you may try to decompress to a stream, you may try command line like: "run-trust4 -1 <(bzcat read1.bz2) -2 <(bzcat read2.bz2) -f ..." . You might lose 1000 reads since TRUST4 will use them to collect some statistics, and the streamed input can not be rewind back. But unless very unlucky, these 1000 reads should be from other irrelevant genes. If you are concerned about those, you may try: "run-trust4 -1 <(bzcat read1.bz2 | head -4000) -2 <(bzcat read2.bz2 | head -4000) -1 <(bzcat read1.bz2) -2 <(bzcat read2.bz2) -f ..." I think this would work.

Thanks for replying do fast. Currently I'm using v1.0.5 and I met some issues in updating to 1.0.7 on the cluster. I'm contacting the admin to update it. 
For the bz2 input, the steamed input really helps. Thanks a lot!

**Comment by thisishcb** [comment]
> I forgot your data is single-cell. For data with barcodes, you also need to duplicate the first 2000,000 barcode sequences, where TRUST4 needs to estimate barcode distribution for error correction.

Do you mean the first 2000,000 reads in the file for `--barcode` parameter or the first 2000,000 barcode sequences in the file for `--barcodeWhitelist`? The 737K barcode whitelist seems to have less than 2000,000 barcodes.

**Comment by mourisl** [comment]
The first 2M reads in the --barcode file.

**Comment by thisishcb** [comment]
Thanks!
