### ISSUE TITLE
TRUST4 annotator not found error

### ISSUE THREAD

**Issue by olu2016** [liulab-dfci/TRUST4#133]
Hi,

I have an assembly fasta file (con2.fa) and interested in obtaining V,D,J,C  and CDR3 gene assignments of the the sequences.

I ran a trust4 command as follows:

`./run_trust4 -u con2.fa -f IMGT+C.fa -t 20 --stage 2 -o bar`

I got the following errors:

`[Fri Jun 10 12:29:03 2022] TRUST4 begins.
[Fri Jun 10 12:29:03 2022] WARNING: human_IMGT+C.fa is of IMGT format, automatically add --ref option.
[Fri Jun 10 12:29:03 2022] SYSTEM CALL: /programs/TRUST4/annotator -f human_IMGT+C.fa -a bar_final.out -t 20 -o bar  -r bar_assembled_reads.fa > bar_annot.fa
sh: 1: /programs/TRUST4/annotator: not found
system /programs/TRUST4/annotator -f human_IMGT+C.fa -a bar_final.out -t 20 -o bar -r bar_assembled_reads.fa > bar_annot.fa failed: 32512 at ./run-trust4 line 48.`

Any idea what the source of the error is?

Thanks

**Comment by mourisl** [comment]
Have you run "make" to compile TRUST4 first?

**Comment by olu2016** [comment]
That's what the issue was. I missed out the "make" step! Issue now resolved. Thanks
