### ISSUE TITLE
TRUST4 compatible w/ 5'RACE enriched libs

### ISSUE THREAD

**Issue by tdfy** [liulab-dfci/TRUST4#134]
Hello, 

Is TRUST4 compatible w/ immune repertoire libraries generated from 5'RACE enrichment? If so, can you advise on preferable parameters-- including UMI quantification. Thank you!

-Todd

**Comment by tdfy** [comment]
thank you. Per the 5'RACE enrichment structure; I wouldn't two chains w/ different UMIs since the primer(IgM/IgG/TCRb/TCRa..) is chain-constant region specific. 

Is TRUST4 applicable to this library structure since it is not shotgun, nor the 5' bias GEX 10x libraries? 


![Screen Shot 2022-06-14 at 2 35 04 PM](https://user-images.githubusercontent.com/25744474/173663813-91fb0084-6153-4356-865c-a02ad2bf2833.png)

**Comment by mourisl** [comment]
Hi @tdfy , I just add the option "--barcode-level" to the github repo. You can run TRUST4 with option "--barcode-level molecule", and trust_barcode_report.tsv (on the third column) and trust_barcode_airr.tsv file will contains the CDR3 information for each barcode.
