### ISSUE TITLE
Problem of Assembled 0 reads

### ISSUE THREAD

**Issue by FsheriF** [liulab-dfci/TRUST4#137]
I want to reconstruct TCRA from one bulk RNA-seq "SRR17591781". Set MiXCR as control, it can produce 1K TCRA seq. 
Howerver  when I ran TRUST4 using the code `~run-trust4 -t 8 -1 ~SRR17591781_1.fastq.gz -2 ~SRR17591781_2.fastq.gz -f hg38_bcrtcr.fa --ref human_IMGT+C.fa` , it can not assembled any TCR/BCR seq in the process, here is the log
[Tue Jun 21 14:26:21 2022] TRUST4 begins.
[Tue Jun 21 14:26:21 2022] SYSTEM CALL: ~bin/fastq-extractor -t 8 -f hg38_bcrtcr.fa -o TRUST_SRR17591781_1_toassemble  -1 ./SRR17591781_1.fastq.gz -2 ./SRR17591781_2.fastq.gz
[Tue Jun 21 14:26:21 2022] Start to extract candidate reads from read files.
[Tue Jun 21 14:32:53 2022] Finish extracting reads.
[Tue Jun 21 14:32:53 2022] SYSTEM CALL: ~/bin/trust4  -t 8 -f hg38_bcrtcr.fa -o TRUST_SRR17591781_1 -1 TRUST_SRR17591781_1_toassemble_1.fq -2 TRUST_SRR17591781_1_toassemble_2.fq
[Tue Jun 21 14:32:54 2022] Read in and count kmers for 100000 reads.
[Tue Jun 21 14:32:55 2022] Read in and count kmers for 200000 reads.
[Tue Jun 21 14:32:58 2022] Found 262596 reads.
[Tue Jun 21 14:32:59 2022] Finish sorting the reads.
[Tue Jun 21 14:33:01 2022] Finish rough annotations.
[Tue Jun 21 14:33:01 2022] Processed 100000 reads (0 are used for assembly).
[Tue Jun 21 14:33:01 2022] Processed 200000 reads (0 are used for assembly).
[Tue Jun 21 14:33:01 2022] Assembled 0 reads.
[Tue Jun 21 14:33:01 2022] Try to rescue 0 reads for assembly.
[Tue Jun 21 14:33:01 2022] Rescued 0 reads.
[Tue Jun 21 14:33:01 2022] Extend assemblies by mate pair information.
[Tue Jun 21 14:33:01 2022] Remove redundant assemblies.
[Tue Jun 21 14:33:01 2022] Finish assembly.
[Tue Jun 21 14:33:01 2022] SYSTEM CALL: ~/bin/annotator -f human_IMGT+C.fa -a TRUST_SRR17591781_1_final.out -t 8 -o TRUST_SRR17591781_1  -r TRUST_SRR17591781_1_assembled_reads.fa > TRUST_SRR17591781_1_annot.fa
[Tue Jun 21 14:33:01 2022] Start to annotate assemblies.
[Tue Jun 21 14:33:01 2022] Start to realign reads for CDR3 analysis.
[Tue Jun 21 14:33:01 2022] Compute CDR3 abundance.
[Tue Jun 21 14:33:01 2022] Finish annotation.
[Tue Jun 21 14:33:02 2022] SYSTEM CALL: perl ~/bin/trust-simplerep.pl TRUST_SRR17591781_1_cdr3.out  > TRUST_SRR17591781_1_report.tsv
[Tue Jun 21 14:33:02 2022] TRUST4 finishes.

So why could this happened and how can I fix it?

Thanks in advance.

**Comment by FsheriF** [comment]
Hi, thanks for you reply.

1. 
Below is first 20 lines TRUST_SRR17591781_1_toassemble_1.fq
-------
@SRR17591781.10
TCCTCTATGAGATCCTGCTAGGGAAGGCCNCNCTNTATNCTGNGCNGNTCAGCGCCCTTGTGTTGATGGCCATGGT
+
AAFFFJJJAJFJJJJJ7A7FJF<JJFJJJ#J#JF#JJJ#JFF#JJ#J#FJFJJFFJJJFJ<FFJAJJJJJJJJFFJ
@SRR17591781.456
GCCTTGTCCCTCTCTTAGTGTTCTTTAATCAGATAACTGCCTGGAAGCCTTTCATTTTACACGCCCTGAAGCAGTC
+
AAAFFJJJJJJJAA<JJJ-FFJJFFJJJFJFJJJJJJFJJJAJFJFJJJ-FFJJFFFJJFJFJJJJ7JA-FJ7<FF
@SRR17591781.731
GTGTTCTTAAACTCCTGGGCTCAAGGGATCCGCCTGCCTTGGCCTCCTAAAGTGCTGGGATTACAAGTGTGAGCCA
+
AAFAFJJJJJJJJJJJFJJJFJJJJJJJFJJJFJAAJJJJF7JAJFJJJFJJFFJAFJJFJJJJJJJ-FAJ<JJJJ
@SRR17591781.781
TTCCAGAGGCTAGCTCCAAAACCATCCCAGGTCATTCTTCATCCTCACCCAGGATTCTCCTGTACCTGCTCCCAAT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJ
@SRR17591781.817
CACACCTGCACACTCACGGCTGAAATCTCCCTAACCCAGGGGGACCTTAGCATGCCTAAGTGACTAAACCAATAAA
+
AAFFAA<AFFFJJ<JFFF<J7<JFJ-F-FFJAJFJJJJJJJFFJJJFFJJJJJ<JJJ7AJ<<FJJFJAJJFJFJJJ
-------

Below is first 20 lines TRUST_SRR17591781_1_toassemble_2.fq
-------
@SRR17591781.10
CTCTTGACCATGGCCATCAACACAAGGGCGCTGACCAGCACAGCATACAGGGTGGCCTTCCCTAGCAGGATCTCAT
+
AAAFFAJFJJJJJJJJJJJJJJJJJJJJJFJFJFJJJJJJJFJJJAJJJJJJJJJJJJJJJJJJFJFFJJJJ7FJJ
@SRR17591781.456
CTTTTCATTTTTTTAAATTTATTTTGCTTATTACGGAAAAACACACCACATAATTCAACTAGCAAAGAAGACTGCT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ7FFJJJJJJJJJA-AJJFJJJJJJ-FJJJJJFJJF77AF
@SRR17591781.731
GCCTGGTCCCGTAAAAACAAAAACAAAAACCAACACCAGATGTGGTGGCTCATGCCTATAATCCCAGCGCTTGGGA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJAJJJAJJ<JJFFFJFJJJJ-FJJJAJJJJJJJJJ
@SRR17591781.781
GTTTAGCCTATTTCGTACTTGGGGGTTGGGAGCTCAATCTTCAGGGAAACAGAAAAAAGAGAGAAGTATTCATGTA
+
AAFFFJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ-FJJJJJJJJJJJJJ
@SRR17591781.817
TATCAACGCAGAGTACTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<AJAJJAJF-AFFJJJJJJJ<FFJJJJ
-------

I also tried to use fastaq-dump without --split-files to get just pair-end SRR17591781 files. When ran it, it still get 0 assemble. The first 20 lines is like this
-------
@SRR17591781.10
TCCTCTATGAGATCCTGCTAGGGAAGGCCNCNCTNTATNCTGNGCNGNTCAGCGCCCTTGTGTTGATGGCCATGGTCTCTTGACCATGGCCATCAACACAAGGGCGCTGACCAGCACAGCATACAGGGTGGCCTTCCCTAGCAGGATCTCAT
+
AAFFFJJJAJFJJJJJ7A7FJF<JJFJJJ#J#JF#JJJ#JFF#JJ#J#FJFJJFFJJJFJ<FFJAJJJJJJJJFFJAAAFFAJFJJJJJJJJJJJJJJJJJJJJJFJFJFJJJJJJJFJJJAJJJJJJJJJJJJJJJJJJFJFFJJJJ7FJJ
@SRR17591781.456
GCCTTGTCCCTCTCTTAGTGTTCTTTAATCAGATAACTGCCTGGAAGCCTTTCATTTTACACGCCCTGAAGCAGTCCTTTTCATTTTTTTAAATTTATTTTGCTTATTACGGAAAAACACACCACATAATTCAACTAGCAAAGAAGACTGCT
+
AAAFFJJJJJJJAA<JJJ-FFJJFFJJJFJFJJJJJJFJJJAJFJFJJJ-FFJJFFFJJFJFJJJJ7JA-FJ7<FFAAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ7FFJJJJJJJJJA-AJJFJJJJJJ-FJJJJJFJJF77AF
@SRR17591781.771
CTTGAAGTCACAAAGGGGAGGCGTGAAGAAATCCTGCATCTCAGTCCCTCACAAGACAGCTGTCTCAGGCTTTTCAGCCGAAGCCCCTCACCCTGAGATGGGAGCCATCTTCCCAGTCCACCATCCCCATCGTGGGCATTGTTGCTGGCCTG
+
AAFFFJJJJ--AFJJJJJJ7JJJJJJJJJJJFJJJJJJJJAJF<FJJJJJJJJJAJJJJJJJJJ<JJJJJ-FJJJJAAAFFJJJFJ<AFFJJJJJJFJAFFJJJAJJFJFFJJJJJAJFFAJF7JJF<JJJJJ7A7A7F-FJJJJAFAJ<JJ
@SRR17591781.781
TTCCAGAGGCTAGCTCCAAAACCATCCCAGGTCATTCTTCATCCTCACCCAGGATTCTCCTGTACCTGCTCCCAATGTTTAGCCTATTTCGTACTTGGGGGTTGGGAGCTCAATCTTCAGGGAAACAGAAAAAAGAGAGAAGTATTCATGTA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJAAFFFJJJJJJJJJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ-FJJJJJJJJJJJJJ
@SRR17591781.824
CTGTTATCTTCTTGGATGACACGAGATTTATTCTTATATCCTTGGGGTAGAATTCCTTCACCAGACAAGCGACATTCTTGGGGATCCTGACTTCCCTACGCGTACTGGGGGATATTGTTCGTACACCGATAAACTCATCTTTGGAAAAGGAA
+
AAFFFFJJJJJJJJJJJJJJJJJJJJ<JJJJJJJJJJJJJJJJJFJJJ<JJJJJJJAJJJJJJJJJJFFJJJJJFFAAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJFJJJJJJJJJJJFJJ
-------

3. For the TRUST4 version, I used Bioconda to installed, the package name showed is "trust4-1.0.5.1-h2e03b76_0".

**Comment by mourisl** [comment]
All the 5 reads are on the 3' end of the constant gene so they are filtered in the output. I think bioconda has 1.0.7 now which fixes some serious bugs. Could you please give it a try?
Furthermore, is it possible for you to share the TRUST_SRR17591781_1_toassemble_{1,2}.fq files? It seems SRR17591781 need access permission and I could not download it with fastq-dump.

**Comment by FsheriF** [comment]
Thanks for your suggestion, I tired to using the newest trust from git repository and now it works!
[TRUST_SRR17591781.zip](https://github.com/liulab-dfci/TRUST4/files/8954332/TRUST_SRR17591781.zip)

**Comment by mourisl** [comment]
Thank you for sharing the data. It seems the new version does not have any memory access errors in my test either. I guess the bug is already fixed. I'll close the issue for now. If you found more problems, please feel free to let us know.
