### ISSUE TITLE
Fastq vs BAM input produces different output. Which is preferred? 

### ISSUE THREAD

**Issue by BrianLohman** [liulab-dfci/TRUST4#142]
Hello,

I'm interested in working with your software. Very impressed with the speed! 

I started with the example data that is provided in the repo. I ran the two example commands with the fastqs and the BAM but it looks like the results are different. Which one should I use? 

For BAM input:
```
./run-trust4 -b example/example.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa
``` 

and for fastq input:
```
./run-trust4 -f human_IMGT+C.fa --ref human_IMGT+C.fa -1 example/example_1.fq -2 example/example_2.fq -o TRUST_example
```

Which results in the attached files. The counts are the same between the different inputs but the sequences are different. 
[bam_TRUST_example_report.txt](https://github.com/liulab-dfci/TRUST4/files/9065809/bam_TRUST_example_report.txt)
[fastq_TRUST_example_report.txt](https://github.com/liulab-dfci/TRUST4/files/9065812/fastq_TRUST_example_report.txt)

The problem is exacerbated when I use some of the RNAseq data that was published in one of your earlier papers: https://www.nature.com/articles/ng.3581 Specifically, I am using SRR7882935. Here I am comparing the output of the fasterq-dump and sam-dump from the SRA object.

With sratoolkit:
```
prefetch  SRR7882935
fasterq-dump SRR7882935.sra --split-3

sam-dump SRR7882935.sra | samtools view -S -b > SRR7882935.bam
```

With the TRUST4 commands:
```
# with paired end reads
~/TRUST4/run-trust4 -1 SRR7882935_1.fastq -2 SRR7882935_2.fastq -f /data/trust4_references/human_IMGT+C.fa --ref /data/trust4_references/human_IMGT+C.fa

# with bam
~/TRUST4/run-trust4 -b SRR7882935.bam -f /data/trust4_references/hg38_bcrtcr.fa --ref /data/trust4_references/human_IMGT+C.fa -t 4
```

Which gives very different counts and sequences as described in the attached files. 
[bam_TRUST_SRR7882935_report.txt](https://github.com/liulab-dfci/TRUST4/files/9065817/bam_TRUST_SRR7882935_report.txt)
[fastq_TRUST_SRR7882935_report.txt](https://github.com/liulab-dfci/TRUST4/files/9065818/fastq_TRUST_SRR7882935_report.txt)

Thanks for your help. 

Cheers,

Brian

**Comment by mourisl** [comment]
Thank you for sharing your test results on TRUST4. For the example file, I think the output is the same if you sort the rows. Somehow the output order the entries with the same abundance differently. The output is actually identical on tour server when I tested with your command.

For the SRR7882935 (FZ-122) issue, the bam file output seems have much lower count comparing with your fastq input and the output from my test. I'm not sure how the NCBI SRA stores the BAM file, especially on whether it is sorted and how to handle the unaligned reads. In this case, fastq input is more reliable and reproducible. 
There will be some difference between fastq and bam input, but the difference should be quite small. The advantage of BAM input is that TRUST4 is faster on this input, and can also use some processed fields such as the processed barcode in single-cell analysis. The advantage of fastq input is that you don't need to generate the BAM file if your other analysis does not rely on BAM files, such as kallisto or salmon.

**Comment by BrianLohman** [comment]
Hi @mourisl,

Thank you for your quick reply. I do see that when the example reports are sorted by nucleotide sequence that the bam and fastq reports are identical. Thanks spotting that. 

I wonder what the results would look like if I were to request bucket delivery of the originally submitted BAM file for SRR7882935, instead of extracting it from the .sra object. 

For bulk RNAseq I will stick with the fastq input, unless you think there is a better option. 

Cheers,

Brian

**Comment by mourisl** [comment]
I have added the TRUST4 v1.0.0's results (the version we used in the manuscript) to the validation repo at https://github.com/liulab-dfci/TRUST4_manuscript_evaluation/tree/master/bulk . The results are different from current version due to many bug fixings afterwards. Hope this helps.

**Comment by BrianLohman** [comment]
Great! Thanks for all your help.
