### ISSUE TITLE
use TRUST4_report in VDJtools

### ISSUE THREAD

**Issue by piti295** [liulab-dfci/TRUST4#157]
Hi,
I processed my samples through TRUST4 (via BAM files) and wanted to visualize the output with VDJtools-1.2.1.
however, I encounter some difficulties when trying to run most of VDJtools routines with TRUST_report.tsv as input.
the main issue which repeatedly occurs when running VDJtools is that on `CDR3aa `col, VDJtools would not take "out_of_frame" as a value. this could be "hacked" by replacing "out_of_frame" with "_", however, from what I've learned, there is a difference between these two values.
Also, on the VDJtools documentation page, the description of input to be used in VDJtools does not fully matches TRUST4_report file, with several cardinal columns missing (`Vend, Dstart, Dend, Jstart`)

My questions are:
1.  should i do any modifications in the TRUST4 run command or post processing of the TRUST4_report file in order to use it in VDJtools?
2.  Is there a recommended native software to use for visualization of TRUST4 ouputs?

The TRUST4 command:
`./run-trust4 --abnormalUnmapFlag -b input/path/file.bam -f TRUST4/hg19_bcrtcr.fa --ref TRUST4/human_IMGT+C.fa -o output/dir/of_sample_preffix`

Thanks

**Comment by Z-YWJ** [comment]
I met the same problem. Using VDJtools-1.2.1 to process the data from TRUST4, always report an error, makes my heart tired

**Comment by mourisl** [comment]
You can use "grep -v out_of_frame report.tsv > new_report.tsv" to filter the out of frame fields in the report, and VDJtools should work. (https://github.com/mikessh/vdjtools/issues/151)

I think you can also try immunarch (https://github.com/immunomind/immunarch) to visualize TRUST4's result.

**Comment by piti295** [comment]
> You can use "grep -v out_of_frame report.tsv > new_report.tsv" to filter the out of frame fields in the report, and VDJtools should work. ([mikessh/vdjtools#151](https://github.com/mikessh/vdjtools/issues/151))
> 


Hi, Thanks for your replay.
I've filtered out the lines causing the errors, though i still get other errors such as:
`[ERROR] java.lang.ArithmeticException: Division by zero`
or
`[ERROR] java.lang.ArithmeticException`

> I think you can also try immunarch (https://github.com/immunomind/immunarch) to visualize TRUST4's result.

I'll try doing it,
Thanks

**Comment by Mussa1122** [comment]
Sorry, What is the difference of `amino acids` in `chain1` and `chain2` columns?

**Comment by mourisl** [comment]
@Mussa1122 chain1 is for IGH, TRB, TRD (chains with D genes), and chain2 is for IGK/IGL, TRA and TRG. This information is for the single-cell data, and VDJTools probably could not process the information.

**Comment by piti295** [comment]
Hi, 
Just want to update TRUST4 reports works great on immunarch. 
just install immunarch via:
`devtools::install_github("immunomind/immunarch", ref="trust4-fix")`

Thanks

**Comment by beginner984** [comment]
> Hi, Just want to update TRUST4 reports works great on immunarch. just install immunarch via: `devtools::install_github("immunomind/immunarch", ref="trust4-fix")`
> 
> Thanks

Yes Immunarch works Smoot with TRUST4 output

**Comment by ScienceAdvances** [comment]
> > You can use "grep -v out_of_frame report.tsv > new_report.tsv" to filter the out of frame fields in the report, and VDJtools should work. ([mikessh/vdjtools#151](https://github.com/mikessh/vdjtools/issues/151))
> 
> Hi, Thanks for your replay. I've filtered out the lines causing the errors, though i still get other errors such as: `[ERROR] java.lang.ArithmeticException: Division by zero` or `[ERROR] java.lang.ArithmeticException`
> 
> > I think you can also try immunarch (https://github.com/immunomind/immunarch) to visualize TRUST4's result.
> 
> I'll try doing it, Thanks

"grep -v out_of_frame report.tsv > new_report.tsv"  **works !!!**
