### ISSUE TITLE
TCR CPK and clonality

### ISSUE THREAD

**Issue by jhylwq123** [liulab-dfci/TRUST4#159]
Thank you for developing this tool !
When I used trust-stats.py to calculate the CPK and clonality based on the report.tsv, I found it reported CPK and clonality for TRB and TRA seperately. My question is if I want to calculate the CPK and clonality for the TCR, is it  simply add TRA and TRB together?

**Comment by mourisl** [comment]
They should be regarded separately. I would recommend using TRB's CPK and clonality. This is because TRB chains tend to have higher expression than TRAs, and TRUST4 can recover more CDR3s and the statistics are more reliable.

**Comment by jhylwq123** [comment]
Got it, thanks for your advice!
