### ISSUE TITLE
TRUST4 for singcell data

### ISSUE THREAD

**Issue by toddey** [liulab-dfci/TRUST4#16]
Hi,when we analyzed our single-cell data, we found two clusters interested according to Seurat. And we want to analyzed the TCR/BCR of the clusters, is this can be done by TRUST4?

**Comment by mourisl** [comment]
Yes. You can run TRUST4 with the option "--barcode CB" if you have the cellranger generated bam file. TRUST4 will generate a report file with the TCR/BCR chain information for each cell barcode. The section "Single-cell data, e.g. 10X Genomics data:" in the README will have more information on this.
