### ISSUE TITLE
Phylogenetic tree and other analysis

### ISSUE THREAD

**Issue by saramoein372** [liulab-dfci/TRUST4#162]
Hello,

I have a question: does you package has specific pipeline for generating the phylogenetic tree?
And more downstream analysis on BCR and TCR data?

Thank you,
Sara

**Comment by mourisl** [comment]
Sorry, we don't. TRUST4 is for assemble the TCRs and BCRs. You may try other methods like IgPhyML. We provide a script "trust-stats.py" in the scripts folder to calculate common diversity measures (entorpy, clonality,...) for each sample. You can also use methods like Immunarch for downstream analysis.

**Comment by saramoein372** [comment]
Thank you for your response and thanks for such a great package!

**Comment by saramoein372** [comment]
I have another question: would you please provide some details about the
main strategy for defining the BCR clones? Is it based on
levenshtein distance on CDR3?

Appreciate it.

Thanks,
Sara

**Comment by mourisl** [comment]
Do you mean BCRs from the same lineage? It's usually based on the hamming distance of CDR3 (so the CDR3s are of the same length), maybe including V, J gene assignment.

**Comment by saramoein372** [comment]
Thank you.

I was wondering if you have any published results for the healthy sample as
negative control? Or if you have nay BCR fastq files that I run to see the
BCR clones on the healthy sample.

Any information would be appreciated.

Thanks,
Sara

**Comment by mourisl** [comment]
It seems we continued the discussion in another thread. Let me close this issue for now, and please feel to reopen it if you have other questions on the analysis.
