### ISSUE TITLE
error wiith trust4

### ISSUE THREAD

**Issue by Echoloria** [liulab-dfci/TRUST4#164]
Hi,
   When I used Trust4 to obtain TCR/BCR information from bulk RNAseq data, I met an error:

**[Tue Nov  8 23:58:03 2022] TRUST4 begins.
[Tue Nov  8 23:58:03 2022] SYSTEM CALL: /home/software/TRUST4/fastq-extractor -t 1 -f /home/software/TRUST4/hg38_bcrtcr.fa -o TRUST_78_1_toassemble  -1 78_1.fastq.gz -2 78_2.fastq.gz -2 ./OUT
Can't exec "/home/software/TRUST4/fastq-extractor": No such file or directory at /home/software/TRUST4/run-trust4 line 49.
system /home/software/TRUST4/fastq-extractor -t 1 -f /home/software/TRUST4/hg38_bcrtcr.fa -o TRUST_78_1_toassemble  -1 78_1.fastq.gz -2 78_2.fastq.gz -2 ./OUT failed: -1 at /home/software/TRUST4/run-trust4 line 49.**

How could I solve this? Thanks.

Echo.

**Comment by mourisl** [comment]
Have you run "make" in the TRUST4 folder to compile the executable files?

**Comment by Echoloria** [comment]
Sorry, I didn't do that, I'll try it, thanks a lot!

**Comment by mourisl** [comment]
It seems the issue has been resolved. I'll close this thread for now, and if you find any error, please feel free to reopen this issue. Thank you.
