### ISSUE TITLE
Two reads from the unaligned fragment are not showing up together. Please use -u option.

### ISSUE THREAD

**Issue by whitehilltea** [liulab-dfci/TRUST4#17]
Dear Developers,

I have the paired-end RNA-seq data. I used Hisat2 to align them and then use the coordinated sorted bam as input to run the Trust4. I did not use PicardMarkDuplicates to remove some reads.

I encounter the error message:

`Two reads from the unaligned fragment are not showing up together. Please use -u option.`

Here is my command history running on Google Cloud Docker(Terra)

```shell
[Mon Jun 22 02:22:45 2020] TRUST4 begins.
[Mon Jun 22 02:22:45 2020] SYSTEM CALL: //bam-extractor -b /cromwell_root/fc-secure-99ea097c-0cfb-4db2-8163-488bcf97d058/5ad13ae3-96d8-4095-b8ef-ac1ebacbaae3/MyBestWorkflow/3bf92ca1-b211-427b-995a-f52f4ec0dd74/call-SamToCoordinateSortedBam/cacheCopy/Pt-UID-01-2_on-treatment.coordinate_sorted.bam -t 1 -f /hg38_bcrtcr.fa -o TRUST_Pt-UID-01-2_on-treatment_toassemble 
[Mon Jun 22 02:22:45 2020] Start to extract candidate reads from bam file.
SRRxxxxxx.6.1
SRRxxxxxx.6.2
Two reads from the unaligned fragment are not showing up together. Please use -u option.
system //bam-extractor -b /cromwell_root/fc-secure-99ea097c-0cfb-4db2-8163-488bcf97d058/5ad13ae3-96d8-4095-b8ef-ac1ebacbaae3/MyBestWorkflow/3bf92ca1-b211-427b-995a-f52f4ec0dd74/call-SamToCoordinateSortedBam/cacheCopy/Pt-UID-01-2_on-treatment.coordinate_sorted.bam -t 1 -f /hg38_bcrtcr.fa -o TRUST_Pt-UID-01-2_on-treatment_toassemble  failed: 256 at /run-trust4 line 34.
```

My command for this task is like this:

```shell
/run-trust4 -t 1 -b ${input_bam} -f /hg38_bcrtcr.fa --ref /human_IMGT+C.fa
```

I scrutinized the two reads **SRRxxxxxx.6.1** and **SRRxxxxxx.6.2** mentioned in the error message

```shell
samtools view Pt-UID-01-2_on-treatment.coordinate_sorted.bam | grep -F SRRxxxxxx.6.1

SRRxxxxxx.6.1  77      *       0       0       *       *       0       0       ACATGGGATTAATCCCCTGGCCCAACCCGTCATCTACT  AAAAAEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEEE    YT:Z:UP

samtools view Pt-UID-01-2_on-treatment.coordinate_sorted.bam | grep -F SRRxxxxxx.6.2
SRRxxxxxx.6.2  141     *       0       0       *       *       0       0       GGCCTACTCAGGTAAAAAAAAAGTGCGAGCTTAGCGCT  AAAAAEEEEEEEEEEEEE####################    YT:Z:UP
```

It seems that both mates of the fragment were unmapped, however, the error message suggest me to drop the paired-end data to single-end data to make the Trust4 run, which seems a lot of information loss. Perhaps the trust4 program should be able to handle this common phenomena that both mates of a fragment are unmapped.

Is this something that you could fix in the bam extractor of Trust4 or something wrong with my raw data?

Waiting for your suggestions.

Thanks.

**Comment by mourisl** [comment]
TRUST4 uses read id to associate mate pairs. It only recognizes the same read id or "/1,/2" suffix for this. You can rename the read ids in your bam file for TRUST4 to work.

**Comment by whitehilltea** [comment]
Thanks for your quick suggestions. I will give a try.

**Comment by whitehilltea** [comment]
I tried renaming the reads and succeeded in running the trust4. Thanks for your suggestions.

**Comment by mourisl** [comment]
I've added the option "--mateIdSuffixLen" to handle these unconventional ".1,.2" suffixes. You can use "--mateIdSuffixLen 2" so TRUST4 can ignore the last two characters of the read id.
