### ISSUE TITLE
No such file or directory Error

### ISSUE THREAD

**Issue by dimitrisokolowskei** [liulab-dfci/TRUST4#174]
Hi,

I am trying to use TRUST4 on 10X genomics data. I'm using the following code:
```sh
./run-trust4 -f hg38_bcrtcr.fa --ref human_IMGT+C.fa -u SRR14219615_S1_L001_R2_001.fastq.gz --barcode SRR14219615_S1_L001_R1_001.fastq.gz --barcodeRange 0 15 + --barcodeWhitelist path/cellranger-7.1.0/lib/python/cellranger/barcodes/737K-august-2016.txt -t 34
```
However, I receive an error as output:
```sh
Can't exec "/path/TRUST4/fastq-extractor": No such file or directory at ./run-trust4 line 51.
```
It seems that the file **fastq-extractor** is missing. The only file that look like it is **FastqExtractor.cpp**. I just cloned the TRUST 4 repo. I would appreciate some help on this issue.

Best regards

**Comment by mourisl** [comment]
Have you run "make" to compile the executables?

**Comment by dimitrisokolowskei** [comment]
Hi,

Shortly after I sent this issue and realized that I haven't compiled the repo. Everthing is working perfectly. My bad. 

All the best
