### ISSUE TITLE
Library size normalization?

### ISSUE THREAD

**Issue by ksm113** [liulab-dfci/TRUST4#18]
Hi,

I see that TRUST reports the frequency of a given sequence, defined as the number of reads belonging to that contig divided by the total number of CD3R reads. I see also that BCR and TCR frequency are normalized separately. It was not clear to me whether the overall library size is used for normalization.

Should downstream analyses correct for library size, or has that been accounted for in TRUST4? The question is applicable only when comparing absolute abundance between samples, of course.

**Comment by mourisl** [comment]
The report file does not take the library size into account. So if your downstream analysis involves infiltration level, you need to normalize with the library size (total reads in the bam or fastq file).

**Comment by ksm113** [comment]
Clear, thank you!
