### ISSUE TITLE
Meaning of special character

### ISSUE THREAD

**Issue by pinholeye** [liulab-dfci/TRUST4#185]
Hi, 

I am using data from the kit: Takara Bio SMARTer Human TCR v2
I run trust4 on trimmed and  deduplicated fastq.gz files using the command:

```
   run-trust4 \
        -1 ${fastq1} \
        -2 ${fastq2} \
        -f ${ref_genome} \
        --ref ${ref_imgt} \
        -t 16 \
        --od ./output
```

and I am getting CDR3 aa sequences that contain special characters such as "_" and "?" 
What is the meaning of the special characters? Is there documentation where I can find this information?

Examples:
CDR3aaa: CAVPLGRVARSCSLQGEPC_RW
CDRaaa:  CASSPSPRITD?QYF

**Comment by mourisl** [comment]
"_" means stop codon, "?" means there is an N in the nucleotide sequence so we can't decide its amino acid. We provide a wrapper trust-smartseq.pl to process SMART-seq, which can pick the representative CDR3s for each cell. Does it apply to the SMARTer Human TCR v2?

**Comment by pinholeye** [comment]
Thank you for the explanation. The wrapper can be also used for this kind of data :+1:
