### ISSUE TITLE
Read1/2 list for smart-seq wrapper

### ISSUE THREAD

**Issue by kbruton** [liulab-dfci/TRUST4#188]
I tried using the smart-seq wrapper for BCR assembly from <100 cells. The following seemed as though it was running properly: 
```
perl trust-smartseq.pl -1 /Users/xxx/Desktop/for_trust4/read1_list.txt -2 /Users/xxx/Desktop/for_trust4/read2_list.txt -t 16 -f /Users/xxx/TRUST4/mouse/GRCm38_bcrtcr.fa --ref /Users/xxx/TRUST4/mouse/mouse_IMGT+C.fa -o TRUST
```

```
[Wed Mar 15 18:11:14 2023] SYSTEM CALL: perl /Users/xxx/TRUST4/trust-simplerep.pl tmp_smartseq_cdr3.out  > tmp_smartseq_report.tsv
[Wed Mar 15 18:11:15 2023] SYSTEM CALL: perl /Users/xxx/TRUST4/trust-airr.pl tmp_smartseq_report.tsv tmp_smartseq_annot.fa --airr-align tmp_smartseq_airr_align.tsv > tmp_smartseq_airr.tsv
[Wed Mar 15 18:11:16 2023] TRUST4 finishes.
```

However, the AIRR file only contains alignments from the last sample in my read_list. Presumably the issue is with how I structured the read1_list and read2_list...?
Currently I have two .txt files that contain the path to file. Paths are separated by a single space. Could you advise how I can fix this?

**Comment by mourisl** [comment]
The list file assumes that each path/cell is on its own line instead of space-separated file. In other words, if you have n cells, there would be n rows in the list file. Could you please reformat it and give it a try? Thanks.
