### ISSUE TITLE
the meaning of the first two columns: read_count and frequency(proportion of read_count)

### ISSUE THREAD

**Issue by whitehilltea** [liulab-dfci/TRUST4#19]
Dear Developers,

I have a question about the fields in the **trust_report.tsv**. In your readme file on github, it is written like this:

> The output trust_report.tsv is a tsv file. The fields are:
>
> **read_count**	**frequency(proportion of read_count)**	CDR3_dna	CDR3_amino_acids	V	D	J	C 
>
> For frequency, the BCR(IG) and TCR(TR) chains are normalized respectively.

We are studying RNA-seq data from different experiments from different bio-projects, so we are interested in the meaning of the first two columns: **read_count** and **frequency(proportion of read_count)**, so that we can do proper count and frequency normalization, combination of raw count, and extraction of T-cells from the trust_report.tsv.

Based on my understanding, the **read_count** is how many raw read counts are mapped to the specific clonotype. In the scenario of TCR, **frequency** is the number of reads mapped to the specific clonotype divided by the number of reads mapped to all the TCR region. In the scenario of BCR, **frequency** is the number of reads mapped to the specific clonotype divided by the number of reads mapped to all the BCR region.  Am I correct?

However, there are still come confusions:

1. The **trust_report.tsv** contains T cells and B cells, since the **frequency** is calculated for T cells and B cells, respectively, if I only extract T cells from the **trust_report.tsv**, do I need to re-calculate the **frequency** for T cells?

2. in your 2016 Nature Genetics paper, you mentioned  `clonotypes per thousand (kilo) reads (CPK)`. Is this CPK value used in the **read_count** or **frequency** in the **trust_report_tsv**? Or CPK is only used in your paper to compare the diversity across data sets?

3. In your github readme, you mentioned `For frequency, the BCR(IG) and TCR(TR) chains are normalized respectively`. How is the **frequency** normalized? Is the normalization by CPK or something else? Is the **read_count** derived from the raw count without any normalization?

Waiting for your suggestions.

Thanks a lot.

**Comment by mourisl** [comment]
In the report file, the read count is the number of reads covering/overlapping with this CDR3. Your interpretation of the frequency is correct (except it is also for CDR3 region).

For your confusions:
1. You don't need to recalculate the frequency.
2. CPK value is not used in the report. You can compute CPK by the number of unique CDR3 divided by the total number reads for that chain (sum of column 1 from chosen rows) and then times 1000.
3. The read_count is the raw read count, there is no normalization on that. For TCR, the frequency is its column 1 divided by the sum of read_count of the TCR rows.

Does this help?

Thanks,
Li

**Comment by whitehilltea** [comment]
Hi, Li,

I selected several report files to do the manual frequency calculation based on the read_count. The calculated frequencies for T cell or B cell are both concordant with your described formula.

Thanks a lot for your explanation. It is very clear and helpful. Now I can think about how to merge my data from multiple projects.

Thanks a again for providing such a good tool for the science community.
