### ISSUE TITLE
inconsistency between trust4 and run-trust4 binaries

### ISSUE THREAD

**Issue by amoschoomy** [liulab-dfci/TRUST4#198]
the trust4 executable does not contain an optional --ref flag but run-trust4 contains it, I know based on the github repo, we're supposed to use run-trust4 but what's the point of trust4 executable then?

**Comment by mourisl** [comment]
trust4 is only for assembling the contigs. The reference file (-f) option is mainly for very rough VDJ annotation. The file from "--ref" option has more detailed sequence information in IMGT format, such as sequence gaps allowing the identification of CDR3 boundaries. This --ref file will be used in the executable "annotator" to provide more accurate VDJ annotations and CDR3 region identification.

I introduce this "--ref" option to optimize the case where the genome has IMGT reference sequences. For some non-model genomes without IMGT VDJ sequences, the annotator program will try to use the "-f" sequences to annotation VDJ and then identify CDR3 using sequence motifs.

Hope this helps.
