### ISSUE TITLE
Cannot install through conda

### ISSUE THREAD

**Issue by YIPhiufung1997** [liulab-dfci/TRUST4#199]
hi, I fail to install TRUST4 through "conda install -c bioconda trust4". The command was killed and failed to execute. It is rare because I successfully installed on another device a few months back. may I get your help in fixing this issue?

**Comment by mourisl** [comment]
I think this is a conda or your sever's issue. Do you know why it is killed, such as out of memory?

**Comment by mourisl** [comment]
Based on the other issue thread, it seems TRUST4 can be installed now. I'll close the issue for now.
