### ISSUE TITLE
Difference between TRUST4 and TRUST3?

### ISSUE THREAD

**Issue by jbreynier** [liulab-dfci/TRUST4#2]
Hello,

Thank you very much for developing this tool. I have already run my analysis with the previous version of TRUST, and I was wondering if there was any advantage/particular reason to use TRUST4 over TRUST3. Thanks!

J-B

**Comment by mourisl** [comment]
The code of TRUST4 starts from scratch.  It is more sensitive, precise and much more computationally efficient. TRUST4 produces longer assemblies, hence has significantly better performance on identifying anchoring V, J, C genes. For some abundant BCR/TCRs, you can obtain their full-ength sequences.

**Comment by jbreynier** [comment]
Thank you for the quick reply!
