### ISSUE TITLE
read number issue

### ISSUE THREAD

**Issue by njwehi** [liulab-dfci/TRUST4#202]
the statistics of read numbers seems not consistent between outputs.
for example, 
in trust4 **running log**, "Found **1866804** reads." and "Assembled **1158765** reads."
in **airr.tsv** , the colSum of **consensus_count** is **208044**.

How are those "consensus_count"s counted? Is it the read numbers that are mapped the single assemble (for example assemble0_0)?

**Comment by mourisl** [comment]
The "Found XXX reads" includes reads from the constant gene that is close to the 3' end (which we don't try to assemble that far). It also contains many false positive candidate reads from the non-rigorous fastq-extractor/bam-extractor stage. "Assembled XXX reads" are the reads actually used in the assemblies.

The consensus count is the number of reads that are mapped to the single assembly and also overlap with the CDR3 region of that assembly.

**Comment by njwehi** [comment]
Thanks very much for your quick response! Very helpful answers!
I have one comment: in bulk RNAseq, indeed it is no necessary to assemble that far to 3-UTR while for scRNAseq, it is valuable to try to assemble the full length transcripts since the constant genes are also informative by identifying the alleles of the constant genes.
here I have two more questions,
1. what is the definition of an assemble? how are those assembles coded? One assemble id has two numbers, what do they mean?
2. in the air.tsv output, why are there some "\xd7"s with the sequences of "germline_alignment"?

Thanks again!

**Comment by njwehi** [comment]
one question:
"The consensus count is the number of reads that are mapped to the single assembly and also overlap with the CDR3 region of that assembly."
 
what is the extent of "overlap" here? how many nucleotides?

**Comment by mourisl** [comment]
The minimum overlap size is 4bp.

**Comment by njwehi** [comment]
thanks for your kind answer. Could you also answer these two questions?

1. what is the definition of an assemble? how are those assembles coded? One assemble id has two numbers, what do they mean?
2. in the air.tsv output, why are there some "\xd7"s within the sequences of "germline_alignment"?

**Comment by mourisl** [comment]
Sorry, I missed your previous issue.

> ''I have one comment: in bulk RNAseq, indeed it is no necessary to assemble that far to 3-UTR while for scRNAseq, it is valuable to try to assemble the full length transcripts since the constant genes are also informative by identifying the alleles of the constant genes.

We still assemble about 200bp for constant gene, which is enough to distinguish isotypes, and maybe some alleles?

1. An assembly is the assembled contigs/scaffolding by stitching overlapped reads. You can refer to TRUST4's manuscript for more detail. The assemble id usually has one number in it. What is your assemble (contig) id looks like? 
2. I think this could be a bug in the program if the contig has a gap (NNNNNNN). Is that the case? I recently pushed a fix to github repo regarding this, could you give it a try to see whether the abnormal symbols go away?

**Comment by njwehi** [comment]
Thanks so much for your quick responses.
"The assemble id usually has one number in it. What is your assemble (contig) id looks like?"
- the ids are assigned as assemble0_0, assemble0_1, assemble0_2, ..., assemble0_n, assemble1_0, assemble1_1, ..., assemblen_0. I was wondering what is the relationship between assembles with the same prefixes, for example, all assembles with the prefix "assemble0_". Do they share something?
"could you give it a try to see whether the abnormal symbols go away?"
- I will have another try using the recent version. currently, I just simply replaced "\xd7"s with Ns.

**Comment by mourisl** [comment]
Oh, because the assembled contig is the consensus of the sequences, which may encode somatic hypermutations, so TRUST4 will realign the reads to the CDR3 region to extract those variations. As a result, I use the second number to index those variations.
