### ISSUE TITLE
Question regarding available references

### ISSUE THREAD

**Issue by kboufea** [liulab-dfci/TRUST4#204]
Hello, 

I would like to ask if the [hg19_bcrtcr](https://github.com/liulab-dfci/TRUST4/blob/master/hg19_bcrtcr.fa) reference you provide also comes from IMGT. Due to licensing issues, it is not possible to use the IMGT database. Could you please let me know of an alternative human reference?

Thank you,
Katerina

**Comment by mourisl** [comment]
The hg38_bcrtcr.fa and hg19_bcrtcr.fa were obtained by concatenating the exons sequencing from those reference genomes guided by the genome annotation from Gencode. So they are not created from IMGT. Just out of curiosity, does IMGT have any license restrictions?

**Comment by kboufea** [comment]
Thanks for your response. Yes, IMGT is only free for academic users and non profit organisations. You can find more info on this [link](https://www.imgt.org/#termsofuse), but briefly:

> the IMGT® software and data are provided to the academic users and NPO's (Not for Profit Organization(s)) under the [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) license. Any other use of IMGT® material, from the private sector, needs a financial arrangement with CNRS.

**Comment by mourisl** [comment]
Thank you for the link, I did not know about this. FYI, the bcrtcr.fa is generated by the script "BuildDatabaseFa.pl" as described here https://github.com/liulab-dfci/TRUST4#build-custom-vjc-gene-database-files-for--f-and---ref .
