### ISSUE TITLE
run-trust4 failed: 34304 at run-trust4 line 54

### ISSUE THREAD

**Issue by joyshen123** [liulab-dfci/TRUST4#205]
hello!
I encountered an error when using trust4 to process transcriptome RNA-seq data. Can you help me?

see details and fastq file below.

run-trust4 -1 SRR5388335_1.fastq.gz -2 SRR5388335_2.fastq.gz -f /home/shenyy/data/trust4_ref/hg38_bcrtcr.fa --ref /home/shenyy/data/trust4_ref/human_IMGT+C.fa -t 16
[Thu Jul 27 16:00:49 2023] TRUST4 begins.
[Thu Jul 27 16:00:49 2023] SYSTEM CALL: /home/shenyy/miniconda3/envs/syyenv/bin/fastq-extractor -t 16 -f /home/shenyy/data/trust4_ref/hg38_bcrtcr.fa -o TRUST_SRR5388335_1_toassemble  -1 SRR5388335_1.fastq.gz -2 SRR5388335_2.fastq.gz
[Thu Jul 27 16:00:50 2023] Start to extract candidate reads from read files.
[Thu Jul 27 16:07:00 2023] Finish extracting reads.
[Thu Jul 27 16:07:00 2023] SYSTEM CALL: /home/shenyy/miniconda3/envs/syyenv/bin/trust4  -t 16 -f /home/shenyy/data/trust4_ref/hg38_bcrtcr.fa -o TRUST_SRR5388335_1 -1 TRUST_SRR5388335_1_toassemble_1.fq -2 TRUST_SRR5388335_1_toassemble_2.fq
[Thu Jul 27 16:07:00 2023] Read in and count kmers for 100000 reads.
[Thu Jul 27 16:07:01 2023] Read in and count kmers for 200000 reads.
[Thu Jul 27 16:07:02 2023] Read in and count kmers for 300000 reads.
[Thu Jul 27 16:07:02 2023] Read in and count kmers for 400000 reads.
[Thu Jul 27 16:07:03 2023] Read in and count kmers for 500000 reads.
[Thu Jul 27 16:07:04 2023] Read in and count kmers for 600000 reads.
[Thu Jul 27 16:07:07 2023] Found 575572 reads.
[Thu Jul 27 16:07:08 2023] Finish sorting the reads.
[Thu Jul 27 16:07:11 2023] Finish rough annotations.
[Thu Jul 27 16:07:11 2023] Processed 100000 reads (31709 are used for assembly).
[Thu Jul 27 16:07:11 2023] Processed 200000 reads (47255 are used for assembly).
[Thu Jul 27 16:07:11 2023] Processed 300000 reads (75794 are used for assembly).
[Thu Jul 27 16:07:13 2023] Processed 400000 reads (144247 are used for assembly).
[Thu Jul 27 16:07:18 2023] Processed 500000 reads (206969 are used for assembly).
[Thu Jul 27 16:07:25 2023] Assembled 255573 reads.
[Thu Jul 27 16:07:25 2023] Try to rescue 3948 reads for assembly.
[Thu Jul 27 16:07:25 2023] Rescued 1219 reads.
[Thu Jul 27 16:07:27 2023] Extend assemblies by mate pair information.
[Thu Jul 27 16:07:30 2023] Remove redundant assemblies.
[Thu Jul 27 16:07:33 2023] Finish assembly.
[Thu Jul 27 16:07:34 2023] SYSTEM CALL: /home/shenyy/miniconda3/envs/syyenv/bin/annotator -f /home/shenyy/data/trust4_ref/human_IMGT+C.fa -a TRUST_SRR5388335_1_final.out -t 16 -o TRUST_SRR5388335_1  -r TRUST_SRR5388335_1_assembled_reads.fa --airrAlignment > TRUST_SRR5388335_1_annot.fa
[Thu Jul 27 16:07:34 2023] Start to annotate assemblies.
*** Error in `/home/shenyy/miniconda3/envs/syyenv/bin/annotator': free(): invalid next size (normal): 0x000055b324882860 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x7f4a55928679]
/home/shenyy/miniconda3/envs/syyenv/bin/annotator(+0xdb9a)[0x55b322a7bb9a]
/home/shenyy/miniconda3/envs/syyenv/bin/annotator(+0x3d44)[0x55b322a71d44]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f4a558c9505]
/home/shenyy/miniconda3/envs/syyenv/bin/annotator(+0x5d91)[0x55b322a73d91]
======= Memory map: ========
55b322a6e000-55b322a70000 r--p 00000000 fd:02 64424578615                /home/shenyy/miniconda3/envs/syyenv/bin/annotator
55b322a70000-55b322a91000 r-xp 00002000 fd:02 64424578615                /home/shenyy/miniconda3/envs/syyenv/bin/annotator
55b322a91000-55b322a94000 r--p 00023000 fd:02 64424578615                /home/shenyy/miniconda3/envs/syyenv/bin/annotator
55b322a94000-55b322a95000 r--p 00026000 fd:02 64424578615                /home/shenyy/miniconda3/envs/syyenv/bin/annotator
55b322a95000-55b322a96000 rw-p 00027000 fd:02 64424578615                /home/shenyy/miniconda3/envs/syyenv/bin/annotator
55b322a96000-55b322a9b000 rw-p 00000000 00:00 0
55b32378b000-55b329cab000 rw-p 00000000 00:00 0                          [heap]
7f4a04000000-7f4a0404c000 rw-p 00000000 00:00 0
7f4a0404c000-7f4a08000000 ---p 00000000 00:00 0
7f4a08000000-7f4a0806c000 rw-p 00000000 00:00 0
7f4a0806c000-7f4a0c000000 ---p 00000000 00:00 0
7f4a0c000000-7f4a0c188000 rw-p 00000000 00:00 0
7f4a0c188000-7f4a10000000 ---p 00000000 00:00 0
7f4a10000000-7f4a100c2000 rw-p 00000000 00:00 0
7f4a100c2000-7f4a14000000 ---p 00000000 00:00 0
7f4a14000000-7f4a1406d000 rw-p 00000000 00:00 0
7f4a1406d000-7f4a18000000 ---p 00000000 00:00 0
7f4a18000000-7f4a18117000 rw-p 00000000 00:00 0
7f4a18117000-7f4a1c000000 ---p 00000000 00:00 0
7f4a1c000000-7f4a1c157000 rw-p 00000000 00:00 0
7f4a1c157000-7f4a20000000 ---p 00000000 00:00 0
7f4a20000000-7f4a20298000 rw-p 00000000 00:00 0
7f4a20298000-7f4a24000000 ---p 00000000 00:00 0
7f4a24000000-7f4a24084000 rw-p 00000000 00:00 0
7f4a24084000-7f4a28000000 ---p 00000000 00:00 0
7f4a28000000-7f4a2811e000 rw-p 00000000 00:00 0
7f4a2811e000-7f4a2c000000 ---p 00000000 00:00 0
7f4a2e7fd000-7f4a2e7fe000 ---p 00000000 00:00 0
7f4a2e7fe000-7f4a2effe000 rw-p 00000000 00:00 0
7f4a2effe000-7f4a2efff000 ---p 00000000 00:00 0
7f4a2efff000-7f4a2f7ff000 rw-p 00000000 00:00 0
7f4a30000000-7f4a302c6000 rw-p 00000000 00:00 0
7f4a302c6000-7f4a34000000 ---p 00000000 00:00 0
7f4a347f9000-7f4a347fa000 ---p 00000000 00:00 0
7f4a347fa000-7f4a34ffa000 rw-p 00000000 00:00 0
7f4a34ffa000-7f4a34ffb000 ---p 00000000 00:00 0
7f4a34ffb000-7f4a357fb000 rw-p 00000000 00:00 0
7f4a38000000-7f4a380f9000 rw-p 00000000 00:00 0
7f4a380f9000-7f4a3c000000 ---p 00000000 00:00 0
7f4a3c000000-7f4a3c1fc000 rw-p 00000000 00:00 0
7f4a3c1fc000-7f4a40000000 ---p 00000000 00:00 0
7f4a40000000-7f4a401af000 rw-p 00000000 00:00 0
7f4a401af000-7f4a44000000 ---p 00000000 00:00 0
7f4a44000000-7f4a441f7000 rw-p 00000000 00:00 0
7f4a441f7000-7f4a48000000 ---p 00000000 00:00 0
7f4a48000000-7f4a48559000 rw-p 00000000 00:00 0
7f4a48559000-7f4a4c000000 ---p 00000000 00:00 0
7f4a4f493000-7f4a558a7000 rw-p 00000000 00:00 0
7f4a558a7000-7f4a55a6a000 r-xp 00000000 fd:00 335545384                  /usr/lib64/libc-2.17.so
7f4a55a6a000-7f4a55c6a000 ---p 001c3000 fd:00 335545384                  /usr/lib64/libc-2.17.so
7f4a55c6a000-7f4a55c6e000 r--p 001c3000 fd:00 335545384                  /usr/lib64/libc-2.17.so
7f4a55c6e000-7f4a55c70000 rw-p 001c7000 fd:00 335545384                  /usr/lib64/libc-2.17.so
7f4a55c70000-7f4a55c75000 rw-p 00000000 00:00 0
7f4a55c75000-7f4a55d76000 r-xp 00000000 fd:00 335545392                  /usr/lib64/libm-2.17.so
7f4a55d76000-7f4a55f75000 ---p 00101000 fd:00 335545392                  /usr/lib64/libm-2.17.so
7f4a55f75000-7f4a55f76000 r--p 00100000 fd:00 335545392                  /usr/lib64/libm-2.17.so
7f4a55f76000-7f4a55f77000 rw-p 00101000 fd:00 335545392                  /usr/lib64/libm-2.17.so
7f4a55f77000-7f4a56020000 r--p 00000000 fd:02 40813043765                /home/shenyy/miniconda3/envs/syyenv/lib/libstdc++.so.6.0.31
7f4a56020000-7f4a560c0000 r-xp 000a9000 fd:02 40813043765                /home/shenyy/miniconda3/envs/syyenv/lib/libstdc++.so.6.0.31
7f4a560c0000-7f4a56147000 r--p 00149000 fd:02 40813043765                /home/shenyy/miniconda3/envs/syyenv/lib/libstdc++.so.6.0.31
7f4a56147000-7f4a56152000 r--p 001cf000 fd:02 40813043765                /home/shenyy/miniconda3/envs/syyenv/lib/libstdc++.so.6.0.31
7f4a56152000-7f4a56156000 rw-p 001da000 fd:02 40813043765                /home/shenyy/miniconda3/envs/syyenv/lib/libstdc++.so.6.0.31
7f4a56156000-7f4a5615a000 rw-p 00000000 00:00 0
7f4a5615a000-7f4a56171000 r-xp 00000000 fd:00 335545410                  /usr/lib64/libpthread-2.17.so
7f4a56171000-7f4a56370000 ---p 00017000 fd:00 335545410                  /usr/lib64/libpthread-2.17.so
7f4a56370000-7f4a56371000 r--p 00016000 fd:00 335545410                  /usr/lib64/libpthread-2.17.so
7f4a56371000-7f4a56372000 rw-p 00017000 fd:00 335545410                  /usr/lib64/libpthread-2.17.so
7f4a56372000-7f4a56376000 rw-p 00000000 00:00 0
7f4a56376000-7f4a56398000 r-xp 00000000 fd:00 335545377                  /usr/lib64/ld-2.17.so
7f4a5654a000-7f4a5654f000 rw-p 00000000 00:00 0
7f4a5654f000-7f4a56553000 r--p 00000000 fd:02 60164992021                /home/shenyy/miniconda3/envs/syyenv/lib/libgcc_s.so.1
7f4a56553000-7f4a56565000 r-xp 00004000 fd:02 60164992021                /home/shenyy/miniconda3/envs/syyenv/lib/libgcc_s.so.1
7f4a56565000-7f4a56568000 r--p 00016000 fd:02 60164992021                /home/shenyy/miniconda3/envs/syyenv/lib/libgcc_s.so.1
7f4a56568000-7f4a56569000 r--p 00019000 fd:02 60164992021                /home/shenyy/miniconda3/envs/syyenv/lib/libgcc_s.so.1
7f4a56569000-7f4a5656a000 rw-p 0001a000 fd:02 60164992021                /home/shenyy/miniconda3/envs/syyenv/lib/libgcc_s.so.1
7f4a5656a000-7f4a5656b000 rw-p 00000000 00:00 0
7f4a5656b000-7f4a5656e000 r--p 00000000 fd:02 15033837644                /home/shenyy/miniconda3/envs/syyenv/lib/libz.so.1.2.13
7f4a5656e000-7f4a5657d000 r-xp 00003000 fd:02 15033837644                /home/shenyy/miniconda3/envs/syyenv/lib/libz.so.1.2.13
7f4a5657d000-7f4a56584000 r--p 00012000 fd:02 15033837644                /home/shenyy/miniconda3/envs/syyenv/lib/libz.so.1.2.13
7f4a56584000-7f4a56585000 r--p 00018000 fd:02 15033837644                /home/shenyy/miniconda3/envs/syyenv/lib/libz.so.1.2.13
7f4a56585000-7f4a56586000 rw-p 00019000 fd:02 15033837644                /home/shenyy/miniconda3/envs/syyenv/lib/libz.so.1.2.13
7f4a56586000-7f4a56587000 rw-p 00000000 00:00 0
7f4a56593000-7f4a56597000 rw-p 00000000 00:00 0
7f4a56597000-7f4a56598000 r--p 00021000 fd:00 335545377                  /usr/lib64/ld-2.17.so
7f4a56598000-7f4a56599000 rw-p 00022000 fd:00 335545377                  /usr/lib64/ld-2.17.so
7f4a56599000-7f4a5659a000 rw-p 00000000 00:00 0
7ffeea5da000-7ffeea5fb000 rw-p 00000000 00:00 0                          [stack]
7ffeea5fb000-7ffeea5fd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
sh: line 1: 76343 Aborted                 /home/shenyy/miniconda3/envs/syyenv/bin/annotator -f /home/shenyy/data/trust4_ref/human_IMGT+C.fa -a TRUST_SRR5388335_1_final.out -t 16 -o TRUST_SRR5388335_1 -r TRUST_SRR5388335_1_assembled_reads.fa --airrAlignment > TRUST_SRR5388335_1_annot.fa
system /home/shenyy/miniconda3/envs/syyenv/bin/annotator -f /home/shenyy/data/trust4_ref/human_IMGT+C.fa -a TRUST_SRR5388335_1_final.out -t 16 -o TRUST_SRR5388335_1  -r TRUST_SRR5388335_1_assembled_reads.fa --airrAlignment > TRUST_SRR5388335_1_annot.fa failed: 34304 at /home/shenyy/miniconda3/envs/syyenv/bin/run-trust4 line 54.

SRR5388335_1.fastq.gz

@SRR5388335.1 1 length=51
GGGTGGTTGTGTTGATTCAAATTANNTGTTTTTTGGAAAGTCATGTCAGTN
+SRR5388335.1 1 length=51
@@@DDFDDFFDDDHHHIIIGGFAF##11?FHIJGIHEBGFHIJJJIJIJH#
@SRR5388335.2 2 length=51
CTCCGAAGGACAGTGGGGTAAAGGCCTGTGCCCCTATGGGAAGGGTAGGAG
+SRR5388335.2 2 length=51
?@@DDDDA1<<3<AFFI6C:E9EFECDGFFEFFIB6B4BFFE?FIFFIEF3
@SRR5388335.3 3 length=51
CCTGTGGCCAGGAGCACATCCCCAAAATCCAGCCGCACTGACCAGATGGGG
+SRR5388335.3 3 length=51
;=@DADDDDD;DF7;::C?G?@F<BF?<FHGDDFAE0@:FGGHIB(8=8@;
@SRR5388335.4 4 length=51
CCGGTCTCTGATCCGGACCCACGGGCCGCTCCTGGTGCCCCCCCCCCCCCC
+SRR5388335.4 4 length=51
@@@DDDDDHHDHHIIIGHIIBHGB###########################
@SRR5388335.5 5 length=51
CCTGATCCAGAGTAGTCCTCAGAAAGTGGGAAGATACGATTCAAGTCCTGG
+SRR5388335.5 5 length=51
CCCFFFFFHHHHFHHIJJJJJJIJJJBHIIIIIJJJJJIJIJJJJJJIJJJ

SRR5388335_2.fastq.gz

@SRR5388335.1 1 length=51
NNNNNNNNNNNNNNNNNNNNNNNTTANNNNNNNNNNNNNNNNNNNNNNNNN
+SRR5388335.1 1 length=51
###################################################
@SRR5388335.2 2 length=51
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
+SRR5388335.2 2 length=51
###################################################
@SRR5388335.3 3 length=51
CCTATGTGAAGCTCTTCTTTGGTGGCCAGGAGCTNNGGACGNGCACCGTGT
+SRR5388335.3 3 length=51
1==::BAD?FADHBFGFG+<4AA1?EHCF=)?B3##10?BF#00?@(<FCG
@SRR5388335.4 4 length=51
GCCTGGTGTCTGTCAGGAAGAGCAGGTTGTTGGCCGCGCTGGACGAAGAGC
+SRR5388335.4 4 length=51
@CCFFFADFFDHFHIGG>>F3FFCGG;FA@?BFHIIIGGHBHBGGE/A';?
@SRR5388335.5 5 length=51
GGTCATGATGCAGAAGCTACTCAAATGCAGTCGGCTTGTCCTGGCTCTTGC
+SRR5388335.5 5 length=51
CCBFFFFFHHHHHJJJJJJJJJJJJIJJJIIJJJJJJGFGIECGGGGII<B

**Comment by mourisl** [comment]
Which version of TRUST4 did you use?

**Comment by joyshen123** [comment]
I installed trust4 1.0.11 from conda .

> Which version of TRUST4 did you use?

**Comment by mourisl** [comment]
This might be a bug in TRUST4. Could you please share the "TRUST_SRR5388335_1_final.out " file for me to debug? Thank you.

**Comment by joyshen123** [comment]
Thanks a lot !
[TRUST_SRR5388335_1_final.txt](https://github.com/liulab-dfci/TRUST4/files/12189764/TRUST_SRR5388335_1_final.txt)

**Comment by mourisl** [comment]
Thank you for sharing the file. I think I've found and fixed the bug. Could you please try to install the TRUST4 from github? You can rerun it on your original path with the option "--stage 2" to avoid the time-consuming assembly steps. If this fixes your issue, I will draft a new release. Thank you.

**Comment by joyshen123** [comment]
Thanks again for all your help! I ran trust4 from github and it successfully worked. You really helped me a great favor.
