### ISSUE TITLE
Does TRUST4 work with BCR-seq or TCR-seq data?

### ISSUE THREAD

**Issue by sdzxzh** [liulab-dfci/TRUST4#207]
Hello,

Do you think TRUST4 can work with IR seq data? Perhaps, it could provide more information than MiXCR?

Thanks in advance

**Comment by mourisl** [comment]
Yes, you can either use the "--repseq" option for IR seq, or use "--barcodeLevel molecule"+"--readFormat" if it is a UMI-based IR-seq.

**Comment by sdzxzh** [comment]
> 

Thank you!

**Comment by sdzxzh** [comment]
> Yes, you can either use the "--repseq" option for IR seq, or use "--barcodeLevel molecule"+"--readFormat" if it is a UMI-based IR-seq.

Thank you!
