### ISSUE TITLE
Use TRUST4 on selected RNAseq data

### ISSUE THREAD

**Issue by popucui** [liulab-dfci/TRUST4#211]
Hello,

I understand that TRUST4 is specifically designed to handle unselected RNAseq data. I have attempted to use TRUST4 to assemble the complete BCR sequence from target enriched BCRseq  PE300 data, and it takes approximately 10 hours to process 16 million reads. I would like to know if you have any recommendations for optimizing the parameters of TRUST4 to improve its speed, or if I should consider using an alternative method for this purpose. Thank you for your assistance.

**Comment by mourisl** [comment]
For targeted amplified data, you may add the option "--repseq" to accelerate the program. Is your data also UMI-based?

**Comment by JackCuihfb** [comment]
Thanks a lot for providing the information. Currently, our library does not incorporate UMI, but we do have a discussion about it's potential inclusion for single cell data.

**Comment by mourisl** [comment]
If your data is UMI-based bulk BCR-seq, you can use the option "--barcode UMI_file.fa --barcodeLevel molecule".

**Comment by popucui** [comment]
Thanks a lot, I'll close this issue.
