### ISSUE TITLE
Sample normalization and BCR SHM calculation

### ISSUE THREAD

**Issue by cloudyrainy-zh** [liulab-dfci/TRUST4#213]
Thank you for developing this tool!
I see that you mentioned multi-sample standardization in the previous issues, should I standardize the clone number of each clonotype before comparing the CPK and other metrics in different samples and groups, or is there a better way to do it? 
Do you have any recommended standardized methods based on each sample's reads?
In addition to the questions above, I looked up the BCR SHM calculation but didn't have a good clue.

**Comment by mourisl** [comment]
CPK and clonality are already normalized, so probably you don't need more standardization. For entropy, though it is affected by library size and infiltration level, it contains information on how many different clonotypes in the data set. Therefore, I think you can leave the values as they are, and check multiple metrics. 

For SHM, I usually just check the V gene alignment identity, which I think is more straightforward.

**Comment by cloudyrainy-zh** [comment]
First of all, thank you very much for your prompt reply.
What about copy numbers? should we compare copy numbers for each sample after standardization? Alternatively, first determine whether there is a significant correlation between the copy numbers obtained from trust4 and the number of reads.

For the second question, the parameter v_identity in the output trust_airr.tsv could represent SHM for each assemble?
Can the SHM values of different BCR chains be calculated using the average value of  v_identity?
If not, could you please tell me the method for calculating the SHM of different BCR chains for each sample?

**Comment by mourisl** [comment]
1. If you are comparing the same clonotype across different samples, I would normalize the copy number, i.e. the fraction of clonotype.
2. I usually do a weighted average (weight by its copy number). Furthermore, I will only consider the full-length assemblies to avoid some assembly artifacts that may spuriously increase the overall SHM.

**Comment by cloudyrainy-zh** [comment]
Got it, thank you very much, it helped me a lot.
