### ISSUE TITLE
Question about outputs

### ISSUE THREAD

**Issue by ejohnson643** [liulab-dfci/TRUST4#226]
Is there a difference between the  `_raw.out` and `_final.out` files? They appear to be identical for me. Thanks!

**Comment by mourisl** [comment]
_raw.out is the contig before scaffolding using the mate pair information. The _final.out is the scaffolds by joining contigs guided by paired-end reads. In single-end data, these two files will be the same.

**Comment by ejohnson643** [comment]
Perfect! Thank you!
