### ISSUE TITLE
Feature request: add an optional parameter to specify the output directory

### ISSUE THREAD

**Issue by whitehilltea** [liulab-dfci/TRUST4#23]
Hi, developer,

Could you please add an optional parameter in the Trust4 command line, if this parameter is not very hard to add in your code? The parameter can allow users to specify the output directory.

I want this feature because the default directory that the Trust4 writes the output files into is the current working directory. Thereby, each time I have to make a new directory and `cd` to that directory, so that the Trust4 program files are not messed up with the output files. This operation makes my commands have a lot of hierarchical structure for different folders and files, as are seen in my previous submitted issues.

Thanks a lot.

**Comment by mourisl** [comment]
The option "-o" can include the path. However, you need to create that directory first.

**Comment by whitehilltea** [comment]
Hi, Li,

Thanks for point out the usage of -o that I did not know previously. Yes. `-o ${output_directory}/${output_sample_prefix}` works very well, after I create that output directory first. Automatic creation of the output directory will be great. Thanks.

A further thinking: personally, I think letting users to concatenate the `${output_directory}/${output_sample_prefix}` is not very elegant. If there are two separate parameters, one for output directory, and one for output sample prefix, it should be more straightforward and need less string manipulation at the user's side. After all, output directory and output file prefix are two different things. In different situations, the user might only want to consider one parameter whereas ignore the other parameter. For example, when I run trust4 in a wdl pipeline using docker image, outputting to the current working directory is perfect, and I am only interested in the output file prefix, because docker and wdl has its mechanism to transfer the output files out of the docker container to an external directory designated by wdl options. By comparison, for example, when I run the trust4 directly on the Linux system, I hope to set up the output directory as well as the output file prefix.

I apologize if my further thinking seems overly picky to you. Anyway, thanks a lot for your contribution to the TCR research community.

Best Wishes.

**Comment by mourisl** [comment]
I've added the option "--od" so you can specify the output directory. This will also create the directory automatically. 

As you might notice when checking the updates, we released the source code and you can compile TRUST4 on your system now.

Thanks,
Li

**Comment by whitehilltea** [comment]
Thanks a lot for your work.
