### ISSUE TITLE
sample1_toassemble_bc.fa failed: 9 at /usr/local/bin/run-trust4 line 54

### ISSUE THREAD

**Issue by RaghadShu** [liulab-dfci/TRUST4#231]
Hello,
I have 10X 3' scRNA-seq data, and I have been running TRUST4 on each sample using this command in docker:
`run-trust4 -b .sample1/outs/possorted_genome_bam.bam --barcode CB -t 8 -f ./TRUST4/hg38_bcrtcr.fa --ref ./TRUST4/human_IMGT+C.fa -o sample1 --od ./TRUST4/sample1_wbarcode`

It worked for some samples, but others I get this error:
`system /usr/local/bin/trust4  -t 8 -f ./TRUST4/hg38_bcrtcr.fa -o ./TRUST4/sample1_wbarcode/sample1 -u ./TRUST4/sample1_wbarcode/sample1_toassemble.fq --barcode ./TRUST4/MGUS1_wbarcode/sample1_toassemble_bc.fa failed: 9 at /usr/local/bin/run-trust4 line 54.`

I'm not sure what "failed: 9 at /usr/local/bin/run-trust4 line 54" stands for.

Looking forward to your advice,
Raghad

**Comment by mourisl** [comment]
Could you please show me the full error message? It is strange that the sample1_toassemble.fq and sample_toassemble_bc.fa are in two different folders, which I guess you modified the sample id when posting the issue on github. Could you please also show me the first few lines of toassemble.fq and toassemble_bc.fa files? Thank you.

**Comment by RaghadShu** [comment]
Hi,
You are correct, they are in the same folder but don't seem like it because I mis-edited the paths for the post.

This is the error line: 
`[Tue Oct 24 11:11:21 2023] Read in and count kmers for 122700000 reads.
system /usr/local/bin/trust4  -t 8 -f ./TRUST4/hg38_bcrtcr.fa -o ./TRUST4/MGUS1_wbarcode/MGUS1 -u ./TRUST4/MGUS1_wbarcode/MGUS1_toassemble.fq --barcode ./TRUST4/MGUS1_wbarcode/MGUS1_toassemble_bc.fa failed: 9 at /usr/local/bin/run-trust4 line 54.
`

This is the first 20 lines of toassemble.fq:
`head -n 20 MGUS1_toassemble.fq
@VH00461:29:AAANNNVHV:2:2213:31770:27447
GTAAAACTCTAGAAAATCTGCAAAAATCATGCAAAGAAAATCATGTAAAAATCATGATCTTTACTTAGGCACTTACAGGTGAAATGACGA
+
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
@VH00461:29:AAANNNVHV:1:2206:40253:48763
CAGGCTGGAGTGCAGTGGCGTGATCTCGGCTCACTGCAACCTCGGCCTGGGCAACAGAGGGAGACTCCGTCTCGAAAAAAAAAAAAAAAA
+
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
@VH00461:29:AAANNNVHV:2:2614:75284:20784
GGCTGAGGCGGGTGGATCACCAGAGGTCAGGAGTTTGAGACCAGCCTGACCAGTATGATGAAACCCCATCTCTACTAAAAATACAAAAAT
+
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCC
@VH00461:29:AAANNNVHV:2:1501:52353:1833
CTTCCCAAAGTGCTGGGGCAAGCGGATCACGAGGTCAAGTGTTTGAGACCAGCCTGGCCAATATGGTGAAACCCCATCTCTACTAAAAAA
+
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCC
@VH00461:29:AAANNNVHV:1:1502:23912:50562
AAGCAGTGGTATCAACGCAGAGTACATGGGGTACTGTCACTCTGTTGACAGTAATAAGTTGCAAAATCTTCAGGCTGCAGGCTGCGGATG
+
C;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC`

and the first 20 lines of toassemble_bc.fq:
`head -n 20 MGUS1_toassemble_bc.fa 
>VH00461:29:AAANNNVHV:2:2213:31770:27447
CTCGCTCCATATTGAC-1
>VH00461:29:AAANNNVHV:1:2206:40253:48763
GAGGCAAGTCCTTTAA-1
>VH00461:29:AAANNNVHV:2:2614:75284:20784
TGGTCAGTCCCTCTAA-1
>VH00461:29:AAANNNVHV:2:1501:52353:1833
GTCCGTAAGTCGCAAT-1
>VH00461:29:AAANNNVHV:1:1502:23912:50562
TGGCCAATCATCCTAT-1
>VH00461:29:AAANNNVHV:1:2602:69812:40794
CTCACACTCATTAGCA-1
>VH00461:29:AAANNNVHV:1:2602:74167:39279
CTCACACTCATTAGCA-1
>VH00461:29:AAANNNVHV:1:2602:69982:41645
missing_barcode
>VH00461:29:AAANNNVHV:1:1305:70626:21693
GCTATAGGTGGTTATG-1
>VH00461:29:AAANNNVHV:1:1306:25881:7588
TGAGGTGCAATTAGCT-1`


Best,
Raghad

**Comment by mourisl** [comment]
It seems you have a massive number of candidate reads for this sample, at least 122,700,000. It would take a lot of memory to store the reads and k-mer count, so I guess the system killed TRUST4 for the memory constraints on your system. It is strange to have so many candidate reads from TCR region, and I tried to to use fastq-extractor on the first reads and neither of them should be the candidate read. Could you please show me your full command of running TRUST4 and maybe use "samtools view" and grep to show the alignment information for the first two reads from the toassemble file? Thank you.

**Comment by RaghadShu** [comment]
Hi again,
Sorry for the late reply but I think I figured it out: I had the memory limit for the docker set for 50G and apparently that was not enough. I raised the memory to 150G and it is working smoothly now. Thank you for your cooperation!!!

**Comment by mourisl** [comment]
It's still strange that you got this amount of the candidate reads. Could you please grep VH00461:29:AAANNNVHV:2:2213:31770:27447 in your BAM file to see where it is mapped to? Thank you.
