### ISSUE TITLE
double free or corruption (!prev)

### ISSUE THREAD

**Issue by ywigelman** [liulab-dfci/TRUST4#24]
first, thank you so much for TRUST4 - it's a great tool  

I've experienced a similar issue. 
I'm trying to run TRUST4 over 124 RepSeq, RNA, samples starting from fastq files (pair-end). 
the run of most samples was successful however it fails in others during the annotation step:

(python3.6) yoav@zelda:~$ /home/zel/yoav/TRUST4/annotator -f /home/zel/yoav/TRUST4/mouse/mouse_IMGT+C.fa -a /home/zel/yoav/GBM_data/TCR_seq/TRUST4_all/7_final.out -t 1 -o /home/zel/yoav/GBM_data/TCR_seq/TRUST4_all/7  -r /home/zel/yoav/GBM_data/TCR_seq/TRUST4_all/7_assembled_reads.fa > /home/zel/yoav/GBM_data/TCR_seq/TRUST4_all/7_annot.fa
[Sun Aug 23 12:59:25 2020] Start to annotate assemblies.
[Sun Aug 23 13:12:14 2020] Start to realign reads for CDR3 analysis.
[Sun Aug 23 13:17:00 2020] Realigned 100000 reads.
[Sun Aug 23 13:20:44 2020] Realigned 200000 reads.
[Sun Aug 23 13:24:16 2020] Realigned 300000 reads.
[Sun Aug 23 13:27:29 2020] Realigned 400000 reads.
[Sun Aug 23 13:34:11 2020] Realigned 500000 reads.
[Sun Aug 23 13:35:15 2020] Compute CDR3 abundance.
double free or corruption (!prev)
Aborted (core dumped)

here's a link to the final file in case it helps  [7_final.out](https://drive.google.com/file/d/1_ThygZOOw5WN29aiN92Hmjlu4AINIAzs/view?usp=sharing)

thanks in advance for your assistance, 

Yoav

_Originally posted by @ywigelman in https://github.com/liulab-dfci/TRUST4/issues/22#issuecomment-678776054_

**Comment by mourisl** [comment]
Thank you for sharing the file and the commands! I've found and fixed the bug based on this information. Can you pull the github repo and test it again? 

The bug is that some mouse IMGT sequences (e.g., TRAV7-5*03) do not have CDR1 and CDR2, so TRUST4 tried to obtain the information outside of the reference and caused memory error.

Thank you!

**Comment by ywigelman** [comment]
Dear Li

thank you so much 
it works great now :)

best wishes

Yoav
