### ISSUE TITLE
Segmentation fault in annotation stage

### ISSUE THREAD

**Issue by Leo-Guan-git** [liulab-dfci/TRUST4#242]
Hello,

I'm using TRUST4 on some bulk RNA-seq data, multiple samples are processed, most of which are succeed. But two of these samples are failed in annotation stage, all I can see from the log file about the reason for failed is:
"""
[Tue Jan  2 17:06:13 2024] Start to annotate assemblies.
sh: line 1:  2189 Segmentation fault      (core dumped) /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/TRUST4-v1.0.13/TRUST4/annotator -f /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/01.database/imgt/Homo_sapien/Homo_sapien.IMGT+C.fa -a /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X_final.out -t 10 -o /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X -r /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X_assembled_reads.fa --airrAlignment > /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X_annot.fa
system /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/TRUST4-v1.0.13/TRUST4/annotator -f /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/01.database/imgt/Homo_sapien/Homo_sapien.IMGT+C.fa -a /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X_final.out -t 10 -o /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X  -r /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X_assembled_reads.fa --airrAlignment > /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/guanxiangyu/RNA-seq/Cyclone/fuyunyun/20231210_v3/Jurkat-2w-TRBC-1X/3.Immune/TRUST4/Bulk/Jurkat-2w-TRBC-1X_annot.fa failed: 35584 at /hwfssz1/ST_SUPERCELLS/P21Z10200N0125/zhanghaibo/software/TRUST4-v1.0.13/TRUST4/run-trust4_v2 line 55.
"""

I tried the version of 1.0.13, 1.0.12 and 1.0.11, but failed reports are all the same. When I run the annotator scirpt along, there are only 'Segmentation fault' reported, the Segmentation fault  in Issues (#220 #116 #132 #3 #22) can not solve my problem either.
So, could you please help me to figure out the reason of the failed? the Homo_sapien.IMGT+C.fa, Jurkat-2w-TRBC-1
X_final.out and Jurkat-2w-TRBC-1X_assembled_reads.fa files are listed [here](https://drive.google.com/drive/folders/1kH5Ht8vAd1wxuTWjfP3sHlo2r_DKdwJ4?usp=sharing), Thanks a lot!

**Comment by mourisl** [comment]
Thank you for sharing the data! I will look into this issue.

**Comment by mourisl** [comment]
I think I've found the issue and pushed a fix to the github repo. It seems from a very long contig that starts from V gene, into maybe genomic region, then to J and C gene, or this is a misassembled contig. Could you please pull the code from github and give it a try? You can run TRUST4 with the additional option --stage 2 to save assembly time. Thank you!

**Comment by Leo-Guan-git** [comment]
Thank you so much for your answer.

the error are solved after pull the newest code from github, thanks again!
