### ISSUE TITLE
Description of columns in trust4_report.tsv, specifically column C 

### ISSUE THREAD

**Issue by divya-venkat** [liulab-dfci/TRUST4#245]
I cannot find any description for the columns in trust4_report.tsv. Need to clarify whether the C column gives the constant region gene or chain type. 
Also, what does it mean when the value of C is blank or “.” ? 

Appreciate any help, thanks!

**Comment by mourisl** [comment]
The description of this format is at: https://github.com/liulab-dfci/TRUST4?tab=readme-ov-file#inputoutput . In particular, for report.tsv file:
```
read_count	frequency(proportion of read_count)	CDR3_dna	CDR3_amino_acids	V	D	J	C	consensus_id consensus_id_full_length
```
"." means that TRUST4 could not obtain the information from the contig.

**Comment by divya-venkat** [comment]
That clears it up. Thanks for the prompt reply!
