### ISSUE TITLE
Question about paired-end 10x genomics data

### ISSUE THREAD

**Issue by Yunuuuu** [liulab-dfci/TRUST4#250]
I have 10x 3' sequencing paired-end fastq files, both read files have 150bp (Just like this https://www.biostars.org/p/9529864/), the first read file contains the barcode (16bp) and UMI (12bp) sequence, other sequence should be omitted. Though the sequencing is paired-end, but we only have one fastq file with valid sequence.  I'm confused about the running command 
 -  `-u read2 --barcode read1 --UMI read1 --readFormat bc:0:15,um:16:27`
 -  `-1 read1 -2 read2 --barcode read1 --UMI read1 --readFormat bc:0:15,um:16:27,r1:28:-1`

A snopshot of my fastq files
![image](https://github.com/liulab-dfci/TRUST4/assets/19575010/b0abcb5d-5640-4bcb-bcb7-4591510d113e)

**Comment by mourisl** [comment]
In your case, since the other part in read1 is not useful, you shall use the first command "-u read2 --barcode read1 --UMI read1 --readFormat bc:0:15,um:16:27".

**Comment by Yunuuuu** [comment]
Thank you so much for your reply.
