### ISSUE TITLE
Permission of commercial use

### ISSUE THREAD

**Issue by jiey6596** [liulab-dfci/TRUST4#257]
Dear Prof. Li,

I hope you are doing well. I recently came across your TRUST4 tool on GitHub, and I am very interested in its functionality for downstream analysis in our ongoing development of spatial immune profiling products for commercial use.

I would like to inquire about the licensing and terms of use for TRUST4. Specifically, I would like to understand if it is permissible to use TRUST4 for commercial purposes (TRUST4 will be as one part in our analysis workflow to decover the TCR/BCR genes). If so, are there any specific requirements or restrictions that we should be aware of?

We greatly value the work you have put into developing TRUST4, and we believe that it could be a valuable asset for our research and development. Any information you can provide regarding the usage and permissions for commercial use would be greatly appreciated.

Thank you for your time and consideration. I look forward to hearing from you soon.

Best regards, 
Jieshao

**Comment by mourisl** [comment]
Thank you for considering TRUST4 and this inquiry. Will your workflow be open-sourced? I think that's the main constraint from the GPL license. I'm fine with commercial use, and am thinking about changing the license to MIT recently.

**Comment by jiey6596** [comment]
Dear Prof. Li, 

thank you for your prompt response. 

Unfortunately, my workflow is currently not allowed to be made open-source, which is the main constraint at the moment I think. It would be so nice that you are changing the license to MIT. Can I know if there is a more definite timeline for when you plan to switch the license to MIT. 

Best regards,
Jieshao

**Comment by mourisl** [comment]
I will draft a new version in a few weeks/days to reflect some bug fixings. If no other issues arise, I can change the license to MIT at that time.

**Comment by jiey6596** [comment]
That would be so great. Thank you so much for your effort. 

Best regards,
Jieshao

**Comment by jiey6596** [comment]
Dear Prof. Li, 

Thank you for informing me about the release of TRUST4 v1.1.0 with the updated MIT license. It's great to see that TRUST4 is continuously evolving and improving. I will definitely test the new version of TRUST4 and provide feedback if I encounter any issues. 

Best regards,
Jieshao
