### ISSUE TITLE
Separate TCR & BCR results

### ISSUE THREAD

**Issue by bioinformatics-takara** [liulab-dfci/TRUST4#26]
Hi Is there anyway to specify mapping type to only TCR or only BCR?
Or map both but split TCR and BCR results at a later stage?
Thanks!

**Comment by mourisl** [comment]
Yes, you can use command like "awk '$5~"IG" || $7~"IG" || $8~"IG"' XXXX_report.tsv > bcr_report.tsv" and "awk '$5~"TR" || $7~"TR" || $8~"TR"' XXX_report.tsv > tcr_report.tsv" to split the results from the report. Does this help?

**Comment by bioinformatics-takara** [comment]
Thanks, this is help!
