### ISSUE TITLE
failed: 9 at ./run-trust4 line 55. 

### ISSUE THREAD

**Issue by MinhuaSu** [liulab-dfci/TRUST4#264]
Hi there,

I am attempting to retrieve BCR from some CCLE cell lines (bulk RNA-seq). While it was successful for some cell lines, I encountered a failure with the following line:

Command used:

./run-trust4 -b ../rnasq_hg38/kms27/CDS-5xsctH.Aligned.sortedByCoord.out.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa --abnormalUnmapFlag -t 8 --od kms27/

error message:
system /PATH/TRUST4/trust4  -t 8 -f hg38_bcrtcr.fa -o kms27//TRUST_CDS-5xsctH -1 kms27//TRUST_CDS-5xsctH_toassemble_1.fq -2 kms27//TRUST_CDS-5xsctH_toassemble_2.fq failed: 9 at ./run-trust4 line 55.

Thank you

**Comment by mourisl** [comment]
Which version of TRUST4 are you using? Is there any other message print on the screen before the failed: 9 message?

**Comment by MinhuaSu** [comment]
Hi, i am using v1.0.13-r474

Message before 

 [Tue Apr 23 01:21:56 2024] TRUST4 begins.
[Tue Apr 23 01:21:56 2024] SYSTEM CALL: /PATH/TRUST4/bam-extractor -b ../rnasq_hg38/ejm/CDS-T8ywaR.Aligned.sortedByCoord.out.bam -t 8 -f hg38_bcrtcr.fa -o ejm/TRUST_CDS-T8ywaR_toassemble  -u
[Tue Apr 23 01:21:56 2024] Start to extract candidate reads from bam file.
[Tue Apr 23 01:38:13 2024] Finish obtaining the candidate read ids.
[Tue Apr 23 01:50:54 2024] Finish extracting reads.
[Tue Apr 23 01:51:03 2024] SYSTEM CALL: /PATH/TRUST4/trust4  -t 8 -f hg38_bcrtcr.fa -o ejm/TRUST_CDS-T8ywaR -1 ejm/TRUST_CDS-T8ywaR_toassemble_1.fq -2 ejm/TRUST_CDS-T8ywaR_toassemble_2.fq
[Tue Apr 23 01:51:05 2024] Read in and count kmers for 100000 reads.
[Tue Apr 23 01:51:06 2024] Read in and count kmers for 200000 reads.
[Tue Apr 23 01:51:07 2024] Read in and count kmers for 300000 reads.
[Tue Apr 23 01:51:09 2024] Read in and count kmers for 400000 reads.
[Tue Apr 23 01:51:10 2024] Read in and count kmers for 500000 reads.
[Tue Apr 23 01:51:11 2024] Read in and count kmers for 600000 reads.
[Tue Apr 23 01:51:13 2024] Read in and count kmers for 700000 reads.
[Tue Apr 23 01:51:14 2024] Read in and count kmers for 800000 reads.
[Tue Apr 23 01:51:16 2024] Read in and count kmers for 900000 reads.
[Tue Apr 23 01:51:17 2024] Read in and count kmers for 1000000 reads.
[Tue Apr 23 01:51:19 2024] Read in and count kmers for 1100000 reads.
[Tue Apr 23 01:51:21 2024] Read in and count kmers for 1200000 reads.
[Tue Apr 23 01:51:22 2024] Read in and count kmers for 1300000 reads.
[Tue Apr 23 01:51:24 2024] Read in and count kmers for 1400000 reads.
[Tue Apr 23 01:51:25 2024] Read in and count kmers for 1500000 reads.
[Tue Apr 23 01:51:27 2024] Read in and count kmers for 1600000 reads.
[Tue Apr 23 01:51:28 2024] Read in and count kmers for 1700000 reads.
[Tue Apr 23 01:51:30 2024] Read in and count kmers for 1800000 reads.
[Tue Apr 23 01:51:32 2024] Read in and count kmers for 1900000 reads.
[Tue Apr 23 01:51:34 2024] Read in and count kmers for 2000000 reads.
[Tue Apr 23 01:51:36 2024] Read in and count kmers for 2100000 reads.
[Tue Apr 23 01:51:38 2024] Read in and count kmers for 2200000 reads.
[Tue Apr 23 01:51:40 2024] Read in and count kmers for 2300000 reads.
[Tue Apr 23 01:51:41 2024] Read in and count kmers for 2400000 reads.
[Tue Apr 23 01:51:43 2024] Read in and count kmers for 2500000 reads.
[Tue Apr 23 01:51:45 2024] Read in and count kmers for 2600000 reads.
[Tue Apr 23 01:51:47 2024] Read in and count kmers for 2700000 reads.
[Tue Apr 23 01:51:49 2024] Read in and count kmers for 2800000 reads.
[Tue Apr 23 01:51:51 2024] Read in and count kmers for 2900000 reads.
[Tue Apr 23 01:51:53 2024] Read in and count kmers for 3000000 reads.
[Tue Apr 23 01:51:54 2024] Read in and count kmers for 3100000 reads.
[Tue Apr 23 01:51:56 2024] Read in and count kmers for 3200000 reads.
[Tue Apr 23 01:51:58 2024] Read in and count kmers for 3300000 reads.
[Tue Apr 23 01:52:00 2024] Read in and count kmers for 3400000 reads.
[Tue Apr 23 01:52:02 2024] Read in and count kmers for 3500000 reads.
[Tue Apr 23 01:52:04 2024] Read in and count kmers for 3600000 reads.
[Tue Apr 23 01:52:06 2024] Read in and count kmers for 3700000 reads.
[Tue Apr 23 01:52:08 2024] Read in and count kmers for 3800000 reads.
[Tue Apr 23 01:52:10 2024] Read in and count kmers for 3900000 reads.
[Tue Apr 23 01:52:12 2024] Read in and count kmers for 4000000 reads.
[Tue Apr 23 01:52:14 2024] Read in and count kmers for 4100000 reads.
[Tue Apr 23 01:52:16 2024] Read in and count kmers for 4200000 reads.
[Tue Apr 23 01:52:18 2024] Read in and count kmers for 4300000 reads.
[Tue Apr 23 01:52:21 2024] Read in and count kmers for 4400000 reads.
[Tue Apr 23 01:52:23 2024] Read in and count kmers for 4500000 reads.
[Tue Apr 23 01:52:25 2024] Read in and count kmers for 4600000 reads.
[Tue Apr 23 01:52:27 2024] Read in and count kmers for 4700000 reads.
[Tue Apr 23 01:52:29 2024] Read in and count kmers for 4800000 reads.
[Tue Apr 23 01:52:31 2024] Read in and count kmers for 4900000 reads.
[Tue Apr 23 01:52:33 2024] Read in and count kmers for 5000000 reads.
[Tue Apr 23 01:52:35 2024] Read in and count kmers for 5100000 reads.
[Tue Apr 23 01:52:37 2024] Read in and count kmers for 5200000 reads.
[Tue Apr 23 01:52:39 2024] Read in and count kmers for 5300000 reads.
[Tue Apr 23 01:52:41 2024] Read in and count kmers for 5400000 reads.
[Tue Apr 23 01:52:44 2024] Read in and count kmers for 5500000 reads.
[Tue Apr 23 01:52:46 2024] Read in and count kmers for 5600000 reads.
[Tue Apr 23 01:52:48 2024] Read in and count kmers for 5700000 reads.
[Tue Apr 23 01:52:50 2024] Read in and count kmers for 5800000 reads.
[Tue Apr 23 01:52:52 2024] Read in and count kmers for 5900000 reads.
[Tue Apr 23 01:52:54 2024] Read in and count kmers for 6000000 reads.
[Tue Apr 23 01:52:56 2024] Read in and count kmers for 6100000 reads.
[Tue Apr 23 01:52:58 2024] Read in and count kmers for 6200000 reads.
[Tue Apr 23 01:53:00 2024] Read in and count kmers for 6300000 reads.
[Tue Apr 23 01:53:03 2024] Read in and count kmers for 6400000 reads.
[Tue Apr 23 01:53:05 2024] Read in and count kmers for 6500000 reads.
[Tue Apr 23 01:53:07 2024] Read in and count kmers for 6600000 reads.
[Tue Apr 23 01:53:09 2024] Read in and count kmers for 6700000 reads.
[Tue Apr 23 01:53:12 2024] Read in and count kmers for 6800000 reads.
[Tue Apr 23 01:53:14 2024] Read in and count kmers for 6900000 reads.
[Tue Apr 23 01:53:16 2024] Read in and count kmers for 7000000 reads.
[Tue Apr 23 01:53:18 2024] Read in and count kmers for 7100000 reads.
[Tue Apr 23 01:53:20 2024] Read in and count kmers for 7200000 reads.
[Tue Apr 23 01:53:23 2024] Read in and count kmers for 7300000 reads.
[Tue Apr 23 01:53:25 2024] Read in and count kmers for 7400000 reads.
[Tue Apr 23 01:53:27 2024] Read in and count kmers for 7500000 reads.
[Tue Apr 23 01:53:29 2024] Read in and count kmers for 7600000 reads.
[Tue Apr 23 01:53:31 2024] Read in and count kmers for 7700000 reads.
[Tue Apr 23 01:53:33 2024] Read in and count kmers for 7800000 reads.
[Tue Apr 23 01:53:35 2024] Read in and count kmers for 7900000 reads.
[Tue Apr 23 01:53:39 2024] Read in and count kmers for 8000000 reads.
[Tue Apr 23 01:53:42 2024] Read in and count kmers for 8100000 reads.
[Tue Apr 23 01:53:43 2024] Read in and count kmers for 8200000 reads.
[Tue Apr 23 01:53:45 2024] Read in and count kmers for 8300000 reads.
[Tue Apr 23 01:53:48 2024] Read in and count kmers for 8400000 reads.
[Tue Apr 23 01:53:50 2024] Read in and count kmers for 8500000 reads.
[Tue Apr 23 01:53:53 2024] Read in and count kmers for 8600000 reads.
system /PATH/TRUST4/trust4  -t 8 -f hg38_bcrtcr.fa -o ejm/TRUST_CDS-T8ywaR -1 ejm/TRUST_CDS-T8ywaR_toassemble_1.fq -2 ejm/TRUST_CDS-T8ywaR_toassemble_2.fq failed: 9 at ./run-trust4 line 55.

**Comment by mourisl** [comment]
It seems there are a lot of reads in your data set. Error signal 9 usually means system kills the process. I think in your case might be out of memory. How much memory do you allocate for the job?

**Comment by MinhuaSu** [comment]
I allocated more memory and it worked. Thank you very much!
