### ISSUE TITLE
something wrong with the barcode_report.tsv

### ISSUE THREAD

**Issue by lishuangshuang0616** [liulab-dfci/TRUST4#267]
Hi, Dr, Li

my tcrbcr_annot.fa
![image](https://github.com/liulab-dfci/TRUST4/assets/49019821/9c423be9-39c4-48e4-9799-28a9e1218cce)

cdr3.out
![image](https://github.com/liulab-dfci/TRUST4/assets/49019821/659d1322-e079-480a-b3c9-ca2ed6bc005f)

but barcode_report.tsv miss the CELL19990_N1_260
![image](https://github.com/liulab-dfci/TRUST4/assets/49019821/50b80c48-6a2c-41ed-aa31-09f69c94108e)

```
perl trust-barcoderep.pl tcrbcr_cdr3.out -a tcrbcr_annot.fa --chainsInBarcode 2 > tcrbcr_barcode_report.tsv
```

perhaps something wrong?

**Comment by mourisl** [comment]
Sorry for the delayed reply. I think the _260 and _589 contigs have the same CDR3nt and V and J genes assignment, so the barcode report just selects _589 as the representative based on that it has more reads than _260.

**Comment by lishuangshuang0616** [comment]
yes， they are same . So in terms of selection, trust4 prefer umi number more than full-length.

**Comment by mourisl** [comment]
Right.
