### ISSUE TITLE
How trust4 exactly defines the complete_vdj?

### ISSUE THREAD

**Issue by yuyuleung** [liulab-dfci/TRUST4#274]
Dear Dr. Li, 

Thank you so much for your effort for updating TRUST4.

I am focusing on the fullVDJ assembly with the trust4 output now, cause my data only contains a limited number of complete_vdj assemblies. I guess my TCR-enriched processes attributes it. Thus I want to look into the assmebly result and figure out which part of them si mostly missing. However, I am not completely clear on how trust4 works to accurately define an assembly that covers the 5' end of the V gene to the 3' end of the J gene. (Cause I am not good at reading Cpp-script.) Luckly, I have found that there is a perl script ([GetFullLengthAssembly.pl](https://github.com/liulab-dfci/TRUST4/blob/master/scripts/GetFullLengthAssembly.pl)), used to filter out the full length assembly from the annot.fa.. Thus, I have also looked into this script. 

As I have understood that there are several cretiera to filter the consensus sequence, which is not fullVDJ:

If following not TRUE, the corresponding seq is fullVDJ:
1. Vgene consensus_end> Jgene consensus_start + 3 ||  Jgene consensus_end> Jgene consensus_start + 6
2. Vgene reference_start >=10 || Vgene consensus_end < CDR3 consensus_start
3. Jgene consensus_start > CDR3 consensus_end || Jgene reference_end < Jgene reference_gene_length - 3
4. Cgene reference_start > 10
5. Seq not include "N"

I am not sure, whether these creteria are same used to define complete_vdj column in the barcode.airr file? If not, can you please explain more detail to me?

Thank you.
Yuyu

**Comment by mourisl** [comment]
Perfect timing for this issue. I just updated the code two days ago. The GetFullLengthAssembly.pl follows the criteria you mentioned, that requires almost full length V, J (missing a few bases in the front and the end), and has the annotation for C gene. I think this script a bit out-dated.

In TRUST4's main program, the complete_vdj does not require C gene information now (updated two days ago, will be in v1.1.2), so the criteria is:
1. Has V, J gene, and CDR3 information.
2. V gene end must be <= the first 3 bp of J gene
3. V gene has to be start from the first base, and the end of the V gene must be in the CDR3 region.
4. J gene has to be end at the last base, and the start of the J gene must be in the CDR3 region. 
5. Sequence does not contain "N".
This update will make the complete_vdj reported by the main program more consistent with the definition of AIRR.

**Comment by yuyuleung** [comment]
Thank you so much for your updated and detailed answer. I think I am getting closer to know what I should check.

I have another question regarding the 4th point, "J gene has to end at the last base." How can I determine whether the consensus sequence covers the last base of the V gene, based on the anno.fa file or other output files obtained from TRUST4?

Thanks again.
Yuyu

**Comment by yuyuleung** [comment]
I think I have found the updated script and mostly understood how you made it. 

 "J gene has to end at the last base":  Jgene-refseqEnd == Jgene-readLen - 1, correct? 

Thanks again.

**Comment by mourisl** [comment]
> "J gene has to end at the last base": Jgene-refseqEnd == Jgene-readLen - 1, correct?

Right. If you want to decide from the annot file, it has the J gene length in the parenthesis and the alignment end position, and it should be length-1 for complete_vdj.

**Comment by ruffyp** [comment]
Dear Dr. Li,

I would like to ask if the definition of productive_vdj and the definition of complete_vdj are different from 10x, which are defined as follows:

**productive**: A productive contig satisfies the following conditions: the contig annotations span the 5' end of the V region to the 3' end of the J region of the chain, a start codon was found in the expected part of the V sequence, an in-frame CDR3 amino acid motif was found, and no stop codons were found in the aligned V-J region.
**Full-length**: A contig is full-length if it matches the initial part of a V gene, continues on, and ultimately matches the terminal part of a J gene.

That is, a contig is productive usually means that it is full-length. However, when I checked the airr.tsv output of the TRUST4, I found that many contigs were productive but the complete_vdj was F.

![image](https://github.com/user-attachments/assets/0ee5035f-8ab8-40af-9b4c-675b1e0c9992)

Another question is, when I do subsequent analysis, such as clonotype analysis, should I select the rows with both productive and complete_vdj marked as T?

**Comment by ruffyp** [comment]
Dear Dr. Li,

I would like to ask if the definition of productive and the definition of complete_vdj in the airr.tsv file are different from 10x, which are defined as follows:

**productive**: A productive contig satisfies the following conditions: the contig annotations span the 5' end of the V region to the 3' end of the J region of the chain, a start codon was found in the expected part of the V sequence, an in-frame CDR3 amino acid motif was found, and no stop codons were found in the aligned V-J region.
**full-length**: A contig is full-length if it matches the initial part of a V gene, continues on, and ultimately matches the terminal part of a J gene.
That is, a contig being productive usually means that it is full-length, which is also the case in the airr file output by Cell Ranger. However, when I checked the airr.tsv file output by TRUST4, I found that many contigs were productive but the complete_vdj was F.
![image](https://github.com/user-attachments/assets/cb290854-fbe1-4312-bf64-5fb81d95f255)


Another question is, when I do subsequent analysis, such as clonotype analysis, should I select the rows with both productive and complete_vdj marked as T?

**Comment by ruffyp** [comment]
Dear Dr. Li,

I would like to ask if the definitions of productive and complete_vdj in the airr.tsv file are different from 10x, which are defined as follows:

**productive**: A productive contig satisfies the following conditions: the contig annotations span the 5' end of the V region to the 3' end of the J region of the chain, a start codon was found in the expected part of the V sequence, an in-frame CDR3 amino acid motif was found, and no stop codons were found in the aligned V-J region.
**full-length**: A contig is full-length if it matches the initial part of a V gene, continues on, and ultimately matches the terminal part of a J gene.

That is, a productive contig typically implies it is full-length, a pattern also observed in Cell Ranger's airr file output. However, when I checked the airr.tsv file output by TRUST4, I found that many contigs were productive but the 'complete_vdj' were marked as 'F'.

![image](https://github.com/user-attachments/assets/7efe72df-f880-493c-ac69-61bd4fc9daa1)


Another question is, when I do subsequent analysis, such as clonotype analysis, should I select the rows with both productive and complete_vdj marked as T?

**Comment by mourisl** [comment]
It is different. TRUST4's productive definition is solely based on CDR3 sequence, as TRUST4 is designed for unamplified data, where the full-length assemblies are opportunistic. Full-length's definition in TRUST4 should be the same as 10x's.

For clonotype analysis, you can just use CDR3aa, so complete_vdj is more or less irrelevant.

Hope this helps.

**Comment by ruffyp** [comment]
I understand, thanks for your explanation.
