### ISSUE TITLE
Read count for all contigs (10X)

### ISSUE THREAD

**Issue by ktpolanski** [liulab-dfci/TRUST4#276]
Hello,

I'm mucking about with the various intermediate files, as sometimes it's desirable to look at variably incomplete contigs. From my understanding, `annot.fa` is a master list of "raw" contigs, which are then filtered to ones with a defined CDR3 for `cdr3.out`, which then get further filtered for `barcode_report.tsv`. From what I gather from chatter in the issues, using the read count is a useful way to filter the output. It would appear that this only appears from the `cdr3.out` stage on.

Is there some way to get this for all entries in `annot.fa`? I performed some local attempts, to little success. A test contig of choice, `AGCTTGACACAACGTT_0`, had 192 reads in `cdr3.out` (and onward). I ran with `--outputReadAssignment`, and found 15497 entries for the contig in `assign.out`. I brought in the UMI information from `assembled_reads.fa`, but still got 493 rather than 192 this way:

```bash
grep "AGCTTGACACAACGTT_0" TRUST_R2_assign.out | cut -f 1 > rnames.txt
grep -f rnames.txt TRUST_R2_assembled_reads.fa | grep "barcode:AGCTTGACACAACGTT" | cut -f 6 -d " " | sort | uniq | wc -l
```

Thanks a lot and sorry for the trouble!

**Comment by mourisl** [comment]
cdr3.out and annot.fa is kind in parallel. The assembled contig from TRUST4 is the consensus, which can encode CDR3 with less abundance that differ very little. This is to accommodate somatic hypermutations in BCRs. annot.fa file is the annotation on the consensus assembly. "cdr3.out" reads out the encoded minor CDR3s and calculate the number of reads overlapping with these cdr3s using EM algorithm as some reads may be compatible with multiple CDR3s from the consensus.

In your case, 192 in "cdr3.out" are the number of reads only overlap with the CDR3 region, and the "assign.out" contains the reads that not overlap with CDR3 region, like just overlap with the V gene or C gene portion. If you want to do some filters, the abundance in the cdr3.out file is more accurate, as V gene may be shared in multiple clonotypes and the read assignment becomes pretty random/less-reliable. Hope this helps.

**Comment by ktpolanski** [comment]
Ah, I see. Thank you for my explanation.

Am I correct in my assumption that `cdr3.out` is a subset of `annot.fa`?

**Comment by ktpolanski** [comment]
Oh wait, I have the technology to check. In summary `cdr3.out` is indeed a subset of `annot.fa`, and seems to be created like I theorised in the OP, i.e. taking the contigs with a defined CDR3.

```bash
grep ">" TRUST_R2_annot.fa | cut -f 1 -d " " | sed "s/>//" > annot.txt
cut -f 1 TRUST_R2_cdr3.out > cdr3.txt
#1113448, same count as cdr3 entries
comm -12 <(sort cdr3.txt) <(sort annot.txt) | wc -l

#2121513, the difference between annot entries and cdr3 entries
grep "CDR3(0-0):0.00=null" TRUST_R2_annot.fa | wc -l
```

If I was desperate for some sort of measure to try to possibly filter stuff at the `annot.fa` level, what would you recommend?

**Comment by mourisl** [comment]
In the header of the annot.fa file, the third number is kind of the average coverage, namely the number_reads*read_length/500.0 . You may consider filter the contig with very shallow average coverage, for example less than 1 or 0.5.

The detailed coverage information is in the final.out file, which contains the number of reads support each of the nucleotide for the contig. Essentially, final.out is the position weight matrix for each contig assembly. I think you can filter those contigs with just one read support, i.e. every base pair has just 1 read.

**Comment by ktpolanski** [comment]
Awesome, thank you very much! So in summary use the CDR3 read count if able, and if not able try these two. Think that's all the info I need, so I'll close this to declutter a bit.
