### ISSUE TITLE
TRUST4 assembly on NCBI SRA data 

### ISSUE THREAD

**Issue by dudzicp** [liulab-dfci/TRUST4#278]
Hello,

I am trying to reconstruct the BCR repertoire from SRA data with accession SRR11669895.

If i understand correctly, authors use 10x 5' library preparation pipeline which means that barcodes and umis are present on read_1.
(--readFormat bc:0:15,um:16:25,r1:26:-1)

Running trust extraction seems to correctly split the input to files: TRUST_toassemble_1.fq  TRUST_toassemble_2.fq  TRUST_toassemble_bc.fa  TRUST_toassemble_umi.fa.

I have a problem with interpretation of assembly results - I would imagine that the reads would get deduplicated by UMIs as they should represent the technical copies of the same biological reads, in yet in the assembly results, I see the following:

```
>SRR11669895.108261823 1 667591 691927 barcode:CATCGGGTCGAATGGG umi:7237
CCTGCCAGGACACAGTTTAGATATGAGGTTCCAGGTTCAGGTTCTGGGGCTCCTTCTGCTCTGGATATCAGGTGCCCAG
>SRR11669895.76117208 1 667591 691923 barcode:CATCGGGTCGAATGGG umi:7237
CCTGCCAGGACACAGTTTAGATATGAGGTTCCAGGTTCAGGTTCTGGGGCTCCTTCTGCTCTGG
>SRR11669895.21359552 1 667591 681584 barcode:CATCGGGTCGAATGGG umi:7237
CCTGCCAGGACACAGTTTAGATATGAGGTTCCA
>SRR11669895.72131682 1 662961 691248 barcode:CATCGGGTCGAATGGG umi:7237
CCTGCCAGGACACAGTTTAGATATGAGGTTCCAGGTTCAGGTTCTGGGGCTCCTTCTGCTCTGGATATCAGGTGCCCAGTGTGATGTCCAGATAAC
>SRR11669895.87964952 1 662961 691248 barcode:CATCGGGTCGAATGGG umi:7237
CCTGCCAGGACACAGTTTAGATATGAGGTTCCAGGTTCAGGTTCTGGGGCTCCTTCTGCTCTGGATATCAGGTGCCCAGTGTGATGTCCAGATAAC
```

Am I missing something? 

Best regards
Paweł

**Comment by mourisl** [comment]
The reads are not deduplicated at this stage. The UMI information is used in the final abundance estimation stage, where each UMI is counted once when estimating the abundance for a clonotype.

**Comment by dudzicp** [comment]
thank you for the answer
