### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by slukowski** [liulab-dfci/TRUST4#28]
Hi
I'm having some trouble installing TRUST4 on my HPC, whereby the `make` step produces an error and then doesn't continue further. I've cloned the git repo as per the installation instructions, and once inside the repo, am simply running `make`. 

Any suggestions? 

Thanks for your help!

```
make

g++ -O3    -c -o main.o main.cpp
In file included from main.cpp:12:
SeqSet.hpp: In member function ‘int SeqSet::AnnotateRead(char*, int, _overlap*, _overlap*, std::vector<_overlap>*)’:
SeqSet.hpp:5765:14: error: expected unqualified-id before ‘=’ token
 5765 |      int far = false ;
      |              ^
SeqSet.hpp:5768:12: error: expected primary-expression before ‘=’ token
 5768 |        far = true ;
      |            ^
SeqSet.hpp:5769:15: error: expected primary-expression before ‘)’ token
 5769 |      if ( far )
      |               ^
make: *** [main.o] Error 1

```

**Comment by slukowski** [comment]
Ok - looks like it was a GCC version problem. Initially I was using GCC v9.3.0 and it was throwing the above error. Reverting to GCC 6.4.0 cleared this up nicely

**Comment by mourisl** [comment]
Thanks for the message! I've changed the variable type so it should work on your default compiler now.
