### ISSUE TITLE
The number of reads used for assembling each contig

### ISSUE THREAD

**Issue by lishuangshuang0616** [liulab-dfci/TRUST4#283]
Hi Dr. Li,

I would like to know where I can find the number of **_reads_** used for assembling each contig. 
In the _**trust_annot.fa**_ file, the _**average_coverage**_ is calculated as the total length of the reads divided by 500. I have run the same command multiple times and obtained inconsistent average_coverage values, although the differences are very small.
The **_assign.out_** file contains the results of the reads being realigned. 
However, I have not been able to find the data that specifies the number of reads used to assemble each contig. 
How can I obtain this information?

**Comment by mourisl** [comment]
The assembly step is quite complex and involve contig rearrangment, fixing, cleaning up, so it is hard to track the original read used to assemble each contig, the average_coverage is probably the closed to the raw assembly information for now. 

You mentioned the average_coverage is changed. Is the contig also different? Can you show me the different average_coverage values? If the difference is very small, it could be just the precision issue of the float number.

**Comment by lishuangshuang0616** [comment]
Yes, there will be some small differences in float number.
