### ISSUE TITLE
Documentation options are not the same as the current version (1.1.2) and are not recognised

### ISSUE THREAD

**Issue by ulyssebaruchel** [liulab-dfci/TRUST4#288]
Hi, when I try to use the software installed through bioconda (build h43eeafb_1), I get this text:

Required:
        -f STRING: fasta file containing the receptor genome sequence
        [Read file]
        -u STRING: path to single-end read file
                or
        -1 STRING -2 STRING: path to paried-end read files
                or
        -b STRING: path to BAM alignment file
Optional:
        -o STRING: prefix of the output file (default: trust)
        -t INT: number of threads (default: 1)
        -c STRING: the path to the kmer count file
        -k INT: the starting k-mer size for indexing contigs (default: 9)
        --minHitLen INT: the minimal hit length for a valid overlap (default: auto)
        --skipMateExtension: skip the step of extension assemblies with mate-pair information
        --trimLevel INT: 0: no trim; 1: trim low quality; 2: trim unmatched (default: 1)
        --barcode STRING: the path to the barcode file (default: not used)
        --UMI STRING: the path to the UMI file (default: not used)
        --keepNoBarcode: assemble the reads with missing barcodes. (default: ignore the reads)
        
Many of the options described in the documentation and in some past issues are not recognised when I try to use them: 
- '--read-format'
- '--ref'
- '--barcodeRange'
- '--umiRange'

I do not know how I can specify my UMI and cell barcode positions on one of my two reads (the other read containing the gene insert) from input FASTQ files. Can you tell me what options I should use, please?
Thank you

**Comment by mourisl** [comment]
This is the "trust4" main executable for the assembly stage. You shall run trust4 through the wrapper "run-trust4". You can use the "--readFormat" option following the readme at: https://github.com/liulab-dfci/TRUST4?tab=readme-ov-file#10x-genomics-data-and-barcode-based-single-cell-data . I

**Comment by ulyssebaruchel** [comment]
Thank you! 
While I am here, can I ask some questions, please? 

1) I have paired-end reads with gene insert on read1 and only cell barcode + UMI on read2 (no transcriptomic information). Should I use the options 
run-trust4 \
-t $SLURM_JOB_CPUS_PER_NODE \
-f $ref_igmt_c_fa \
--ref $ref_igmt_c_fa \
-u $read1 \
--barcodeWhitelist $bc_white\
--barcode $read2  \
--UMI $read2 \
--read-format bc:0:7,um:8:17
--trimLevel 0 \
--od $output_dir
or still use -1 -2?

2) I am also not sure about --ref and -f being the same (IMGT+C.fa) since I am giving FASTQ files as input so it should be good according to the "Build custom V,J,C gene database (files for -f and --ref)" but the example in the "10X Genomics data and barcode-based single-cell data" section of the documentation uses FASTQ files as input AND -f hg38_bcrtcr.fa --ref human_IMGT+C.fa 

3) What are the different file formats supported for the --barcodeWhitelist option, please?

Thank you so much for your help!
