### ISSUE TITLE
Question about paired-end options for read2 with only CB + UMI

### ISSUE THREAD

**Issue by ulyssebaruchel** [liulab-dfci/TRUST4#289]
Hi!

I have paired-end reads with gene insert on read1 and only cell barcode + UMI on read2 (no transcriptomic information). Should I use the options 
run-trust4 \
-t $SLURM_JOB_CPUS_PER_NODE \
-f $ref_igmt_c_fa \
--ref $ref_igmt_c_fa \
-u $read1 \
--barcodeWhitelist $bc_white\
--barcode $read2  \
--UMI $read2 \
--read-format bc:0:7,um:8:17
--trimLevel 0 \
--od $output_dir

or still use -1 -2?

Thank you for your help?

**Comment by mourisl** [comment]
Your command looks fine. "-u" is appropriate for single-end data in your case. Just want to make sure, is your barcode only 8bp, and UMI 10bp?

**Comment by ulyssebaruchel** [comment]
Yes, thank you!
