### ISSUE TITLE
Documentation on -f and --ref for FASTQ input

### ISSUE THREAD

**Issue by ulyssebaruchel** [liulab-dfci/TRUST4#290]
Hi!
I am not sure about --ref and -f being the same (IMGT+C.fa) since I am giving FASTQ files as input so it should be good according to the "Build custom V,J,C gene database (files for -f and --ref)" but the example in the "10X Genomics data and barcode-based single-cell data" section of the documentation uses FASTQ files as input AND -f hg38_bcrtcr.fa --ref human_IMGT+C.fa 

What is the optimal way, please?

Thank you so much for your help!

**Comment by mourisl** [comment]
"-f" contains gene's genomic coordinate information. It should be used when the raw input is BAM file. 

For fastq input, either hg38_bcrtcr.fa and IMGT+C.fa should be fine. The hg38_bcrtcr.fa has longer C gene sequence, so it might capture more VDJ reads during the process. So I tend to use hg38_bcrtcr.fa file for sure. Though in practice, I don't see much difference in the results when using two different files for the -f option.

**Comment by ulyssebaruchel** [comment]
Okay thank you!
