### ISSUE TITLE
What file formats for --barcodeWhitelist

### ISSUE THREAD

**Issue by ulyssebaruchel** [liulab-dfci/TRUST4#291]
Hi! Do you have a list with a quick description for the file formats that can be used for the barcode whitelist, please? (I used a simple .txt file with a cell barcode on each line.)
Thank you very much.

**Comment by mourisl** [comment]
Yes, it is one barcode per line.

**Comment by ulyssebaruchel** [comment]
Ok thank you, just wanted to have this written here for others to find. Was also curious if a FASTA or CSV file was possible.

**Comment by ulyssebaruchel** [comment]
Ok, thank you.
