### ISSUE TITLE
Error: terminate called after throwing an instance of 'std::bad_array_new_length'

### ISSUE THREAD

**Issue by BolinLiuu** [liulab-dfci/TRUST4#294]
Dear Dr. Li, I have encountered some problems while using TRUST4  commands on the server. This error just happened on several specific samples, while other samples run without any issues. Is that related to insufficient memory? I hope to receive your suggestions. Best wishes!

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/3299db6e-85eb-4071-8f8b-d88292b4acfa">

**Comment by mourisl** [comment]
Which version of TRUST4 are you using? If it is the latest version (1.1.2), could you please share the _final.out file with me?

**Comment by BolinLiuu** [comment]
> Which version of TRUST4 are you using? If it is the latest version (1.1.2), could you please share the _final.out file with me?

Yes, I am using version 1.1.2. Since the output results for that sample were deleted, I am sending you the _final.out file from another sample that encountered the same error. Thank you for your response!
[CLLGSS_final.out.zip](https://github.com/user-attachments/files/16313304/CLLGSS_final.out.zip)

**Comment by mourisl** [comment]
Thank you for sharing the file. I think I've found the issue for this file and have pushed a fix to the github repo. Could you please git clone the github version and give it a try?

**Comment by BolinLiuu** [comment]
> Thank you for sharing the file. I think I've found the issue for this file and have pushed a fix to the github repo. Could you please git clone the github version and give it a try?

The new version works well! Thank you very much!

**Comment by yingmingt** [comment]
hello,I encountered the same problem, I used the latest version of trust4.Should I use a different version?

<img width="2359" height="871" alt="Image" src="https://github.com/user-attachments/assets/e56556c0-27d7-4551-a1eb-c07af4fa15f4" />

**Comment by mourisl** [comment]
Oh. I see. It seems you are putting a wrong sequence for the "--ref" option in the run-trust4 command. This file is usually from IMGT's V,J gene references, not the mouse reference genome. You can use the files here: https://github.com/liulab-dfci/TRUST4/tree/master/mouse , with the suggested extra options.
