### ISSUE TITLE
CDR3 sequences length

### ISSUE THREAD

**Issue by lishuangshuang0616** [liulab-dfci/TRUST4#295]
Hi Dr. Li,

When I use Cell Ranger and TRUST4 for analysis, 
I noticed that some CDR3 sequences obtained by TRUST4 are longer than those from Cell Ranger. 
What caused the difference?

```
# trust4
TRA:CAVSSTNTGKLTFGD  TRA:TGTGCAGTGAGTAGCACCAATACAGGCAAATTAACCTTTGGGGAT
TRB:CSSREGLQDTQYF    TRB:TGTAGTTCTAGAGAAGGACTCCAAGACACCCAGTACTTT

# cellranger
TRA:CAVSSTNTGKLTF    TRA:TGTGCAGTGAGTAGCACCAATACAGGCAAATTAACCTTT
TRB:CSSREGLQDTQYF    TRB:TGTAGTTCTAGAGAAGGACTCCAAGACACCCAGTACTTT
```
i have used the latest repo.

**Comment by mourisl** [comment]
Which version of TRUST4 are you using? Could you please send me the corresponding row for TGTGCAGTGAGTAGCACCAATACAGGCAAATTAACCTTTGGGGAT in the AIRR file. Thank you!

**Comment by lishuangshuang0616** [comment]
[airr_select.txt](https://github.com/user-attachments/files/16385329/airr_select.txt)

version 1.1.2

**Comment by mourisl** [comment]
Thank you for sharing the file. I think I've found the issue, and pushed the fix to the github repo. Could you clone the github version and give it a try? This is a pretty serious bug, and if it works on your data set, I will draft a new release soon.

**Comment by lishuangshuang0616** [comment]
Thank you for your quick work. I will try to re-analyze using the latest repo.

**Comment by lishuangshuang0616** [comment]
I checked and found that the result no longer has that last part and is consistent with cellranger.
Another question, for this particular sequence, both cdr1 and cdr2 are identified as null, but cellranger is able to identify them.
something wrong with the annotation?

**Comment by mourisl** [comment]
Thank you! The mouse IMGT TRA sequence has some special gaps, so the common coordinate for CDR1, 2, 3 does not hold. The CDR3 coordinate can still be inferred from the motifs, but the CDR1, 2 is more difficult to recalibrate. I think in CellRanger, they have their own reference gene annotation, so they don't have this issue. I need some time to fix the CDR1,2 issue.

**Comment by lishuangshuang0616** [comment]
Thank you very much for your answer.

**Comment by mourisl** [comment]
I just added the option "--imgtAdditionalGap" in the "special_gap" branch on the github repo. If the CDR1,2 information for the TRA chain is needed, you can add the option "--imgtAdditionalGap TRAV:7,83".  If you get a chance, could you please give this branch a try and let me know whether it works on your data? Thank you!

**Comment by lishuangshuang0616** [comment]
i check some result

```
# trust4
TSGFNG,ACATCTGGGTTCAACGGG,NVLDGL,AATGTTCTGGATGGTTTG,CAVRNAGNMLTF,TGTGCTGTGAGGAATGCAGGCAACATGCTCACCTTT
NSASQS,AACAGTGCTTCTCAGTCT,VYSSGN,GTATACTCCAGTGGTAAT,CVVNPESGSARQLTF,TGTGTGGTGAACCCGGAATCTGGTTCTGCAAGGCAACTGACCTTT
NSASDY,AACAGCGCCTCAGACTAC,IRSNMDK,ATTCGTTCAAATATGGACAAA,CAENSPDNAGNMLTF,TGTGCAGAGAATTCCCCCGATAATGCAGGCAACATGCTCACCTTT
KALYS,AAGGCTTTATATTCT,LLKGGEQ,TTACTGAAGGGTGGAGAACAG,CGTEIRGDAGGTSYGKLTF,TGTGGCACAGAGATAAGAGGGGATGCTGGTGGTACTAGCTATGGAAAGCTGACATTT
SSYSPS,TCTTCTTATTCACCATCT,YTSAATLV,TACACATCAGCGGCCACCCTGGTT,CVVRRGQNFVF,TGTGTTGTGAGGAGGGGTCAGAATTTTGTCTTT
```

```
# 10x
TSGFNG,ACATCTGGGTTCAACGGG,NVLDGL,AATGTTCTGGATGGTTTG,CAVRNAGNMLTF,TGTGCTGTGAGGAATGCAGGCAACATGCTCACCTTT
NSASQS,AACAGTGCTTCTCAGTCT,VYSSG,GTATACTCCAGTGGT,CVVNIGSNFNKFYF,TGTGTGGTGAACATAGGTTCTAACTTCAACAAATTTTACTTT
NSASDY,AACAGCGCCTCAGACTAC,IRSNMDK,ATTCGTTCAAATATGGACAAA,CAENSPDNAGNMLTF,TGTGCAGAGAATTCCCCCGATAATGCAGGCAACATGCTCACCTTT
KALYS,AAGGCTTTATATTCT,LLKGGEQ,TTACTGAAGGGTGGAGAACAG,CGTEIRGDAGGTSYGKLTF,TGTGGCACAGAGATAAGAGGGGATGCTGGTGGTACTAGCTATGGAAAGCTGACATTT
SSYSPS,TCTTCTTATTCACCATCT,YTSAATLV,TACACATCAGCGGCCACCCTGGTT,CVVRRGQNFVF,TGTGTTGTGAGGAGGGGTCAGAATTTTGTCTTT
```
i've captured some of the results for you,. If you need more , i send them use email

**Comment by mourisl** [comment]
Thank you! This looks quite consistent. I've merged the branch to the master, and will make a new release this week.

**Comment by lishuangshuang0616** [comment]
So this parameter can only be added when performing similar analyses like TCR analysis in mouse, and if it's added to other analyses like BCR analysis, it will result in incorrect CDR1/CDR2, right?

**Comment by mourisl** [comment]
The parameter is only effective when TRUST4 detects the IMGT introduces additional gaps, where the canonical CDR3 motif does not match the IMGT coordinate system. When that happens, it will try to use the --imgtAdditionalGap option to adjust CDR1 and CDR2's coordinates. Therefore, adding the option shouldn't affect the analysis for most chains, and only the chain specified in the option like "TRAV:7,83" will be affected.
