### ISSUE TITLE
Condo-based TRUST4 installation fails on Macs with Apple Silicon chips

### ISSUE THREAD

**Issue by mcovington-takara** [liulab-dfci/TRUST4#299]
The TRUST4 conda installation page shows that osx-64 is the only Mac platform that it is available. Would it be possible to get a version for osx-arm64? I can manually install using `--platform osx-64`, but need to be able to install it in an automated platform-agnostic fashion. Thanks!

**Comment by mourisl** [comment]
Thank you for the suggestion. I just released a new version that fixes several bugs introduced in 1.1.2, and has a compromised solution to fully handle the additional gaps in IMGT (thank you for identifying this issue!). After bioconda bump up the version, I'll check how to add the osx-64 to bioconda's config file.

**Comment by mcovington-takara** [comment]
That's great. I'm looking forward to trying out the new `--imgtAdditionalGap` parameter! I see that bioconda has now bumped the version to 1.1.3. Thank you very much.

**Comment by mourisl** [comment]
The osx-arm64 is part of TRUST4 bioconda config now :).

**Comment by mcovington-takara** [comment]
Thank you! I have tested and it works well.
