### ISSUE TITLE
Program freezes when running in parallel

### ISSUE THREAD

**Issue by jbreynier** [liulab-dfci/TRUST4#3]
Hello,

I am able to run the example script without specifying -t, but when I try to run it with -t=4, the program freezes after the read extraction is complete (I allocated 4 cores when running the script, so that shouldn't be an issue). Are there maybe any additional dependencies for running TRUST4 in parallel? I'm running on an HPC cluster, so these are the modules that I have loaded:
gcc/6.2.0 zlib/1.2.11 bzip2/1.0.6 xz/5.2.2 perl/5.24.0 python/3.6.0 samtools/1.9 glibc/2.14
Thanks!

J-B

**Comment by mourisl** [comment]
The executables were compiled under gcc/7.3.0, maybe the pthread library needs that version. Could you please show me the output on the screen from run-trust4?

**Comment by jbreynier** [comment]
This is the stderr when I run with multiple threads:
`[Thu Feb 27 20:47:16 2020] TRUST4 begins.
[Thu Feb 27 20:47:17 2020] SYSTEM CALL: /scratch/jbreynier/programs/TRUST4/TRUST4/bam-extractor -b example/example.bam -t 2 -f hg38_bcrtcr.fa -o ../TRUST4_test/test_toassemble 
[Thu Feb 27 20:47:17 2020] Start to extract candidate reads from bam file.
[Thu Feb 27 20:47:18 2020] Finish obtaining the candidate read ids.
[Thu Feb 27 20:47:18 2020] Finish extracting reads.`

The samtools and glibc programs on the HPC cluster are dependent on gcc/6.2.0 so I'll ask my HPC administrator if that can be modified. I'll give it a try and get back to you.

**Comment by jbreynier** [comment]
Could you please also list all TRUST4 dependencies, in case I need other programs to be installed?

**Comment by mourisl** [comment]
I think there is no other dependency. Could you please check whether ../TRUST4_test/test_toassemble_1.fq, ../TRUST4_test/test_toassemble_2.fq were generated and ended with read id "seq23.2_IGHV3-74*01_IGHJ5*01_TGTGCAAGCATTTGAATATAGCAGCTCGTCATTGTGATAACTCTGGTTCGACCCCTGG-2"

Another way is to run TRUST4 without the wrapper. Just to make sure it is not the operating system issue.
./bam-extractor -b example/example.bam -t 2 -f hg38_bcrtcr.fa -o ../TRUST4_test/test_toassemble
./trust4  -o ../TRUST4_test/test_toassemble -f hg38_bcrtcr.fa -t 2 -1 ../TRUST4_test/test_toassemble_1.fq -2 ../TRUST4_test/test_toassemble_2.fq
./annotator -f human_IMGT+C.fa -a  ../TRUST4_test/test_final.out -r  ../TRUST4_test/test_assembled_reads.fa -t 2 -o  ../TRUST4_test/test >  ../TRUST4_test/test_annot.fa
perl ./trust-simplerep.pl  ../TRUST4_test/test_cdr3.out >  ../TRUST4_test/test_report.tsv 

Thanks.

**Comment by jbreynier** [comment]
Yes, the two fastq files do end with that read id.
I tried running it without the wrapper, but same issue persists (the program freezes after read extraction). I'll contact my HPC administrator to see if the samtools/glibc/perl modules can be installed with gcc/7.3.0.
In the meantime, would it be possible to get the original files, and recompile them myself? It might be possible to recompile with gcc/6.2.0.

**Comment by mourisl** [comment]
I just compiled TRUST4 under gcc/6.2.0. You can download the executables at https://github.com/liulab-dfci/TRUST4/releases and replace the old executables with them. Please let me know whether this works. Thanks.

**Comment by jbreynier** [comment]
I tried running without the wrapper and without indicating the number of threads, and that script also doesn't work. I get the following error output (with the gcc/6.2.0 compiled executables):
`[Mon Mar  2 22:10:09 2020] Start to extract candidate reads from bam file.`
`[Mon Mar  2 22:10:09 2020] Finish obtaining the candidate read ids.`
`[Mon Mar  2 22:10:09 2020] Finish extracting reads.`
`[Mon Mar  2 22:10:10 2020] Found 394 reads.`
`[Mon Mar  2 22:10:10 2020] Finish sorting the reads.`
`[Mon Mar  2 22:10:10 2020] Finish rough annotations.`
`[Mon Mar  2 22:10:10 2020] Assembled 389 reads.`
`[Mon Mar  2 22:10:10 2020] Try to rescue 0 reads for assembly.`
`[Mon Mar  2 22:10:10 2020] Rescued 0 reads.`
`/var/spool/torque/mom_priv/jobs/20780452.cri16sc001.SC: line 82: 175164 Segmentation fault      ./trust4 -o ../TRUST4_test/test_toassemble -f hg38_bcrtcr.fa -1 ../TRUST_test/test_toassemble_1.fq -2 ../TRUST_test/test_toassemble_2.fq`
`Need to use -a to specify the assembly file.` 
`readline() on closed filehandle FP1 at ./trust-simplerep.pl line 295.`
`readline() on closed filehandle FP1 at ./trust-simplerep.pl line 315.`
With the gcc/7.3.0 executables, I get the same exact output without the segmentation fault error. In both cases, the final results are empty. Is there maybe an error in the list of commands you sent me?

The zipped directory doesn't contain the run-trust4 executable compiled with gcc/6.2.0. Could you please add that file so I can see if it works? Thank you!

**Comment by mourisl** [comment]
run-trust4 is just a perl wrapper, so it does not change. I tried this on several systems and they all work fine. Which linux version are you using? 
If you have valgrind on your system, can you run 
"valgrind ./trust4 -o ../TRUST4_test/test -f hg38_bcrtcr.fa -1 ../TRUST_test/test_toassemble_1.fq -2 ../TRUST_test/test_toassemble_2.fq" and share the output with me?

Thanks.

**Comment by jbreynier** [comment]
I figured out why the list of commands without the wrapper weren't producing any results (even with -t 1): in the list of commands, you wrote `./trust4 -o ../TRUST4_test/test_toassemble -f hg38_bcrtcr.fa -t 2 -1 ../TRUST4_test/test_toassemble_1.fq -2 ../TRUST4_test/test_toassemble_2.fq`, but it should have been ` -o ../TRUST4_test/test`.
This is the Linux version on the HPC cluster:
`Linux cri16in001 2.6.32-573.12.1.el6.x86_64 #1 SMP Mon Nov 23 12:55:32 EST 2015 x86_64 x86_64 x86_64 GNU/Linux`

I ran all the individual scripts with valgrind, and this is the error log that I got:
[error_log_valgrind.txt](https://github.com/liulab-dfci/TRUST4/files/4289795/error_log_valgrind.txt)

I also noticed that all of the programs seem to be working and producing the results when run with -t > 1, but they can't seem to be able to exit.

**Comment by jbreynier** [comment]
I think for now I'll stick to the non-parallelized version to run my analysis, but let me know if you have any insight as to why the parallel version might not be working for me. Thanks!

**Comment by mourisl** [comment]
I just uploaded a Singularity container (similar to Docker but does not require root permission) at https://github.com/liulab-dfci/TRUST4/releases and update the instruction in the README. Could you please give it a try if interested?
