### ISSUE TITLE
Dockerfile for TRUST4

### ISSUE THREAD

**Issue by skchronicles** [liulab-dfci/TRUST4#30]
Hello @liulab-dfci,

I hope all is going well, and that you are staying safe in these strange times. I just wanted to preface this by saying thank you for creating TRUST4. It is very useful, and I plan on adding it to one of our pipelines.

 I saw that one of your open issues is for running TRUST4 on RedHat 6 so I created a Dockerfile for running TRUST4 [here](https://github.com/CCBR/Dockers/tree/master/rnaseq/ccbr_trust4).

It includes all the dependencies for TRUST4, Samtools, and HTSlib. I have also added instructions for running TRUST4 with Singularity using your example dataset and instructions for building an image and pushing it to DockerHub (if you have an account). 

Please feel free to use the Dockerfile or add it to your repository.

**Comment by mourisl** [comment]
Thank you very much! I don't have the resource to create the Docker image, and only Singularity successfully worked at that time. Just want to make sure, is the version of TRUST4 in the Dockerfile v0.1.0? I think I can add the link to the release page in the corresponding version. Thank you.

**Comment by skchronicles** [comment]
Hey @mourisl,

To build the image, I cloned your repository yesterday. And as so, it is using the latest version of the master branch on GitHub. I am not sure if the current master branch is ahead of your v1.0.2-beta release, but it is using that at the current moment. If you want, I can re-build the Docker image using the v1.0.2-beta release tarball, and I can create a new tag(s) for the images I pushed to DockerHub so it matches your semantic versioning.

Please let me know what you think.

**Comment by mourisl** [comment]
Yes, I think a matched v1.0.2-beta Docker image would be great! I can then add your github/Dockerhub link to the release page. Thank you for helping TRUST4 more user-friendly!

(Your github repository said it is for TRUST4 (v0.1.0) in the README, so I thought the image was also for that version.)

**Comment by skchronicles** [comment]
@mourisl, sounds good! 

I will let you know when I have finished rebuilding the image, and I have tested it with the provided example dataset. I will also fix the tags on DockerHub too.

**Comment by skchronicles** [comment]
Hello @mourisl,

I just checked on the latest build and ran it against your provided test dataset. Everything looks good.
Here is the [link to the new Dockerfile](https://github.com/CCBR/Dockers/tree/master/rnaseq/ccbr_trust4). I have included a README with instructions on how to build the docker image, push it to DockerHub, pull it from. DockerHub onto local filesystem, and run it with Singularity (for HPC users). Here is the [link to DockerHub](https://hub.docker.com/repository/docker/nciccbr/ccbr_trust4). You will see a new tag that reflects your semantic versioning.

Please let me know if you have any questions, and have an awesome day!

**Comment by mourisl** [comment]
Thank you very much!! This looks great! I've added the links to the release page!
