### ISSUE TITLE
Segmentation fault reported when running the sample on aarch64

### ISSUE THREAD

**Issue by ccz-7** [liulab-dfci/TRUST4#300]
![image](https://github.com/user-attachments/assets/e7efeb66-d33c-42e7-9269-eaa36fa257b1)

**Comment by mourisl** [comment]
Is this installed through conda? Could you please check whether it works by compiling the source code cloned from github?

**Comment by ccz-7** [comment]
> Is this installed through conda? Could you please check whether it works by compiling the source code cloned from github?

Not conda. I compile the source code from github.

**Comment by mourisl** [comment]
Did you get any weird warning message during make?

**Comment by ccz-7** [comment]
> Did you get any weird warning message during make?

Here is the full compile log.
`g++ -O3 -Wall -g    -c -o main.o main.cpp
g++ -o trust4 -I./samtools-0.1.19 -L./samtools-0.1.19 -O3 -Wall -g  main.o -lpthread -lz
g++ -O3 -Wall -g    -c -o BamExtractor.o BamExtractor.cpp
if [ ! -f ./samtools-0.1.19/libbam.a ] ; \
        then \
                        cd samtools-0.1.19 ; make ;\
fi ;
make[1]: Entering directory '/opt/TRUST4/samtools-0.1.19'
make[2]: Entering directory '/opt/TRUST4/samtools-0.1.19'
make[3]: Entering directory '/opt/TRUST4/samtools-0.1.19'
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -DBGZF_CACHE -I. bgzf.c -o bgzf.o
bgzf.c: In function ‘worker_aux’:
bgzf.c:392:9: warning: variable ‘tmp’ set but not used [-Wunused-but-set-variable]
  int i, tmp, stop = 0;
         ^~~
bgzf.c: In function ‘bgzf_close’:
bgzf.c:572:11: warning: variable ‘count’ set but not used [-Wunused-but-set-variable]
  int ret, count, block_length;
           ^~~~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. kstring.c -o kstring.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_aux.c -o bam_aux.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam.c -o bam.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_import.c -o bam_import.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. sam.c -o sam.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_index.c -o bam_index.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_pileup.c -o bam_pileup.o
bam_pileup.c: In function ‘resolve_cigar2’:
bam_pileup.c:75:9: warning: variable ‘is_head’ set but not used [-Wunused-but-set-variable]
  int k, is_head = 0;
         ^~~~~~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_lpileup.c -o bam_lpileup.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_md.c -o bam_md.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. razf.c -o razf.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. faidx.c -o faidx.o
faidx.c: In function ‘fai_load’:
faidx.c:277:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
faidx.c:280:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  if (fp == 0) {
  ^~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bedidx.c -o bedidx.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. knetfile.c -o knetfile.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_sort.c -o bam_sort.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. sam_header.c -o sam_header.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_reheader.c -o bam_reheader.o
bam_reheader.c: In function ‘bam_reheader’:
bam_reheader.c:12:16: warning: variable ‘old’ set but not used [-Wunused-but-set-variable]
  bam_header_t *old;
                ^~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. kprobaln.c -o kprobaln.o
kprobaln.c: In function ‘kpa_glocal’:
kprobaln.c:78:21: warning: variable ‘is_diff’ set but not used [-Wunused-but-set-variable]
  int bw, bw2, i, k, is_diff = 0, is_backward = 1, Pr;
                     ^~~~~~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_cat.c -o bam_cat.o
ar -csru libbam.a bgzf.o kstring.o bam_aux.o bam.o bam_import.o sam.o bam_index.o bam_pileup.o bam_lpileup.o bam_md.o razf.o faidx.o bedidx.o knetfile.o bam_sort.o sam_header.o bam_reheader.o kprobaln.o bam_cat.o
make[3]: Leaving directory '/opt/TRUST4/samtools-0.1.19'
make[3]: Entering directory '/opt/TRUST4/samtools-0.1.19/bcftools'
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. bcf.c -o bcf.o
bcf.c: In function ‘bcf_fmt_core’:
bcf.c:233:9: warning: variable ‘iPL’ set but not used [-Wunused-but-set-variable]
     int iPL = -1;
         ^~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. vcf.c -o vcf.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. bcfutils.c -o bcfutils.o
bcfutils.c: In function ‘bcf_fit_alt’:
bcfutils.c:119:9: warning: variable ‘ipl’ set but not used [-Wunused-but-set-variable]
     int ipl=-1, igt=-1;
         ^~~
bcfutils.c: In function ‘bcf_fix_gt’:
bcfutils.c:254:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
bcfutils.c:256:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  b->fmt[0] = 'G'; b->fmt[1] = 'T'; b->fmt[2] = ':';
  ^
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. prob1.c -o prob1.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. em.c -o em.o
em.c: In function ‘bcf_em1’:
em.c:174:12: warning: variable ‘n2’ set but not used [-Wunused-but-set-variable]
  int i, n, n2;
            ^~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. kfunc.c -o kfunc.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. kmin.c -o kmin.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. index.c -o index.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. fet.c -o fet.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. mut.c -o mut.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. bcf2qcall.c -o bcf2qcall.o
ar -csru libbcf.a bcf.o vcf.o bcfutils.o prob1.o em.o kfunc.o kmin.o index.o fet.o mut.o bcf2qcall.o
make[3]: Leaving directory '/opt/TRUST4/samtools-0.1.19/bcftools'
make[3]: Entering directory '/opt/TRUST4/samtools-0.1.19/misc'
make[3]: Nothing to be done for 'lib'.
make[3]: Leaving directory '/opt/TRUST4/samtools-0.1.19/misc'
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_tview.c -o bam_tview.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_plcmd.c -o bam_plcmd.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. sam_view.c -o sam_view.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_rmdup.c -o bam_rmdup.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_rmdupse.c -o bam_rmdupse.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_mate.c -o bam_mate.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_stat.c -o bam_stat.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_color.c -o bam_color.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bamtk.c -o bamtk.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. kaln.c -o kaln.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam2bcf.c -o bam2bcf.o
bam2bcf.c: In function ‘bcf_call2bcf’:
bam2bcf.c:428:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (bc->read_pos_bias != -1 )
     ^~
bam2bcf.c:430:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  kputc('\0', &s);
  ^~~~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam2bcf_indel.c -o bam2bcf_indel.o
bam2bcf_indel.c: In function ‘bcf_call_add_rg’:
bam2bcf_indel.c:32:4: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
    for (r = p; *r && *r != '\t' && *r != '\n'; ++r); lp = r - p;
    ^~~
bam2bcf_indel.c:32:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
    for (r = p; *r && *r != '\t' && *r != '\n'; ++r); lp = r - p;
                                                      ^~
bam2bcf_indel.c:33:4: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
    for (r = q; *r && *r != '\t' && *r != '\n'; ++r); lq = r - q;
    ^~~
bam2bcf_indel.c:33:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
    for (r = q; *r && *r != '\t' && *r != '\n'; ++r); lq = r - q;
                                                      ^~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. errmod.c -o errmod.o
errmod.c: In function ‘errmod_cal’:
errmod.c:79:8: warning: self-comparison always evaluates to false [-Wtautological-compare]
  if (m > m) return -1;
        ^
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. sample.c -o sample.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. cut_target.c -o cut_target.o
cut_target.c: In function ‘main_cut_target’:
cut_target.c:137:36: warning: variable ‘lastpos’ set but not used [-Wunused-but-set-variable]
  int c, tid, pos, n, lasttid = -1, lastpos = -1, l, max_l;
                                    ^~~~~~~
cut_target.c: In function ‘process_cns.isra.1’:
cut_target.c:96:2: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
  for (i = 0, s = -1; i <= l; ++i) {
  ^~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. phase.c -o phase.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam2depth.c -o bam2depth.o
bam2depth.c: In function ‘main_depth’:
bam2depth.c:85:5: warning: this ‘else’ clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
bam2depth.c:87:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘else’
  data = calloc(n, sizeof(void*)); // data[i] for the i-th input
  ^~~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. padding.c -o padding.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bedcov.c -o bedcov.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bamshuf.c -o bamshuf.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_tview_curses.c -o bam_tview_curses.o
bam_tview_curses.c:287:2: warning: #warning "No curses library is available; tview with curses is disabled." [-Wcpp]
 #warning "No curses library is available; tview with curses is disabled."
  ^~~~~~~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. bam_tview_html.c -o bam_tview_html.o
gcc -g -Wall -O2 -o samtools bam_tview.o bam_plcmd.o sam_view.o bam_rmdup.o bam_rmdupse.o bam_mate.o bam_stat.o bam_color.o bamtk.o kaln.o bam2bcf.o bam2bcf_indel.o errmod.o sample.o cut_target.o phase.o bam2depth.o padding.o bedcov.o bamshuf.o bam_tview_curses.o bam_tview_html.o  libbam.a -Lbcftools -lbcf   -lm -lz -lpthread
make[2]: Leaving directory '/opt/TRUST4/samtools-0.1.19'
make[2]: Entering directory '/opt/TRUST4/samtools-0.1.19/bcftools'
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. call1.c -o call1.o
call1.c: In function ‘write_header’:
call1.c:303:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (!strstr(str.s, "##FORMAT=<ID=GL,"))
     ^~
call1.c:305:2: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  if (!strstr(str.s, "##FORMAT=<ID=DP,"))
  ^~
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I.. -I. main.c -o main.o
gcc -g -Wall -O2 -o bcftools call1.o main.o ../kstring.o ../bgzf.o ../knetfile.o ../bedidx.o -L.  -lbcf -lm -lz -lpthread
make[2]: Leaving directory '/opt/TRUST4/samtools-0.1.19/bcftools'
make[2]: Entering directory '/opt/TRUST4/samtools-0.1.19/misc'
gcc -c -g -Wall -O2 -DMD5SUM_MAIN -o md5sum-lite.o md5.c
md5.c: In function ‘MD5Final’:
md5.c:155:26: warning: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to dereference it? [-Wsizeof-pointer-memaccess]
     memset(ctx, 0, sizeof(ctx));        /* In case it's sensitive */
                          ^
gcc -g -Wall -O2 -o md5sum-lite md5sum-lite.o
gcc -c -g -Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0 -I. md5.c -o md5.o
md5.c: In function ‘MD5Final’:
md5.c:155:26: warning: argument to ‘sizeof’ in ‘memset’ call is the same expression as the destination; did you mean to dereference it? [-Wsizeof-pointer-memaccess]
     memset(ctx, 0, sizeof(ctx));        /* In case it's sensitive */
                          ^
gcc -g -Wall -O2 -c -I.. -o md5fa.o md5fa.c
gcc -g -Wall -O2 -o md5fa md5.o md5fa.o -lz
gcc -g -Wall -O2 -o maq2sam-short maq2sam.c -lz
gcc -g -Wall -O2 -DMAQ_LONGREADS -o maq2sam-long maq2sam.c -lz
gcc -g -Wall -O2 -c -I.. -o ace2sam.o ace2sam.c
ace2sam.c: In function ‘main’:
ace2sam.c:162:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
    if (write_cns) puts(t[4].s); t[4].l = 0;
    ^~
ace2sam.c:162:33: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
    if (write_cns) puts(t[4].s); t[4].l = 0;
                                 ^
gcc -g -Wall -O2 -o ace2sam ace2sam.o -lz
gcc -g -Wall -O2 -c -I.. -o wgsim.o wgsim.c
gcc -g -Wall -O2 -o wgsim wgsim.o -lm -lz
gcc -g -Wall -O2 -c -I.. -o bamcheck.o bamcheck.c
gcc -g -Wall -O2 -o bamcheck bamcheck.o -L.. -lm -lbam -lpthread -lz
make[2]: Leaving directory '/opt/TRUST4/samtools-0.1.19/misc'
make[1]: Leaving directory '/opt/TRUST4/samtools-0.1.19'
g++ -o bam-extractor -I./samtools-0.1.19 -L./samtools-0.1.19 -O3 -Wall -g  BamExtractor.o -lpthread -lz  -lbam
g++ -O3 -Wall -g    -c -o FastqExtractor.o FastqExtractor.cpp
g++ -o fastq-extractor -I./samtools-0.1.19 -L./samtools-0.1.19 -O3 -Wall -g  FastqExtractor.o -lpthread -lz
g++ -O3 -Wall -g    -c -o Annotator.o Annotator.cpp
g++ -o annotator -I./samtools-0.1.19 -L./samtools-0.1.19 -O3 -Wall -g  Annotator.o -lpthread -lz`

**Comment by ccz-7** [comment]
![image](https://github.com/user-attachments/assets/dd58a95e-d3a4-40e9-a7de-5d9affb96576)

**Comment by ccz-7** [comment]
When I use `-fsanitize=address`.
![image](https://github.com/user-attachments/assets/040978a2-8b06-43c6-86f9-ef507986d37f)

**Comment by mourisl** [comment]
Does this error happen on any other platform you have? Would installing from conda resolve this issue?

**Comment by ccz-7** [comment]
Doesn't happen on x86 platform. Installing from conda doesn't resolve this issue.

**Comment by mourisl** [comment]
Could you please try a different GCC version to compile the code? If there is no other GCC version, could you please also try change the -O3 flag in the makefile to -O to do less aggressive compiler optimization?

**Comment by ccz-7** [comment]
> Could you please try a different GCC version to compile the code? If there is no other GCC version, could you please also try change the -O3 flag in the makefile to -O to do less aggressive compiler optimization?

-O flag does not work. I am using GCC 7.3.0.

**Comment by mourisl** [comment]
What is your system? I may need to try that on a virtual machine...

**Comment by ccz-7** [comment]
> What is your system? I may need to try that on a virtual machine...

I am using [CentOS 7](https://vault.centos.org/altarch/7.6.1810/isos/aarch64/).

**Comment by mourisl** [comment]
What's the hardware?

**Comment by ccz-7** [comment]
> What's the hardware?

![image](https://github.com/user-attachments/assets/8e034c08-1ba2-4d91-ac2f-dda2eff8164f)

**Comment by ccz-7** [comment]
@mourisl  Thank you very much for your help! Are there same problem on your virtual machine?

**Comment by mourisl** [comment]
I tried to set up the QEMU on my mac, but it could not display the system interface. Need more time to figure that out...

**Comment by ccz-7** [comment]
> I tried to set up the QEMU on my mac, but it could not display the system interface. Need more time to figure that out...

thank u. I can prepare a remote virtual machine if you need.

**Comment by mourisl** [comment]
That would be nice!

**Comment by mourisl** [comment]
I just tried the VMware, seems to show the system image now. I've installed the Ubuntu there and can reproduce your error!

**Comment by mourisl** [comment]
I think I've found the issue. Could you please checkout the "dev" branch and give it a try, on both of the example data and your real data set? If it works, I will merge it to the master branch. Thank you!

**Comment by ccz-7** [comment]
> I think I've found the issue. Could you please checkout the "dev" branch and give it a try, on both of the example data and your real data set? If it works, I will merge it to the master branch. Thank you!

dev branch works for me. thanks a lot!

**Comment by mourisl** [comment]
Thank you! I have merged the branch into the master. Please feel free to reopen this issue if you find other errors.
