### ISSUE TITLE
failed: 139 at /usr/local/bin/run-trust4 line 58

### ISSUE THREAD

**Issue by Dingchunyuan** [liulab-dfci/TRUST4#304]
Hello,

When running TRUST4, I encountered an error: “failed: 139 at /usr/local/bin/run-trust4 line 58”. I have successfully run this code before, but today it failed with the same code.  I am certain that both the file paths and the working directory are correct.

/usr/local/bin/run-trust4  -f hg38_bcrtcr.fa --ref human_IMGT+C.fa -1 ./Rawdata/Pre-9952-T3/DP8480008034BL_L01_53_1.fq.gz -2 ./Rawdata/Pre-9952-T3/DP8480008034BL_L01_53_2.fq.gz  -o ./Resultdata/TRUST/Pre-9952-T3/Pre-9952-T3

Thanks for your help.

**Comment by mourisl** [comment]
Which TRUST4 version are you using? What's the other output on the screen?

**Comment by Dingchunyuan** [comment]
The version shown in the picture is v1.1.4

![96A0FFC46F05977870D68D9A59A9D4E0](https://github.com/user-attachments/assets/2ec678aa-2632-452a-a8ba-efd8d68a1044)

**Comment by mourisl** [comment]
I see the TRUST4 main program is in the /usr/local/bin folder, is the hg38_bcrtcr.fa file in the current folder?

**Comment by Dingchunyuan** [comment]
yes，both hg38_bcrtcr.fa and human_IMGT+C.fa files are in the current working directory. the current working directory isn’t the /usr/local/bin folder but /data/work/folder

**Comment by mourisl** [comment]
Can you show me the first few lines of the DP..._1.fq.gz and _2.fq.gz files?

**Comment by Dingchunyuan** [comment]
I am certain that the data is correct. Yesterday, I successfully ran it on a Linux system installed on VMware. However, I need to perform the analysis on the company’s system, where I have also successfully run it before.

![image](https://github.com/user-attachments/assets/1c29d460-17e7-4772-a5be-3441e5d3a964)

And I noticed that “TRUST4 depends on pthreads and samtools depends on zlib.” I used ldconfig and rpm -qa to verify the installation of pthreads and zlib. Although ldconfig did not detect zlib, rpm -qa confirmed that it is installed. Both methods successfully detected pthreads.Does this have any impact?

![image](https://github.com/user-attachments/assets/02dbeeb9-3c3d-48a7-9ad4-bccf0c21d6a8)

**Comment by mourisl** [comment]
Do you mean your company's system is not Linux? Can you compile TRUST4 from the source code on the company system?

**Comment by Dingchunyuan** [comment]
It’s Linux, but it’s CentOS. The one on VMware is Ubuntu. 
“compile TRUST4 from the source code”， does it mean using git clone instead of installing with conda?

**Comment by mourisl** [comment]
Yes.

**Comment by Dingchunyuan** [comment]
It worked! Thank you so much.
