### ISSUE TITLE
smartseq3 data pipeline

### ISSUE THREAD

**Issue by lishuangshuang0616** [liulab-dfci/TRUST4#307]
Dr. Li,
Hello, do you have experience in analyzing VDJ on smartseq3 data?

**Comment by mourisl** [comment]
Is there barcode in smartseq3? If so you can use the --readFormat to specify the positions for barcode. If it is like the old smartseq library, you can use the "trust-smartseq.pl" wrapper to process the fastq files of the cells.

**Comment by lishuangshuang0616** [comment]
Smart-seq3 data consists of two types: UMI reads that contain UMIs and internal reads that do not contain UMIs. Since the raw data I am using comes from BAM files processed by zUMIs, I should avoid specifying the UB tag, which would allow me to retrieve internal reads and achieve better coverage, correct? 
For PBMC Smart-seq2 data, if it hasn't undergone VDJ enrichment, is it still easy to assemble full-length and paired sequences?

**Comment by mourisl** [comment]
Do the internal reads have the barcode sequence? The UMI (specified through the --umi option) is mainly for abundance estimation and select the representative clonotypes. It does not affect the assembly itself. You can ignore the UB tag if there is CB field for barcode.

For smart-seq2, I think the coverage is usually good enough for paired VDJ.

**Comment by lishuangshuang0616** [comment]
thanks for your answer
