### ISSUE TITLE
failed: 9 at /home/stereonote/TRUST4/run-trust4 line 58.

### ISSUE THREAD

**Issue by Dingchunyuan** [liulab-dfci/TRUST4#309]
Hello,

When I ran a WDL task, I encountered an error: “failed: 9 at /home/stereonote/TRUST4/run-trust4 line 58.” I tried changing the CPU and memory settings multiple times, but it didn’t resolve the issue. Trust4 was installed using “git clone”. Here is my WDL code and the corresponding error message.

Could you please help me refine this?

Thank you.

![image](https://github.com/user-attachments/assets/c08972ae-cdc6-47b1-be45-dcee263f0f35)

![image](https://github.com/user-attachments/assets/1712bbed-953e-411b-a2fb-be7992cd73bc)
![image](https://github.com/user-attachments/assets/2ba65feb-741b-4a31-b84c-0c084ccd52be)

**Comment by mourisl** [comment]
There might be some bugs. Could you please share the toassemble_1.fq and toassemble_2.fq files with me?
