### ISSUE TITLE
Question about using TRUST4

### ISSUE THREAD

**Issue by wgmao** [liulab-dfci/TRUST4#31]
Thank you for developing this powerful tool. I have tried this tool on my own bulk rna-seq data and I have two questions related to its usage. It will be great if you can share your thoughts.

Q1: I have tried the following two commands on the same fastq.gz files. The only difference is that I used different inputs for the `-f` option.
`run-trust4 -1 *_R1.fastq.gz -2 *_R2.fastq.gz -f human_IMGT+C.fa --ref human_IMGT+C.fa -t 4`
`run-trust4 -1 *_R1.fastq.gz -2 *_R2.fastq.gz -f hg38_bcrtcr.fa --ref human_IMGT+C.fa -t 4`
The output seem quite similar. So is it valid to use `hg38_bcrtcr.fa` and `human_IMGT+C.fa` interchangeably given the input is the read file (fastq.gz)?

Q2: I also tried to run the TRUST4 pipeline on the corresponding bam files after aligning the reads (fastq.gz) to the reference genome. The command is as follows.
`run-trust4 -b *.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa  -t 4`
After checking the `report.tsv`, I found there were much fewer hits compared with the output based on fastq files. Do you have any recommendation on whether I should feed TRUST4 with reads file or bam files? Thank you.

**Comment by mourisl** [comment]
Thank you for the questions.
Q1. These two files are not interchangeably. For fastq input, you can just use human_IMGT+C.fa for -f option as you observed, but hg38_bcrtcr.fa is not ideal for --ref option. 
"--ref" option is special is that TRUST4 interprets the files downloaded from IMGT differently.

Q2. How many bam files do you have in that folder? TRUST4 does not support multiple bam files, and may only use the first one in the "*.bam" list. If you only have one bam file in the path, can you check whether it is aligned to hg19 or hg38?

**Comment by wgmao** [comment]
Thank you for your instant reply. Sorry for the confusion. I used `*` to replace the actual file name. When I run the pipeline, I specified the exact bam file I wanted to use for input. The bam file as aligned to hg38.

**Comment by mourisl** [comment]
Thank you for the clarification. Does the bam file contain the unmapped reads?

**Comment by wgmao** [comment]
No, there is no unmapped reads based on the bam file.

**Comment by mourisl** [comment]
Since CDR3 are not represented on the reference genome, many reads from that region will not be unmapped. So if the bam file does not contain unmapped reads, it will lose a lot of CDR3 information. I guess you can either just use fastq files, or regenerate the bam file containing unmapped reads. Thank you.

**Comment by wgmao** [comment]
I think what your meant was `*will be unmapped*`. Problem solved. Thank you so much.

**Comment by mourisl** [comment]
Whoops, right, they "will be unmapped".
