### ISSUE TITLE
ATACseq

### ISSUE THREAD

**Issue by Henrik-huang** [liulab-dfci/TRUST4#310]
Would it be biologically meaningful to apply TRUST4 for the analysis of ATAC-seq data?
Thanks

**Comment by mourisl** [comment]
I think you can still get some CDR3 results by chance, but overall it might not work well. I have tried TRUST4 on scATAC-seq before, and only about two cells got CDR3 result. 

The result indicate the CDR3 is in a chromatin accessible region, but the result might be too sparse to get biological meaningful conclusions.

**Comment by Henrik-huang** [comment]
Thank you for your response！
