### ISSUE TITLE
not having assembly

### ISSUE THREAD

**Issue by fonseca-dfm** [liulab-dfci/TRUST4#319]
Hello again. Not sure what is happening but I am not having assembly of reads. also I am not sure but the --clean INT option is not working . I am running TRUST4/1.0.14-GCC-11.3.0

------------------------This is my code in a bash script--------------------
VDJ_DIR="/mnt/df/H/Exploratory-unconventional research/RESEARCH/Natural Immunity/10x_genomics/NI_031/vdj_40-1079763967/00_fastq"
GEX_DIR="/mnt/df/H/Exploratory-unconventional research/RESEARCH/Natural Immunity/10x_genomics/NI_031/gex_40-1079691319/00_fastq"
OUTPUT_DIR="/mnt/df/H/Bioinformatics/exp_imm/NI/NI_031"

GENOME_DIR="/nethome/df/Documents/scRNA/10x_refs/trust4/hg38_bcrtcr.fa"
IMGT_REF_DIR="/nethome/df/Documents/scRNA/10x_refs/trust4/human_IMGT+C.fa"
BARCODE_LIST="/nethome/df/Documents/scRNA/10x_refs/barcodes/737K-august-2016.txt"

echo "Checking BARCODE_LIST files in: ${BARCODE_LIST}"
echo "Checking gd-* files in: ${VDJ_DIR}"
indexes_gd=$(ls "${VDJ_DIR}"/gd-* 2>/dev/null | grep -o 'gd-[0-9]' | sort | uniq)

cd "$VDJ_DIR"

for index in $indexes_gd; do
    echo "Processing TRUST4 gd index: ${index}"
    run-trust4 -f "${GENOME_DIR}" \
    --ref "${IMGT_REF_DIR}" \
    -1 "${index}_R1_001.fastq.gz" \
    -2 "${index}_R2_001.fastq.gz" \
    --barcode "${index}_R1_001.fastq.gz" \
    --barcodeWhitelist "${BARCODE_LIST}" \
    --readFormat bc:0:15,r1:16:-1 \
    --clean "INT" \
    --od "${OUTPUT_DIR}/vdj_gd"
    
done

------------------------------this is the output -----------------------------
(base) df@mep02linx62v:~/Documents/natural_immunity_project/NI_031/bin$ bash trust4_vdj_gex2.sh 
Checking BARCODE_LIST files in: /nethome/df/Documents/scRNA/10x_refs/barcodes/737K-august-2016.txt
Checking gd-* files in: /mnt/df/H/Exploratory-unconventional research/RESEARCH/Natural Immunity/10x_genomics/NI_031/vdj_40-1079763967/00_fastq
Processing TRUST4 gd index: gd-1
[Fri Oct 11 18:10:49 2024] TRUST4 begins.
[Fri Oct 11 18:10:49 2024] SYSTEM CALL: /nethome/svc.build/modules/easybuild/software/TRUST4/1.0.14-GCC-11.3.0/bin/fastq-extractor -t 1 -f /nethome/df/Documents/scRNA/10x_refs/trust4/hg38_bcrtcr.fa -o /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001_toassemble  --barcodeWhitelist /nethome/df/Documents/scRNA/10x_refs/barcodes/737K-august-2016.txt --readFormat bc:0:15,r1:16:-1 -1 gd-1_R1_001.fastq.gz -2 gd-1_R2_001.fastq.gz --barcode gd-1_R1_001.fastq.gz
[Fri Oct 11 18:10:49 2024] Start to extract candidate reads from read files.
[Fri Oct 11 20:25:01 2024] Finish extracting reads.
[Fri Oct 11 20:25:01 2024] SYSTEM CALL: /nethome/svc.build/modules/easybuild/software/TRUST4/1.0.14-GCC-11.3.0/bin/trust4  -f /nethome/df/Documents/scRNA/10x_refs/trust4/hg38_bcrtcr.fa -o /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001 -1 /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001_toassemble_1.fq -2 /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001_toassemble_2.fq --barcode /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001_toassemble_bc.fa
[Fri Oct 11 20:25:03 2024] Read in and count kmers for 100000 reads.
[Fri Oct 11 20:25:05 2024] Read in and count kmers for 200000 reads.
[Fri Oct 11 20:25:07 2024] Read in and count kmers for 300000 reads.
[Fri Oct 11 20:25:08 2024] Read in and count kmers for 400000 reads.
[Fri Oct 11 20:25:10 2024] Read in and count kmers for 500000 reads.
[Fri Oct 11 20:25:12 2024] Read in and count kmers for 600000 reads.
[Fri Oct 11 20:25:14 2024] Read in and count kmers for 700000 reads.
[Fri Oct 11 20:25:16 2024] Read in and count kmers for 800000 reads.
[Fri Oct 11 20:25:17 2024] Read in and count kmers for 900000 reads.
[Fri Oct 11 20:25:19 2024] Read in and count kmers for 1000000 reads.
[Fri Oct 11 20:25:21 2024] Read in and count kmers for 1100000 reads.
[Fri Oct 11 20:25:23 2024] Read in and count kmers for 1200000 reads.
[Fri Oct 11 20:25:25 2024] Read in and count kmers for 1300000 reads.
[Fri Oct 11 20:25:26 2024] Read in and count kmers for 1400000 reads.
[Fri Oct 11 20:25:28 2024] Read in and count kmers for 1500000 reads.
[Fri Oct 11 20:25:30 2024] Read in and count kmers for 1600000 reads.
[Fri Oct 11 20:25:32 2024] Read in and count kmers for 1700000 reads.
[Fri Oct 11 20:25:34 2024] Read in and count kmers for 1800000 reads.
[Fri Oct 11 20:25:36 2024] Read in and count kmers for 1900000 reads.
[Fri Oct 11 20:25:38 2024] Read in and count kmers for 2000000 reads.
[Fri Oct 11 20:25:40 2024] Read in and count kmers for 2100000 reads.
[Fri Oct 11 20:25:42 2024] Read in and count kmers for 2200000 reads.
[Fri Oct 11 20:25:44 2024] Read in and count kmers for 2300000 reads.
[Fri Oct 11 20:25:46 2024] Read in and count kmers for 2400000 reads.
[Fri Oct 11 20:25:48 2024] Read in and count kmers for 2500000 reads.
[Fri Oct 11 20:25:50 2024] Read in and count kmers for 2600000 reads.
[Fri Oct 11 20:25:53 2024] Read in and count kmers for 2700000 reads.
[Fri Oct 11 20:25:55 2024] Read in and count kmers for 2800000 reads.
[Fri Oct 11 20:25:57 2024] Read in and count kmers for 2900000 reads.
[Fri Oct 11 20:25:59 2024] Read in and count kmers for 3000000 reads.
[Fri Oct 11 20:26:01 2024] Read in and count kmers for 3100000 reads.
[Fri Oct 11 20:26:03 2024] Read in and count kmers for 3200000 reads.
[Fri Oct 11 20:26:05 2024] Read in and count kmers for 3300000 reads.
[Fri Oct 11 20:26:07 2024] Read in and count kmers for 3400000 reads.
[Fri Oct 11 20:26:09 2024] Read in and count kmers for 3500000 reads.
[Fri Oct 11 20:26:11 2024] Read in and count kmers for 3600000 reads.
[Fri Oct 11 20:26:14 2024] Read in and count kmers for 3700000 reads.
[Fri Oct 11 20:26:16 2024] Read in and count kmers for 3800000 reads.
[Fri Oct 11 20:26:19 2024] Read in and count kmers for 3900000 reads.
[Fri Oct 11 20:26:21 2024] Read in and count kmers for 4000000 reads.
[Fri Oct 11 20:26:24 2024] Read in and count kmers for 4100000 reads.
[Fri Oct 11 20:26:26 2024] Read in and count kmers for 4200000 reads.
[Fri Oct 11 20:26:29 2024] Read in and count kmers for 4300000 reads.
[Fri Oct 11 20:26:32 2024] Read in and count kmers for 4400000 reads.
[Fri Oct 11 20:26:34 2024] Read in and count kmers for 4500000 reads.
[Fri Oct 11 20:26:37 2024] Read in and count kmers for 4600000 reads.
[Fri Oct 11 20:26:39 2024] Read in and count kmers for 4700000 reads.
[Fri Oct 11 20:26:42 2024] Read in and count kmers for 4800000 reads.
[Fri Oct 11 20:26:45 2024] Read in and count kmers for 4900000 reads.
[Fri Oct 11 20:26:48 2024] Read in and count kmers for 5000000 reads.
[Fri Oct 11 20:26:51 2024] Read in and count kmers for 5100000 reads.
[Fri Oct 11 20:26:54 2024] Read in and count kmers for 5200000 reads.
[Fri Oct 11 20:26:57 2024] Read in and count kmers for 5300000 reads.
[Fri Oct 11 20:27:00 2024] Read in and count kmers for 5400000 reads.
[Fri Oct 11 20:27:03 2024] Read in and count kmers for 5500000 reads.
[Fri Oct 11 20:27:06 2024] Read in and count kmers for 5600000 reads.
[Fri Oct 11 20:27:09 2024] Read in and count kmers for 5700000 reads.
[Fri Oct 11 20:27:12 2024] Read in and count kmers for 5800000 reads.
[Fri Oct 11 20:27:15 2024] Read in and count kmers for 5900000 reads.
[Fri Oct 11 20:27:18 2024] Read in and count kmers for 6000000 reads.
[Fri Oct 11 20:27:20 2024] Read in and count kmers for 6100000 reads.
[Fri Oct 11 20:27:23 2024] Read in and count kmers for 6200000 reads.
[Fri Oct 11 20:27:26 2024] Read in and count kmers for 6300000 reads.
[Fri Oct 11 20:27:29 2024] Read in and count kmers for 6400000 reads.
[Fri Oct 11 20:27:31 2024] Read in and count kmers for 6500000 reads.
[Fri Oct 11 20:27:34 2024] Read in and count kmers for 6600000 reads.
[Fri Oct 11 20:27:37 2024] Read in and count kmers for 6700000 reads.
[Fri Oct 11 20:27:40 2024] Read in and count kmers for 6800000 reads.
[Fri Oct 11 20:27:42 2024] Read in and count kmers for 6900000 reads.
[Fri Oct 11 20:27:45 2024] Read in and count kmers for 7000000 reads.
[Fri Oct 11 20:27:48 2024] Read in and count kmers for 7100000 reads.
[Fri Oct 11 20:27:51 2024] Read in and count kmers for 7200000 reads.
[Fri Oct 11 20:27:54 2024] Read in and count kmers for 7300000 reads.
[Fri Oct 11 20:27:57 2024] Read in and count kmers for 7400000 reads.
[Fri Oct 11 20:27:59 2024] Read in and count kmers for 7500000 reads.
[Fri Oct 11 20:28:02 2024] Read in and count kmers for 7600000 reads.
[Fri Oct 11 20:28:05 2024] Read in and count kmers for 7700000 reads.
[Fri Oct 11 20:28:08 2024] Read in and count kmers for 7800000 reads.
[Fri Oct 11 20:28:11 2024] Read in and count kmers for 7900000 reads.
[Fri Oct 11 20:28:14 2024] Read in and count kmers for 8000000 reads.
[Fri Oct 11 20:28:17 2024] Read in and count kmers for 8100000 reads.
[Fri Oct 11 20:28:20 2024] Read in and count kmers for 8200000 reads.
[Fri Oct 11 20:28:23 2024] Read in and count kmers for 8300000 reads.
[Fri Oct 11 20:28:26 2024] Read in and count kmers for 8400000 reads.
[Fri Oct 11 20:28:29 2024] Read in and count kmers for 8500000 reads.
[Fri Oct 11 20:28:32 2024] Read in and count kmers for 8600000 reads.
[Fri Oct 11 20:28:35 2024] Read in and count kmers for 8700000 reads.
[Fri Oct 11 20:28:38 2024] Read in and count kmers for 8800000 reads.
[Fri Oct 11 20:28:43 2024] Read in and count kmers for 8900000 reads.
[Fri Oct 11 20:28:46 2024] Read in and count kmers for 9000000 reads.
[Fri Oct 11 20:28:49 2024] Read in and count kmers for 9100000 reads.
[Fri Oct 11 20:28:52 2024] Read in and count kmers for 9200000 reads.
[Fri Oct 11 20:28:55 2024] Read in and count kmers for 9300000 reads.
[Fri Oct 11 20:28:58 2024] Read in and count kmers for 9400000 reads.
[Fri Oct 11 20:29:02 2024] Read in and count kmers for 9500000 reads.
[Fri Oct 11 20:29:05 2024] Read in and count kmers for 9600000 reads.
[Fri Oct 11 20:29:08 2024] Read in and count kmers for 9700000 reads.
[Fri Oct 11 20:29:11 2024] Read in and count kmers for 9800000 reads.
[Fri Oct 11 20:29:14 2024] Read in and count kmers for 9900000 reads.
[Fri Oct 11 20:33:32 2024] Found 9450927 reads.
[Fri Oct 11 20:33:47 2024] Finish sorting the reads.
[Fri Oct 11 20:40:26 2024] Finish rough annotations.
[Fri Oct 11 20:40:27 2024] Processed 100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:27 2024] Processed 1600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 1700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 1800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 1900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 2900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 3900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 4900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 5900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 6000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:28 2024] Processed 6100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 6900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 7900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8500000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8600000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8700000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8800000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 8900000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 9000000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 9100000 reads (0 are used for assembly).
[Fri Oct 11 20:40:29 2024] Processed 9200000 reads (0 are used for assembly).
[Fri Oct 11 20:40:30 2024] Processed 9300000 reads (0 are used for assembly).
[Fri Oct 11 20:40:30 2024] Processed 9400000 reads (0 are used for assembly).
[Fri Oct 11 20:40:30 2024] Assembled 0 reads.
[Fri Oct 11 20:40:30 2024] Try to rescue 0 reads for assembly.
[Fri Oct 11 20:40:30 2024] Rescued 0 reads.
[Fri Oct 11 20:40:36 2024] SYSTEM CALL: /nethome/svc.build/modules/easybuild/software/TRUST4/1.0.14-GCC-11.3.0/bin/annotator -f /nethome/df/Documents/scRNA/10x_refs/trust4/human_IMGT+C.fa -a /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001_final.out -t 1 -o /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001  --barcode --outputCDR3File --airrAlignment > /mnt/df/H/Bioinformatics/exp_imm/NI/NI_031/vdj_gd/TRUST_gd-1_R1_001_annot.fa
[Fri Oct 11 20:40:36 2024] Start to annotate assemblies.
[Fri Oct 11 20:40:36 2024] Finish annotation.

**Comment by mourisl** [comment]
Could you please show me the first few lines of the TRUST_gd-1_R1_001_toassemble_{1,2,bc}.f{q,a} files?

**Comment by fonseca-dfm** [comment]
PS C:\Users\daniel.fonseca\Downloads> Get-Content .\TRUST_gd-1_R1_001_toassemble_1.fq -TotalCount 20
@LH00449:49:22NHYJLT3:3:1101:4107:1096
TCGGCAGCCGTTTCTTATATGGGGACTGAACTTTGAGCTTCAGGCAGCACAACTCACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGAT
+
TCGGCAGCCGTTTCTTATATGGGGACTGAACTTTGAGCTTCAGGCAGCACAACTCACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGAT
@LH00449:49:22NHYJLT3:3:1101:6326:1096
AAAGTGGCGCTTTCTTATATGGGAGTCACTTCTCTCTGCTTGTGTCTCAGGAAGACCAGCTCCTCCTACTGTCTTCTGTGCTAGGGATCACTTCCTTGTTGAGTGGGGCCTGAGTTTTAAGAGGATCTTCTGCT
+
AAAGTGGCGCTTTCTTATATGGGAGTCACTTCTCTCTGCTTGTGTCTCAGGAAGACCAGCTCCTCCTACTGTCTTCTGTGCTAGGGATCACTTCCTTGTTGAGTGGGGCCTGAGTTTTAAGAGGATCTTCTGCT
@LH00449:49:22NHYJLT3:3:1101:8600:1096
CTGCTATACTTTTCTTATATGGGAGCACAACTCACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGATCAAGTGTGGAGATCGGAAGAGC
+
CTGCTATACTTTTCTTATATGGGAGCACAACTCACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGATCAAGTGTGGAGATCGGAAGAGC
@LH00449:49:22NHYJLT3:3:1101:21656:1096
TNTACCCAGGTTTCTTATATGGGGACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGATCAAGTGTGGCCCAGAAGGTTACTCAAGCCCA
+
TNTACCCAGGTTTCTTATATGGGGACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGATCAAGTGTGGCCCAGAAGGTTACTCAAGCCCA
@LH00449:49:22NHYJLT3:3:1101:23468:1096
ANTTGCTGCTTTTCTTATATGGGGACTGAACTTTGAGCTTCAGGCAGCACAACTCACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGAT
+
ANTTGCTGCTTTTCTTATATGGGGACTGAACTTTGAGCTTCAGGCAGCACAACTCACATTTGTGCAAAGAGCTACATGCCACATGCTGTTCTCCAGCCTGCTGTGTGTATTTGTGGCCTTCAGCTACTCTGGAT
PS C:\Users\daniel.fonseca\Downloads>

PS C:\Users\daniel.fonseca\Downloads> Get-Content .\TRUST_gd-1_R1_001_toassemble_2.fq -TotalCount 20
@LH00449:49:22NHYJLT3:3:1101:4107:1096
CTTGTACCAAAAAATATAATATGACCACCAACTTGTTTCATACAGGCAGTTCAGGGTGACTGCTTTCCTCACTGGCATGGATACTGATGACTGGGCTTGAGTAACCTTCTGGGCCACACTTGATCCAGAGTAGCTGAAGGCCACAAATAC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@LH00449:49:22NHYJLT3:3:1101:6326:1096
CCTTGTGCTTCCATAAGTATCATACTTCCCTGGGCTGATTCCTGATTCCAACACAACGCTGGAGGTGTAGGAGTCATAGTACAGAAGACGCTGTGGGGCCTTCCCCTCCTGGTGTAGGTACCAGTGGATGTAGCCGGTACTTCCTTCAGC
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIII
@LH00449:49:22NHYJLT3:3:1101:8600:1096
CCACACTTGATCCAGAGTAGCTGAAGGCCACAAATACACACAGCAGGCTGGAGAACAGCATGTGGCATGTAGCTCTTTGCACAAATGTGAGTTGTGCTCCCATATAAGAAAAGTATAGCAGTCTTACATGTAAAGGTAGATCGGAAGAGC
+
9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
@LH00449:49:22NHYJLT3:3:1101:21656:1096
TGGTTTGGTATGAGGCTGACTTCTTGGTTCCACAGTCACACGGGTTCCTTTTCCAAAGATGAGTTTATCGGTGCGCGATCGTATCCCCCAGTACATAATGGAGGCTTCCCCAAGAGCACAAAAGTACTTTGCTGAATCTTCTAGCTGTAA
+
I9IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII-IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII9IIIIIIIIIIIIIIIIIIIII9
@LH00449:49:22NHYJLT3:3:1101:23468:1096
AGTTCAGGGTGACTGCTTTCCTCACTGGCATGGATACTGATGACTGGGCTTGAGTAACCTTCTGGGCCACACTTGATCCAGAGTAGCTGAAGGCCACAAATACACACAGCAGGCTGGAGAACAGCATGTGGCATGTAGCTCTTTGCACAA
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII


PS C:\Users\daniel.fonseca\Downloads> Get-Content .\TRUST_gd-1_R1_001_toassemble_bc.fa -TotalCount 40
>LH00449:49:22NHYJLT3:3:1101:4107:1096
GCGAGAAAGCCATCGC
>LH00449:49:22NHYJLT3:3:1101:6326:1096
CGGACGTCAAGCCGCT
>LH00449:49:22NHYJLT3:3:1101:8600:1096
ACCTTTACATGTAAGA
>LH00449:49:22NHYJLT3:3:1101:21656:1096
CAGAATCCACCCATGG
>LH00449:49:22NHYJLT3:3:1101:23468:1096
ACCAGTACATTGGTAC
>LH00449:49:22NHYJLT3:3:1101:23635:1096
TACTCGCAGTCGATAA
>LH00449:49:22NHYJLT3:3:1101:14416:1112
TACTCGCAGTCGATAA
>LH00449:49:22NHYJLT3:3:1101:27324:1112
missing_barcode
>LH00449:49:22NHYJLT3:3:1101:30523:1112
CTGTGCTTCACCACCT
>LH00449:49:22NHYJLT3:3:1101:32021:1112
ACATACGAGGGAACGG
>LH00449:49:22NHYJLT3:3:1101:37346:1112
GACACGCCACACGCTG
>LH00449:49:22NHYJLT3:3:1101:46278:1112
TCATTACCACGGCGTT
>LH00449:49:22NHYJLT3:3:1101:48978:1112
CTGCTGTAGAGTGACC
>LH00449:49:22NHYJLT3:3:1101:19696:1128
GGCTGGTGTTATTCTC
>LH00449:49:22NHYJLT3:3:1101:24467:1128
GGACGTCCAATGTAAG
>LH00449:49:22NHYJLT3:3:1101:26889:1128
CAGAGAGAGATGTTAG
>LH00449:49:22NHYJLT3:3:1101:31882:1128
TCTCATAAGGCGTACA
>LH00449:49:22NHYJLT3:3:1101:42497:1128
GTACGTAGTTACGTCA
>LH00449:49:22NHYJLT3:3:1101:14971:1144
GATCTAGGTGCGAAAC
>LH00449:49:22NHYJLT3:3:1101:15137:1144
CACTCCAGTAAGGATT

**Comment by mourisl** [comment]
Sorry for the delayed reply. I just tested the github version of TRUST4 on the example file your provided, and the reads can be assembled. Could you please update the TRUST4 to the most recent version (v1.1.4 should be fine), and give it a try?

**Comment by mourisl** [comment]
What is TRUST4's running output on the example file provided in the github repository?

**Comment by fonseca-dfm** [comment]
Hi. Thanks managed to figure out the issue. One of the reference files was corrupt, hence no assembly. Thank you so much. I really appreciate your help.
