### ISSUE TITLE
Segmentation fault (core dumped) when start to annotate assemblies

### ISSUE THREAD

**Issue by Huangq0825** [liulab-dfci/TRUST4#324]
Hello,
I'm using TRUST4 (v1.1.5-r561) to assemble TCRs sequenced by 10X platform, but the error only happened on one sample C463T, the other samples were fine, so I want to know how to solve this problem:
"_Start to annotate assemblies.
sh: line 1: 782131 Segmentation fault (core dumped)  
./TRUST4/annotator -f human_IMGT+C.fa -a TRUST_C463T_S1_L004_R1_001_final.out -t 1 -o TRUST_C463T_S1_L004_R1_001 --barcode -r TRUST_C463T_S1_L004_R1_001_assembled_reads.fa --airrAlignment > TRUST_C463T_S1_L004_R1_001_annot.fa
failed: 35584 at ./TRUST4/run-trust4 line 60._"
Is there any misassembled contig? or other errors in TRUST_C463T_S1_L004_R1_001_final.out caused such problem?
Thanks your attention!

**Comment by mourisl** [comment]
This is likely to be a bug from recent updates. Could you please share the files generated from TRUST4? If it is too large, is it possible to share the _final.out or the to_assemble files? Thank you.

**Comment by Huangq0825** [comment]
Thanks for your response, I'm sorry the file is too large to send. Actually, I can run it successful with the bam file produced from cellranger, but in this way, the report columns include assemble id  rather than barcode id, which is important for the following analysis. So, my question now is how to use bam file to run this pipeline and get the barcode id in the report file for downstream analysis.
best regards,
Qiang Huang
获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Huangq0825** [comment]
I'm so appreciate that adding "_--barcode CB_" is work, thank you very much.
best regards,
Qiang Huang

**Comment by mourisl** [comment]
Could you please share the previous final.out file from the failed run? It would be nice to have that data to debug TRUST4's issues in case other people may encounter it. Thank you!
