### ISSUE TITLE
Question: use on demultiplexed single cell ONT data 

### ISSUE THREAD

**Issue by andreas-wilm** [liulab-dfci/TRUST4#326]
Hi there,

May I ask whether I can use TRUST4 on already demultiplexed single cell ONT data (avg Q=15), which is enriched for BCRs and TCRs? If yes, I suppose I need to jump straight to the annotation stage (--stage 1)? Are there any caveats I should be aware of?

Many thanks for this awesome tool!
Andreas

**Comment by mourisl** [comment]
Stage 1 is for assembly step. Stage 2 is for annotation. The annotation step requires several file in special format, like sequence with position weight matrix (_final.out), and the read name should be in the fashion of "{barcode}_XXX". I think you can start with the assembly step for now with the "--noExtraction" step to skip the candidate read extraction step. TRUST4 at least shouldn't crash on long-read data set, but the high indel error rate is not specifically modeled by TRUST4, so I'm not sure how good the result would be. Hope this helps.

**Comment by andreas-wilm** [comment]
Many thanks! This makes sense.

May I ask how the barcodes are used in that case? I realize that TRUST4 normally deals automatically with UMIs for example ([as e.g.  discussed here](https://github.com/liulab-dfci/TRUST4/issues/254)). However, since my input is demultiplexed it already contains cellbarcode and UMI in the sequence ids rather than the sequence itself, so I can't use `--readFormat`. I suppose TRUST4 is not aware of the barcodes in that case, at least not with default parameters. How can I make TRUST4 barcode+UMI aware in my case? Should I convert my FastQ to BAM first, splitting the UMI info into a separate field, such that it can be used with `--UMI`? And how about the cell barcodes?

Many thanks again!

PS: I forgot to mention that this is 10X data in case it matters.

**Comment by mourisl** [comment]
You can create another fastq/fasta file containing the barcode and UMI sequence for each read, and provide it through the "--barcode" and "--UMI" options. Then the "--readFormat" can be used.

**Comment by andreas-wilm** [comment]
Thank you. Do I understand correctly that `--barcode` and `--UMI` define the list of allowed barcodes? So if I had to construct a FastQ file with already extracted and cleaned barcode and UMIs anyway, I could also just use `--readFormat`, correct? Thanks again

**Comment by andreas-wilm** [comment]
Ah sorry.  I guess I was thinking of `--barcodeWhitelist`. Still, what do `--barcode` and `--UMI` do when I just have one FastQ file?

**Comment by mourisl** [comment]
For example, you find that the barcode and UMI for a read are "ACGTACGT" and "TGCA", respectively. Then you can create a fasta file with the sequence "ACGTACGTTGCA" for that read, say this file is "bc_umi.fa". When running trust4, you can add the option "--barcode bc_umi.fa --UMI bc_umi.fa --readFormat bc:0:7,um:8:-1". The "--barcode" and "--UMI" specify which file holds the barcode and UMI sequences for each read. The file should be in the same order as the "-1/-2/-u" file. Hope this helps.

**Comment by andreas-wilm** [comment]
I finally got it :) Thank you so much!
