### ISSUE TITLE
Slashes in the reference file prevent annotating some clonotypes

### ISSUE THREAD

**Issue by danich4114** [liulab-dfci/TRUST4#33]
Hello

Run-trust4 does not output clonotypes with TRAV23DV6, TRAV29DV5, TRAV36DV7, TRAV38-2DV8 (and probably many others) V regions in report.tsv if I use default reference file human_IMGT+C.fa from your repository. I suggest the problem is in slashes in human_IMGT+C.fa in these genes, like TRAV29/DV5*01, comparing to hg38_bcrtcr.fa where these genes do not have slashes, like TRAV29DV5.

After deleting slashes in human_IMGT+C.fa in these genes and launching run-trust4 with the same parameters they are output to report.tsv.

I use this command:
./run-trust4 -b $BAM -f hg38_bcrtcr.fa --ref human_IMGT+C.fa

**Comment by mourisl** [comment]
Thank you for sharing this issue! I just pushed the fix to github, could you please give it a try?

I filtered the genes with "/" symbol to avoid the orphan genes, which seems to cause more false positives, and did not notice there were "DV" cases. Thank you for finding this issue!
