### ISSUE TITLE
Example human data?

### ISSUE THREAD

**Issue by kc199** [liulab-dfci/TRUST4#41]
Hi, thanks for making this code public- excited to try out the method.  I was wondering if you have example human data output- I'm assuming the bam file in the example folder is human?  Would be good to know the expected output just to make sure I've set up the method correctly.  Thanks!

**Comment by mourisl** [comment]
Thanks for the suggestion. I've uploaded the expected results for the example data in the "example" folder. This example data is sampled from a human simulated data set.

**Comment by kc199** [comment]
Thank you!
