### ISSUE TITLE
filter parameters

### ISSUE THREAD

**Issue by zhouxinseeu** [liulab-dfci/TRUST4#44]
Hi!

I have got some results by analyzing 10X SC data. I've compared it with 10X results and I found that the TRUST4 results are much more than 10X. In my opinion, it's not normal. So I want to filter TRUST4 results. Is there any recommended filtering parameters for TRUST4?

Thank you!

**Comment by mourisl** [comment]
I observed the same case in several samples too. However, if we focus on the cells passed Seurat QC, 10x V(D)J still found more CDR3s. So the filtration should be using conventional single-cell RNA-seq QC, not through TRUST4.

**Comment by zhouxinseeu** [comment]
Thank you for your quick reply. I will try it later.
