### ISSUE TITLE
How to calculate CPK/other diversity metrics- read counts in TCR/BCR regions?

### ISSUE THREAD

**Issue by kc199** [liulab-dfci/TRUST4#45]
Hi, going through the paper and some of the prior TRUST papers, I had a question about diversity metrics.  In the original TRUST paper, there is a metric called "clonotypes per thousand kilo reads (CPK)", i.e. Fig 4c from https://www.nature.com/articles/ng.3581.pdf. 

According to that paper, CPK is defined as "the number of unique CDR3 calls in each sample normalized by the total read count in the TCR region".  

It would be great to calculate CPK separately for TCR and BCR from TRUST4 output- is the total read count in the TCR region output from TRUST4?  Also wondering if it outputs total read count in the BCR region?  Those values would also be useful for shannon entropy/richness/evenness calculations. 

Thank you very much for your help!

**Comment by mourisl** [comment]
No, you need to extract the TCR and BCR from the report file based on the V/J/C gene assignment. There are several downstream analysis methods such as VDJTools, immunarch that should be able to parse TRUST4's report file (maybe need a few tweaking).

We also provide a python script "trust-stats.py" in the repo. You can run "python3 trust-stats.py -r trust_report.tsv" to obtain those statistics for different chains. The default behavior is using CDR3 amino acids. You can run "python3 trust-stats.py -h" for more information. Thank you!

**Comment by kc199** [comment]
The trust-stats.py script is fantastic!  I see CPK, entropy, and clonality there- exactly what I needed.  Thanks so much for your help and such a quick response!
