### ISSUE TITLE
10x cell barcode and UMI

### ISSUE THREAD

**Issue by BioAmelie** [liulab-dfci/TRUST4#46]
Hi @mourisl 

 I have 10x scRNA-seq data. Cell barcode and UMI are deposited in R1.fastq.gz. The 16 bp 10x Barcode and 12 bp UMI are encoded in R1.fastq.gz and  Read 2 is used to sequence the cDNA fragment. Does `--barcodeRange` is only for cell barcode location? Should I concern the UMI location? What's more,  if I only want to analyze some special cells, for example, T cells, should I provide the `--barcodeWhitelist`  file containing the T cells barcode?

 This is my command for 10x data: `run-trust4 -f hg38_bcrtcr.fa --ref human_IMGT+C.fa -u path_to_10X_fastqs/*_R2_*.fastq.gz --barcode path_to_10X_fastqs/*_R1_*.fastq.gz --barcodeRange 0 15 + --barcodeWhiteList Tcells-barcode.txt` Can you tell me whether it is right?

 Best regards

 minfang

**Comment by mourisl** [comment]
Yes, regarding the barcode, your command is correct. You don't need to worry about the position for UMIs. 

For the barcodeWhitelist, though you can use it for barcode filtration, I would not recommend so.  For example, an erroneous barcode can be corrected to two barcodes in the whole whitelist, with quality score information and global abundance estimation, it can be assigned to a non Tcell barcode. If you only provide T cell barcode, this barcode might be corrected to another "wrong" barcode. You can run TRUST4 with all the data, and write a postscript (or just fgrep -f) to extract those T cells from the trust4_barcode_report.tsv file.

Does this help?  Thanks.

**Comment by BioAmelie** [comment]
okay, but I worried that if I run on all the data, does it spend a lot of time?

**Comment by mourisl** [comment]
The speed should be fine. For a typical PBMC scRNA-seq data, it should finish within about 1.5 hours starting from raw fastq files.

**Comment by BioAmelie** [comment]
That's great! I have also run in BAM (cellranger processed). However I only get 738 unique barcodes in barcode_report.tsv, the origin BAM should contain lots of cells. This is my command : `run-trust4 -t 10 -b $BAM -f ${tcrfa} --ref ${IGMTfa} --barcode CB -o testBAM`

**Comment by BioAmelie** [comment]
Hi @mourisl 
 As for my last question, it seemed that trust4 did not find TCR or BCR for all cells in BAM. After all, the  BAM files maybe contain thousands of cells. Is there something wrong with my data?

**Comment by mourisl** [comment]
Is this a 5' 10x scRNA-seq kit or regular 3' scRNA-seq kit?

**Comment by BioAmelie** [comment]
Hi @mourisl 

 it is 5' 10x scRNA-seq kit.

**Comment by mourisl** [comment]
I would guess there might be few T cell or B cell in the sample, is it the case from the scRNA-seq analysis (like Seurat annotation)? For the ${tcrfa}, is it just TCR sequence not including BCR sequences? Thank you.

**Comment by BioAmelie** [comment]
Hi @mourisl 

 sorry, it it  3' scRNA-seq kit

**Comment by BioAmelie** [comment]
Hi @mourisl 
 I am running fastq data. I will compare the fastq output and BAM output, then I will tell you whether these two outputs have similar cell number.

**Comment by mourisl** [comment]
If it is a 3' kit, the numbers make sense. Since most of the 3' reads lie on the constant genes, the sensitivity for CDR3 assembly is much lower.

**Comment by BioAmelie** [comment]
Hi @mourisl 
 In my 10x data, it at least contains 2000 T cells and 1000 B cells. The ${tcrfa} contains BCR and TCR.

**Comment by BioAmelie** [comment]
oh, That's too bad! Does trust4 have any remedial measure for 3' kit?

**Comment by mourisl** [comment]
I don't think there is a way to improve the sensitivity computationally, since there is no read coverage at all near the 5' end in a 3' kit in most of the cells.

**Comment by BioAmelie** [comment]
okay, Thanks for your replay~
 Best regards
 minfang
