### ISSUE TITLE
Coverage of Paired Chain 10x  trust_barcode_report.tsv

### ISSUE THREAD

**Issue by tAndreani** [liulab-dfci/TRUST4#50]
Hello,

thanks a lot for the great software provided. I have a question regarding the output of 10x data file "trust_barcode_report.tsv". I would like to know the information of the columns. Please see the picture below:

![image](https://user-images.githubusercontent.com/6462162/122395116-f6e18f00-cf76-11eb-8633-5db0b6d29c67.png)

For the first row, the barcode (or single cell) AAAGAAACAGAAACCA, has both chains heavy and light. Is there a way to retrieve the coverage for those chains? Are the numbers "93.10" for the IGHG1 and  "95.65" for the IGKC related to the  coverage? 

Thank you for your reply and feedback.

**Comment by mourisl** [comment]
93.1 and 95.65 related to the alignment similarity with V (,D), J genes that are in the CDR3 region. This information could be useful in some phylogeny analysis. For coverage, do you mean the number of reads supporting this chain or the length of assembly? The 7th number in each field (3.62, 6.55) represents the read coverage. For assembly length, the last number indicate whether the assembly is full-length or not. The sequence id is in the third last (XXX_9575), and you can find the sequence in the trust_annot.fa file.

**Comment by tAndreani** [comment]
Now is clear. Another question: what do you mean by assembly "full length"? For full length do you mean whether they have all the CDR (1,2,3) and all FR (1,2,3,4)?

Those 7 single cells in the picture above are paired chains because there is one heavy and one light chain for the same single cell (barcode).

Please correct me if I am wrong.

**Comment by mourisl** [comment]
Yes, full-length means have all three CDR3s and all frame regions. Your interpretation of paired chains results is very precise.
