### ISSUE TITLE
UMI info and VDJ 10x data

### ISSUE THREAD

**Issue by tAndreani** [liulab-dfci/TRUST4#51]
Hello,

i have two questions:

1) Is there a way to retrieve how many UMI support the expression of a each of the VDJ genes?
2) Is it possible to run TRUST4 on VDJ 10x data? I know that 10x 5' works but i am wondering if i can also use TRUST4 with VDJ 10x libraries

Thank you in advance for your reply

**Comment by mourisl** [comment]
I just add the option for --UMI to fully support UMI quantification. The usage is similar to the usage of parsing barcode. TRUST4 also works on the 10x VDJ data. From my preliminary comparisons, it seems TRUST4 was more sensitive than CellRangerVDJ, but more comparisons were still needed. Is there an application on why you want to try TRUST4 other than CellRanger VDJ on your data? Thank you.

**Comment by tAndreani** [comment]
There is no specific application. It is mostly my curiosity to try TRUST4 on both VDJ and 5' libraries from a given sample and see how much the results are consistent. Have you already pushed the UMI option? Thank you

**Comment by mourisl** [comment]
Yes, you can use "git pull" or "git clone" to get the version.
