### ISSUE TITLE
TRUST4 Fails at annotation

### ISSUE THREAD

**Issue by jkbenotmane** [liulab-dfci/TRUST4#52]
When Calling run-trust4 with previously tested options (on another sample) annotation keeps failing

(base) user@DESKTOP:/mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sample9/TRUST4$ run-trust4 -u '/mnt/d/Dropbox/User/Sequencing_Data/TCR/Sample9_sample_basecall/Merge/Sample9_pass_fail.fastq' -o 'Output_Sequencing9_unprocessed' -f '/mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa' --ref '/mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa' -t 16
[Wed Jun 23 09:13:36 2021] TRUST4 begins.
[Wed Jun 23 09:13:36 2021] SYSTEM CALL: /home/user/anaconda3/bin/fastq-extractor -t 16 -f /mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa -o Output_Sequencing9_unprocessed_toassemble  -u /mnt/d/Dropbox/User/Sequencing_Data/TCR/Sample9_sample_basecall/Merge/Sample9_pass_fail.fastq
[Wed Jun 23 09:13:36 2021] Start to extract candidate reads from read files.
[Wed Jun 23 09:23:16 2021] Finish extracting reads.
[Wed Jun 23 09:23:16 2021] SYSTEM CALL: /home/user/anaconda3/bin/trust4  -f /mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa -t 16 -o Output_Sequencing9_unprocessed -u Output_Sequencing9_unprocessed_toassemble.fq
[Wed Jun 23 09:24:12 2021] Read in and count kmers for 100000 reads.
[Wed Jun 23 09:25:22 2021] Read in and count kmers for 200000 reads.
[Wed Jun 23 09:26:42 2021] Read in and count kmers for 300000 reads.
[Wed Jun 23 09:28:05 2021] Read in and count kmers for 400000 reads.
[Wed Jun 23 09:29:34 2021] Read in and count kmers for 500000 reads.
[Wed Jun 23 09:31:07 2021] Read in and count kmers for 600000 reads.
[Wed Jun 23 09:32:44 2021] Read in and count kmers for 700000 reads.
[Wed Jun 23 09:44:06 2021] Found 725057 reads.
[Wed Jun 23 09:44:53 2021] Finish sorting the reads.
[Wed Jun 23 09:46:39 2021] Finish rough annotations.
[Wed Jun 23 09:54:25 2021] Processed 100000 reads (33266 are used for assembly).
[Wed Jun 23 10:14:57 2021] Processed 200000 reads (88894 are used for assembly).
[Wed Jun 23 10:37:54 2021] Processed 300000 reads (137388 are used for assembly).
[Wed Jun 23 10:59:55 2021] Processed 400000 reads (192723 are used for assembly).
[Wed Jun 23 11:24:41 2021] Processed 500000 reads (253617 are used for assembly).
[Wed Jun 23 11:51:31 2021] Processed 600000 reads (324665 are used for assembly).
[Wed Jun 23 12:12:16 2021] Processed 700000 reads (390685 are used for assembly).
[Wed Jun 23 12:15:41 2021] Assembled 404845 reads.
[Wed Jun 23 12:15:41 2021] Try to rescue 0 reads for assembly.
[Wed Jun 23 12:15:45 2021] Rescued 0 reads.
[Wed Jun 23 13:07:47 2021] SYSTEM CALL: /home/user/anaconda3/bin/annotator -f /mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa -a Output_Sequencing9_unprocessed_final.out -t 16 -o Output_Sequencing9_unprocessed  -r Output_Sequencing9_unprocessed_assembled_reads.fa > Output_Sequencing9_unprocessed_annot.fa
[Wed Jun 23 13:07:48 2021] Start to annotate assemblies.
malloc(): invalid size (unsorted)
Aborted
system /home/user/anaconda3/bin/annotator -f /mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa -a Output_Sequencing9_unprocessed_final.out -t 16 -o Output_Sequencing9_unprocessed  -r Output_Sequencing9_unprocessed_assembled_reads.fa > Output_Sequencing9_unprocessed_annot.fa failed: 34304 at /home/user/anaconda3/bin/run-trust4 line 47.

when restarting at annotation step:

(base) user@DESKTOP:/mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sample9/TRUST4$ run-trust4 -u '/mnt/d/Dropbox/User/Sequencing_Data/TCR/Sample9_sample_basecall/Merge/Sample9_pass_fail.fastq' -o 'Output_Sequencing9_unprocessed' -f '/mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa' --ref '/mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa' -t 16 --stage 2
[Wed Jun 23 13:34:53 2021] TRUST4 begins.
[Wed Jun 23 13:34:53 2021] SYSTEM CALL: /home/user/anaconda3/bin/annotator -f /mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa -a Output_Sequencing9_unprocessed_final.out -t 16 -o Output_Sequencing9_unprocessed  -r Output_Sequencing9_unprocessed_assembled_reads.fa > Output_Sequencing9_unprocessed_annot.fa
[Wed Jun 23 13:34:53 2021] Start to annotate assemblies.
malloc(): invalid size (unsorted)
Aborted
system /home/user/anaconda3/bin/annotator -f /mnt/d/Dropbox/User/Projects/TCR_SEQ/Samples/Sequencing/Sequencing2/TRUST4/IMGT+C.fa -a Output_Sequencing9_unprocessed_final.out -t 16 -o Output_Sequencing9_unprocessed  -r Output_Sequencing9_unprocessed_assembled_reads.fa > Output_Sequencing9_unprocessed_annot.fa failed: 34304 at /home/user/anaconda3/bin/run-trust4 line 47.

**Comment by mourisl** [comment]
Are you using the bioconda version? There are a few bug fixes afterwards, could you please try the github repo version with git clone and "make"? You can still run TRUST4 with the option "--stage 2". If it fails, could you please share the file "Output_Sequencing9_unprocessed_final.out" with me? 

Since the kmer counting step was very slow on your data, I'm wondering what is the read length? If a read is too long, some of the buffers I allocated might be too small and I can fix that. Thank you.

**Comment by jkbenotmane** [comment]
Thank you very much for the quick response ! 
considering your questions:
yes I am working with the bioconda version.

I am working with long-reads generated from Oxford Nanopore which have a mean length around 1000bp.

Thank you very much for your help!

**Comment by mourisl** [comment]
What is the longest read in your data? I think the current buffer size is 10240, which should be sufficient for the RNA length. Due to the high error rate in nanopore sequencing, I don't expect TRUST4 to perform well. Is your data error corrected or already been assembled? We have tested TRUST4 on Pacbio Hifi data, which has much lower error rate.

**Comment by jkbenotmane** [comment]
My longest Read is around 11kb:
file                                                                                            format  type   num_seqs        sum_len  min_len  avg_len  max_len
/mnt/d/Dropbox/User/Sequencing_Data/TCR/Seq_sample_basecall/Merge/Seq_pass_fail.fastq  FASTQ   DNA   2,004,000  1,654,597,413       81    825.6   10,849

This is a fast basecalled Sample of my Run. The Sample that worked seamlessly with TRUST4 was high accuracy basecalled. Could this be the reason ?

**Comment by mourisl** [comment]
Yes, I think this read length causes the issue. It is not likely to have a 10Kb long BCR/TCR gene sequence even including the constant gene. Those long reads could have some regions similar to V,J gene and were still processed by TRUST4. Could you please try to prefilter those long reads or trim those reads? Thank you.

**Comment by jkbenotmane** [comment]
Thank you a lot! Subsetting the read length to 5k of only aligned reads (by minimap2 to refernce file) solved the  issue:

(base) user@DESKTOP:/mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/Sample1/TRUST4/SampleSeq9_unprocessed_max5k$ run-trust4 -u '/mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/Sample1/TRUST4/Sample_Bam/Sample1_aln_TRUST4_ref_mapped_max5k.fastq' -o 'Output_SampleSeq9_unprocessed_max5k' -f '/mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/SampleSeq2/TRUST4/IMGT+C.fa' --ref '/mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/SampleSeq2/TRUST4/IMGT+C.fa' -t 16
[Wed Jun 23 19:58:30 2021] TRUST4 begins.
[Wed Jun 23 19:58:30 2021] SYSTEM CALL: /home/user/anaconda3/bin/fastq-extractor -t 16 -f /mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/SampleSeq2/TRUST4/IMGT+C.fa -o Output_SampleSeq9_unprocessed_max5k_toassemble  -u /mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/Sample1/TRUST4/Sample_Bam/Sample1_aln_TRUST4_ref_mapped_max5k.fastq
[Wed Jun 23 19:58:30 2021] Start to extract candidate reads from read files.
[Wed Jun 23 20:07:57 2021] Finish extracting reads.
[Wed Jun 23 20:07:57 2021] SYSTEM CALL: /home/user/anaconda3/bin/trust4  -f /mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/SampleSeq2/TRUST4/IMGT+C.fa -t 16 -o Output_SampleSeq9_unprocessed_max5k -u Output_SampleSeq9_unprocessed_max5k_toassemble.fq
[Wed Jun 23 20:09:56 2021] Read in and count kmers for 100000 reads.
[Wed Jun 23 20:12:17 2021] Read in and count kmers for 200000 reads.
[Wed Jun 23 20:14:54 2021] Read in and count kmers for 300000 reads.
[Wed Jun 23 20:17:49 2021] Read in and count kmers for 400000 reads.
[Wed Jun 23 20:20:53 2021] Read in and count kmers for 500000 reads.
[Wed Jun 23 20:24:08 2021] Read in and count kmers for 600000 reads.
[Wed Jun 23 20:46:04 2021] Found 678646 reads.
[Wed Jun 23 20:47:13 2021] Finish sorting the reads.
[Wed Jun 23 20:49:17 2021] Finish rough annotations.
[Wed Jun 23 21:01:55 2021] Processed 100000 reads (35293 are used for assembly).
[Wed Jun 23 21:29:59 2021] Processed 200000 reads (90907 are used for assembly).
[Wed Jun 23 21:59:20 2021] Processed 300000 reads (141100 are used for assembly).
[Wed Jun 23 22:26:07 2021] Processed 400000 reads (199652 are used for assembly).
[Wed Jun 23 22:56:05 2021] Processed 500000 reads (263963 are used for assembly).
[Wed Jun 23 23:30:04 2021] Processed 600000 reads (337659 are used for assembly).
[Wed Jun 23 23:47:13 2021] Assembled 388147 reads.
[Wed Jun 23 23:47:13 2021] Try to rescue 0 reads for assembly.
[Wed Jun 23 23:47:18 2021] Rescued 0 reads.
[Thu Jun 24 00:31:41 2021] SYSTEM CALL: /home/user/anaconda3/bin/annotator -f /mnt/d/Dropbox/user/Projects/Sequencing/Samples/SampleSeq/SampleSeq2/TRUST4/IMGT+C.fa -a Output_SampleSeq9_unprocessed_max5k_final.out -t 16 -o Output_SampleSeq9_unprocessed_max5k  -r Output_SampleSeq9_unprocessed_max5k_assembled_reads.fa > Output_SampleSeq9_unprocessed_max5k_annot.fa
[Thu Jun 24 00:31:41 2021] Start to annotate assemblies.
[Thu Jun 24 01:27:47 2021] Start to realign reads for CDR3 analysis.
[Thu Jun 24 03:21:55 2021] Compute CDR3 abundance.
[Thu Jun 24 03:21:59 2021] Finish annotation.
[Thu Jun 24 03:22:47 2021] SYSTEM CALL: perl /home/user/anaconda3/bin/trust-simplerep.pl Output_SampleSeq9_unprocessed_max5k_cdr3.out  > Output_SampleSeq9_unprocessed_max5k_report.tsv
[Thu Jun 24 03:22:48 2021] TRUST4 finishes.
