### ISSUE TITLE
example files crush with "Unknown genome name: 311"

### ISSUE THREAD

**Issue by antonkulaga** [liulab-dfci/TRUST4#56]
```
run-trust4  -f /cromwell-executions/trust/0b587343-8d14-4ad6-a542-8050dda4571b/call-trust4/inputs/1085837631/TRUST_example_annot.fa -t 12 -b /cromwell-executions/trust/0b587343-8d14-4ad6-a542-8050dda4571b/call-trust4/inputs/1085837631/example.bam
```
I used latest docker container quay.io/biocontainers/trust4:1.0.4--h2e03b76_0

**Comment by antonkulaga** [comment]
Same example works well with fastq-s. So I believe it is bam that is totally broken (never managed to make it work with my files as well).

**Comment by mourisl** [comment]
The -f option should be the "IMGT+C.fa" or "hg38_bcrtcr.fa" file. The _annot file is the output of the example file.

For example: 
./run-trust4 -b example/example.bam -f hg38_bcrtcr.fa --ref human_IMGT+C.fa
