### ISSUE TITLE
report.tsv file as input to VDJtools error [ERROR] java.lang.RuntimeException: Unable to parse clonotype string 7 ...VDJtools input type: Unknown symbol "o"

### ISSUE THREAD

**Issue by rosana08** [liulab-dfci/TRUST4#58]
Hi liulab,

Thanks for this wonder tool. I'm trying to do VDJtools-CalcBasicStats from TRUST4 output directly as it is mentioned that reports.tsv is compatible with VDJtools. But, I got following error, could you kindly advise how to process TRUST4 results to use VDJtools for downstream analysis...

[ERROR] java.lang.RuntimeException: Unable to parse clonotype string 9 6.716418e-02 TGTGCGAGAGGGCAGGACGGTGACTACGTGGGCGAGCCCGGGGAGTCTACTACTACTACTACATGGACGTCTGG
out_of_frame IGHV1-301 IGHD1-2601 IGHJ6*04 . assemble1 0 for MiXcr input type: Some mandatory columns are absent in the input file., see _vdjtools_error.log for details

Many thanks,
Rosana

**Comment by mourisl** [comment]
TRUST4 uses "out_of_frame" in the amino acid field to represent the kind of non-productive CDR3. It seems VDJtools does not recognize this, and you can use "grep -v out_of_frame" to remove those lines.

**Comment by rosana08** [comment]
Thank you very much for quick response... It's working fine now!! :-)
