### ISSUE TITLE
output farmat

### ISSUE THREAD

**Issue by toddey** [liulab-dfci/TRUST4#6]
Hi, I have a question about the output of trust_report.tsv, the first header "count" stand that how many copys of the specific TCR chains(each rows stand for one type TCR chain), is it right？ And for single-cell data, if I use hisat2 to generate bam file from read2(treated as sigle-end bulk  RNA-seq data),then use TRUST4 to call TCR/BCR, are the results credible ?

**Comment by mourisl** [comment]
Not always true for the "count", when given "barcode" option, the count is how many cells/copies of that TCR. When not given "barcode" option (bulk RNA-seq), it is just the number of reads supporting that.

Yes, TRUST4 is designed for bulk RNA-seq at beginning, the results were quite reliable from our experiments.

**Comment by toddey** [comment]
> Not always true for the "count", when given "barcode" option, the count is how many cells/copies of that TCR. When not given "barcode" option (bulk RNA-seq), it is just the number of reads supporting that.
> 
> Yes, TRUST4 was designed for bulk RNA-seq at beginning, the results were quite reliable from our experiments.

Thanks for your patience!

**Comment by toddey** [comment]
Hi, I meet a puzzling problem. I want to study TCR of my samples, so I select the chromosome wich contain TCR( chr7 and chr14), I used “samtools view -hb YGR_sc.sorted.bam 7 14 > YGR_sub.bam” to 
get the sub bam files. Then run TRUST4. but the sub bam results is a little different from the result of full bam file 
sub bam results:
#count	frequency	CDR3nt	CDR3aa	V	D	J	C
392	6.727995e-01	TGTGCTGCGTGGGATTACACCATACTAGAACTGTTGAAACAACATGCACAAAATCCCCTCCCAGGGTCTGTGCCCACCACATCCTTC	partial	TRGV10*02	*	*	TRGC
24	4.111419e-02	TGTGCTGCGTGGGATTATAAGAAACTCTTT	CAAWDYKKLF	TRGV10*02	*	TRGJ1*02	TRGC
.....
 
full bam results:
395	2.484500e-01	TGTGCTGCGTGGGATTACACCATACTAGAACTGTTGAAACAACATGCACAAAATCCCCTCCCAGGGTCTGTGCCCACCACATCCTTC	partial	TRGV10*02	*	*	*
321	2.016709e-01	TGCCTCGTGGGTGACACACAGTGAGACAGATGGGCCTGCACCTGTGCCGTTTTCCTCTGT	partial	TRAV4*01	*	*	*
.....
The top frequency of the both results are the same TCR chain , but it have different frequency in the two results. But the second top TCR chain of full bam results can not be found in sub bam results.
I don't know which result I should trust?

**Comment by mourisl** [comment]
Many of the reads covering CDR3 region could not be mapped on the reference genome because the CDR3 sequence is not represented on it. TRUST utilizes those unmapped reads as well, so by extracting only chr7,chr14 you may miss those reads.

**Comment by toddey** [comment]
> Many of the reads covering CDR3 region could not be mapped on the reference genome because the CDR3 sequence is not represented on it. TRUST utilizes those unmapped reads as well, so by extracting only chr7,chr14 you may miss those reads.

Got it. And for cdr3aa, I can understand "partial" means the identified cdr3 is not complete, but what does "out_of_frame" means?

**Comment by mourisl** [comment]
That means the length of the CDR3nt is not multiple of 3, so this is a out of frame recombination.

**Comment by toddey** [comment]
> That means the length of the CDR3nt is not multiple of 3, so this is a out of frame recombination.

Thanks for your patience again!

**Comment by toddey** [comment]
Hi， I find that  two TCR may have the same CDR3nt in one sample, for example:
	5	3.228293e-04	GCAGTGGTATCAACGCAGAGTACATGGGATTTT	partial	*	*	TRBJ2-3*01	TRBC	TRB
	7	4.519611e-04	GCAGTGGTATCAACGCAGAGTACATGGGATTTT	partial	*	*	TRBJ1-5*01	TRBC	TRB

The two TCR are called from one sample. How to explain this.....?

**Comment by mourisl** [comment]
These two TCRs have different J genes, so evene though they have the same cdr3, I still put them separately.

**Comment by toddey** [comment]
> These two TCRs have different J genes, so evene though they have the same cdr3, I still put them separately.

Ok，got it.Thanks！
