### ISSUE TITLE
reference file - TCR

### ISSUE THREAD

**Issue by rosana08** [liulab-dfci/TRUST4#60]
Hi liulab,

Thanks for the wonderful tool. Is there a reference file available to analyse only TCR instead of reference for both TCR and BCR (-f hg38_bcrtcr.fa)?

Thanks

**Comment by mourisl** [comment]
You can use 
    grep -A 1 --no-group-separator ">T" human_IMGT+C.fa > human_IMGT+C_T.fa
and
   grep -A 1 --no-group-separator ">T" hg38_bcrtcr.fa > human_tcr.fa
to extract the TCR sequence and coordinate information from the reference files.

**Comment by rosana08** [comment]
Many thanks for quick response! It works fine!!
