### ISSUE TITLE
Is it possible to use cellranger V(D)J compatible reference

### ISSUE THREAD

**Issue by rosana08** [liulab-dfci/TRUST4#61]
Hi liulab,

A small doubt, is it possible to use  Cell Ranger V(D)J compatible reference (/opt/refdata-cellranger-vdj-GRCh38-alts-ensembl-5.0.0) in -f option to run Trust4?  

Does the Trust4 references hg38_bcrtcr.fa or human_IMGT+C.fa already include cell ranger-vdj human reference in it? 

Many thanks

**Comment by mourisl** [comment]
I checked the header from 10X vdj reference genome, and it is incompatible with TRUST4's reference file. Though you can convert the header to just contain the gene name just as the human_IMGT+C.fa file. 

TRUST4 and CellRanger both used the sequences from IMGT, so the content should be the same. hg38_bcrtcr.fa is based on the GENCODE annotation, and it is most useful when the input is BAM file. So if you want to use VDJ's reference, you can rename their sequence headers and run TRUST4 with FASTQ input.

**Comment by rosana08** [comment]
Many thanks for quick response and clarification. I will give it a try

**Comment by rosana08** [comment]
It's working with VDJ reference as advised. I could create database.fa using your BuildDatabaseFa.pl  for a reference version which I needed 

Thanks a lot for help and support!! Much appreciated!
