### ISSUE TITLE
Compatible with full length transcript?

### ISSUE THREAD

**Issue by TangLabsysu2020** [liulab-dfci/TRUST4#63]
Hi,
    I have full length transcripts data, and I want  extraction bcr and trc candidate read from my data, skipping the assembly, then do annotation and generating the report table. How can i do this?
    Thanks!

**Comment by mourisl** [comment]
Hello, though the main wrapper run-trust4 does not support this function, you can achieve this by running modules separately. For example, something like this should work:

./fastq-extractor -f IMGT+C.fa -u reads.fq -o tmp # Extract candidate reads
./annotator --needReverseComplement --fastq -a tmp.fq -o tmp -f IMGT+C.fa > tmp_annot.fa # generate the annotation file and intermediate report file tmp_cdr3.out
perl trust-simplerep tmp_cdr3.out # generate the report table

I just added "--needReverseComplement", "--fastq" options, so you need to git pull or git clone the newest TRUST4 version. Does this help? Thank you

**Comment by TangLabsysu2020** [comment]
Hi,
    Thanks for your promptly reply, I'll have a try

**Comment by TangLabsysu2020** [comment]
Hi,
    sorry for disturb you again. when i ran annotator command, i got only "tmp_annot.fa", the file "tmp_cdr3.out" are not generated. how can i solve this problem?
Thanks

**Comment by mourisl** [comment]
Sorry, I forgot to put the "--outputCDR3File" option for annotator. The command is updated, could you please give it a try? Thank you.

**Comment by TangLabsysu2020** [comment]
Hi, 
    This pipeline works well for me now. Thanks

**Comment by jkbenotmane** [comment]
Where those scripts removed from the repository or did you change the Name?

./fastq-extractor -f IMGT+C.fa -u reads.fq -o tmp # Extract candidate reads
./annotator --outputCDR3File --needReverseComplement --fastq -a tmp.fq -o tmp -f IMGT+C.fa > tmp_annot.fa # generate the annotation file and intermediate report file tmp_cdr3.out

**Comment by mourisl** [comment]
You need to run "make" to generate those executables.

**Comment by jkbenotmane** [comment]
Of course... sorry.
Thank you!
