### ISSUE TITLE
Matching each BCR or TCR to corresponding cell

### ISSUE THREAD

**Issue by jaewon-cho** [liulab-dfci/TRUST4#65]
Hello
I am trying to map the clonotype information (assemble#) to the corresponding cell.
How can I do it?
(I am using 10x data)

Thank you

**Comment by mourisl** [comment]
It is explained here https://github.com/liulab-dfci/TRUST4#10x-genomics-data  .

**Comment by jaewon-cho** [comment]
Thank you so much
I should have read the document more carefully.
