### ISSUE TITLE
paired end vdj reconstruction

### ISSUE THREAD

**Issue by chenling-immunai** [liulab-dfci/TRUST4#66]
Is it possible to use TRUST4 on paired end data with separate index files (as in 10X 5' TCR and BCR sequences)? 

Thank you!

**Comment by mourisl** [comment]
Yes, you can use grep -A 1 --no-group-separator ">TR" IMGT+C.fa > tcr.fa and  "grep -A 1 --no-group-separator ">IG" IMGT+C.fa > bcr.fa" to get the reference files for TCR and BCR respectively, and then use it as the -f/--ref input (suppose your sequencing data is in fastq). 

By default, TRUST4 should be able to reliably distinguish reads from TCRs and BCRs, just out of curiosity, is there a particular application that you need to separate index/reference files? Thanks.

**Comment by chenling-immunai** [comment]
Hi thank you for getting back to me so quickly! 
I think I hadn't phrased my question clearly enough: I think the 10x pipeline separates the index from the actual sequence already (The fastq are named R1, R2, I1, I2 from a single lane). So I am wondering how those read will go as input to trust4 and if I need more information about the technology to tell for sure. 
Thanks a lot!

**Comment by mourisl** [comment]
Do you mean the index is the lane index? You can use "*" or comma-separated list for options -1, -2, --barcode in TRUST4 as https://github.com/liulab-dfci/TRUST4#10x-genomics-data .

**Comment by chenling-immunai** [comment]
Great thanks!!!
