### ISSUE TITLE
read QC

### ISSUE THREAD

**Issue by Nusob888** [liulab-dfci/TRUST4#68]
Hi, 

Thanks for the brilliant tool. 

I just wanted to enquire a few things:

- Does TRUST4 handle alignments well without adaptor trimming? It is unclear from the manuscript and vignettes on whether this improves performance or whether keeping the reads untrimmed results in better coverage, as has been suggested in some manuscripts. 
- Does TRUST4 have any internal quality controls on base quality during alignments?

Many thanks in advance

**Comment by mourisl** [comment]
TRUST4 internally handles the read-through issue by checking the overlap of mate pairs. So there is no need for adaptor trimming.

For the base quality, TRUST4 trims the read end with bad quality bases near the end. Internally, the bad quality means the quality symbol is less or equal to "/" and the corresponding kmer counts are 1.

**Comment by Nusob888** [comment]
Brilliant, thanks for clarifying so quickly!
