### ISSUE TITLE
the difference between using raw fastq and bam file.

### ISSUE THREAD

**Issue by weizhiting** [liulab-dfci/TRUST4#69]
HI,  I have fastq and  bam file for a sample. To call BCR, which type of file is suggested to use?  Does using bam file will be more accurate?  Why? 
Thanks for your reply.

**Comment by mourisl** [comment]
From my experience, the results are almost identical between bam-input and fastq-input. The bam-input is faster because the reads aligned to non VDJC regions can be directly skipped.
