### ISSUE TITLE
A question about reference genome

### ISSUE THREAD

**Issue by zmyyy3** [liulab-dfci/TRUST4#71]
Hi,

I'm going to use this great tool in dogs' data and try to build the dog_bcrtcr.fa. I got the reference genome annotation GTF( annotation.gtf) from the website of ENSEMBLE. But the reference genome( reference.fa) on the [ENSEMBLE website](http://ftp.ensembl.org/pub/release-104/fasta/canis_lupus_familiaris/dna/) is sorting by chromosome, and there are many files. So I'm confused about which file is good to use. Would you please share with me what kind of file you used to generate hg38_bcrtcr.fa or GRCm38_bcrtcr.fa? Thank you so much!

Best,
Meng

**Comment by zmyyy3** [comment]
I've tried these 2 ways. The second method worked well. 

The first method showed some errors. I merged all the chromosome files into one reference.fa.  
1. But when I ran the BuildDatabaseFa.pl, it showed _'No transcript_name'_. I checked the gtf data, _(X	ensembl	exon	122048669	122049366	.	-	.	gene_id "ENSCAFG00000048531"; gene_version "1"; transcript_id "ENSCAFT00000086423"; transcript_version "1"; exon_number "1"; gene_source "ensembl"; gene_biotype "lncRNA"; transcript_source "ensembl"; transcript_biotype "lncRNA"; exon_id "ENSCAFE00000384752"; exon_version "1"; )_. Indeed, there is no "transcipt_name".  
2. Then, I used human data to run this script again, still got the error _(No transcript_name1	havana	exon	1249777	1251334	.	-	.	gene_id "ENSG00000260179"; gene_version "1"; transcript_id "ENST00000565563"; transcript_version "1"; exon_number "1"; gene_source "havana"; gene_biotype "lncRNA"; transcript_source "havana"; transcript_biotype "lncRNA"; exon_id "ENSE00002619150"; exon_version "1"; tag "basic"; transcript_support_level "NA";)_.
3. I checked the script of BuildDatabaseFa.pl, there is a **next if** statement. Logically, the data triggered errors cannot get into the next if statement because the results of **$clos[2] ne "exon"** are false.  Could you please help me figure out what the problem is? Thank you!

**Comment by mourisl** [comment]
I used the GTF file from gencode, and it contains he field like "transcript_name" and "gene_name", which are not presented in your GTF file. The "gene_name" and "transcript_name" are important, so we know it is something like "TRBV" or "IGHJ".

**Comment by zmyyy3** [comment]
I got the GTF file from [[Ensembl]](https://m.ensembl.org/index.html). I've compared my GTF file with the GTF file from gencode, and they are truly different. Maybe I need to filter out those genes without the information of "transcript_name" and "gene_name" firstly; then to build the database.

**Comment by mourisl** [comment]
If the TCR, BCR genes have the names, then you can filter other genes with no names.

**Comment by zmyyy3** [comment]
An update!
It's kind of weird. I filtered those data with no names; then ran the script, no errors showed up, but there is nothing in the bcrtcr.fa. 
BTW, I uesd **grep -E "transcript_name|gene_name " GTF >  new.gtf** to filter.

**Comment by mourisl** [comment]
Does any BCR, TCR gene show up in the new.gtf file? Like the TRB constant gene "TRBC"?

**Comment by zmyyy3** [comment]
It contains TRAV, TRBV, and TRDV, but does not contain TRBC, TRAJ... in the new.gtf, even in the original GTF file.

**Comment by mourisl** [comment]
I guess the annotation file is incomplete for dog genome. So maybe the second way is better.

**Comment by zmyyy3** [comment]
Maybe you are right. Does the IMGT+C.fa work well for the BAM file?

**Comment by mourisl** [comment]
No, the IMGT+C.fa does not have the genomic coordinates for the genes, so it could not be used to extract reads in the BAM file.

**Comment by zmyyy3** [comment]
Got it. I really appreciate your help!
