### ISSUE TITLE
Questions about the analysis of BCR/TCR using the bulk RNAseq

### ISSUE THREAD

**Issue by weizhiting** [liulab-dfci/TRUST4#72]
Hi, first thanks for the great tools. 
I runTRUST4 on bulk RNAseq datasets of solid tumor samples. About the results in report file, i have several questions:

(1) every samples in my dataset have about 100 million reads, but the total number of reads mapped to BCR/TCR are only tens of thousands and even several hundreds; furthermore,  99% of the reads are mapped to BCR,  is this situation normal? 

(2) Of the reads that mapped to BCR, 95% are mapped to BCR light chain, only 5% are mapped to BCR heavy chain. In my opinion, reads mapped to heavy chain and light chain should be equal. Am i right?  

(3) If the results are right, should i do some quality control before downstream analysis? For example, filter out the clones that only have several reads, because those clones are likely to be false positives? If there is no need to do so, why?
Attached is outputs of several samples in my cohort.
[97PT1-1.txt](https://github.com/liulab-dfci/TRUST4/files/7063781/97PT1-1.txt)
[99PT1-1.txt](https://github.com/liulab-dfci/TRUST4/files/7063782/99PT1-1.txt)
[164PT1-1.txt](https://github.com/liulab-dfci/TRUST4/files/7063783/164PT1-1.txt)
[165PT1-1.txt](https://github.com/liulab-dfci/TRUST4/files/7063784/165PT1-1.txt)
[167PT1-1.txt](https://github.com/liulab-dfci/TRUST4/files/7063785/167PT1-1.txt)
[95PT1-1.txt](https://github.com/liulab-dfci/TRUST4/files/7063786/95PT1-1.txt)

Thanks for your reply.

**Comment by tdfy** [comment]
@mourisl could you please point me in the direction of some literature regarding #2 above? Specifically, BCR lamba/kappa expression > heavy chain? Thank you.

**Comment by mourisl** [comment]
@tdfy We confirmed the observation in TRUST4's manuscript Supplementary Figure 5b based on 10x single-cell data (https://static-content.springer.com/esm/art%3A10.1038%2Fs41592-021-01142-2/MediaObjects/41592_2021_1142_MOESM1_ESM.pdf). There should be other reference literature but might not mention this explicitly.

**Comment by tdfy** [comment]
thank you @mourisl !
