### ISSUE TITLE
--ref option not available

### ISSUE THREAD

**Issue by Emberwhirl** [liulab-dfci/TRUST4#79]
Hi. Many thanks for this great tool. After running make command, it seems that --ref option is not available. 

Here is the snapshot of the output of "./trust4 --help" command. 
![1631242517(1)](https://user-images.githubusercontent.com/5317953/132792054-d0b8bcb9-6da0-4638-8472-e158cbdb40d6.png)

Thank you for your reply.

**Comment by mourisl** [comment]
The --ref is available from the wrapper run-trust4. "./trust4" is the core program for assembly, but it still needs the output from fastq-extractor or bam-extractor. This will be handled by the wrapper.

**Comment by Emberwhirl** [comment]
> The --ref is available from the wrapper run-trust4. "./trust4" is the core program for assembly, but it still needs the output from fastq-extractor or bam-extractor. This will be handled by the wrapper.

Thanks for the swift reply!
