### ISSUE TITLE
10x 5' kit without VDJ

### ISSUE THREAD

**Issue by avilella** [liulab-dfci/TRUST4#8]
Hi all,

What's the recommended fragmentation protocol step for the 10x 5' kit if wanting to get the VDJ sequences as full-length as possible?

**Comment by mourisl** [comment]
We haven't done any benchmark on that. This quite depends on the expression level from the cell. For example, from the plasma B cell, it can easily get the full-length BCRs. But for TCR, it may require more sequencing depth.
