### ISSUE TITLE
What is the criteria of barcoderep-filter.py?

### ISSUE THREAD

**Issue by ttab963** [liulab-dfci/TRUST4#89]
Hi.

In #82 and #87 , I found that barcoderep-filter.py can be used to my result and It works.
And you say this filtering is based on Cellranger documents.

So, could you tell me which part do you use?
I cant find about diffusion effect in cellranger and sadly I cant understand code in barcoderep-filter.py too.

Thanks for your help.

**Comment by ttab963** [comment]
Thanks to reply.

So this algorithm counts chain abundance by read counts in chain1 or chain2.

Is it right?

**Comment by mourisl** [comment]
Right. A's chain1 has to be the same as B's chain1, and the abundance is significantly smaller. The same test will be applied to chain2. If both tests are significantly smaller (including the case A misses the chain), then it will be filtered.

There are a few more variations/combinations of parameters I need to further test and tune. At least, I think the filter works reasonably for now.

**Comment by ttab963** [comment]
Okay, I fully understand!

Thank you so much, mourisl.
