### ISSUE TITLE
clonatype define

### ISSUE THREAD

**Issue by toddey** [liulab-dfci/TRUST4#9]
Hi! I have a question about clonatype identification, I found the defination of clonatype from paper :A TCR clonotype is a unique nucleotide sequence that arises during the gene rearrangement process for that receptor. 
So I can directly use the TRUST4 called CDR3 dna sequence to denfine clonotypes, right?
 And I found TCR clone sequences have been presented in publications in many different forms, what the forms do you usually use? Thank you in advance for your reply.

**Comment by mourisl** [comment]
For us, we mostly use CDR3 dna as clonotypes, which is as you did. This is purely from computational perspective. For biology, it may make more sense use the amino acid sequence as clonotype. Furthermore, if the data has good coverage on T cells, you may use V gene id, J gene id and CDR3 as the clonotype.

**Comment by mourisl** [comment]
By default, TRUST4 also reports partial CDR3s, you may want to filter those out from the report file (just grep -v partial) to compute clonaltypes.

**Comment by toddey** [comment]
> By default, TRUST4 also reports partial CDR3s, you may want to filter those out from the report file (just grep -v partial) to compute clonaltypes.

The out_of _frame CDR3 should also be removed, right?

**Comment by mourisl** [comment]
That's a bit different, for out_of_frame and the CDR3s with stop codon (symbol "_"), they are still the nucleotide sequence during gene rearrangement process for the receptor. I usual still include them as clonotypes, but this depend on the application. If you are interested more at the protein level, you should definitely remove those, since these CDR3s won't be able to translate into the real receptors.

**Comment by toddey** [comment]
> That's a bit different, for out_of_frame and the CDR3s with stop codon (symbol "_"), they are still the nucleotide sequence during gene rearrangement process for the receptor. I usual still include them as clonotypes, but this depend on the application. If you are interested more at the protein level, you should definitely remove those, since these CDR3s won't be able to translate into the real receptors.

I am a little puzzled about partial CDR3. They are also naturally occurring, or just incomplete sequencing?

**Comment by mourisl** [comment]
Partial CDR3 means incomplete sequencing. But from TRUST4's results, many of the partial CDR3s are also from those V or J genes before recombination, so these should be used with caution. I'm considering remove partial CDR3 results from the report by default in the formal release in future.

I'm not on TRUST3's paper. From my experience, many partial CDR3s from TRUST3 become complete in TRUST4, so there is no need to just look for substrings (octamer).

**Comment by toddey** [comment]
> Partial CDR3 means incomplete sequencing. But from TRUST4's results, many of the partial CDR3s are also from those V or J genes before recombination, so these should be used with caution. I'm considering remove partial CDR3 results from the report by default in the formal release in future.
> 
> I'm not on TRUST3's paper. From my experience, many partial CDR3s from TRUST3 become complete in TRUST4, so there is no need to just look for substrings (octamer).

Got it! Thanks for your patience!
