### ISSUE TITLE
Normalised frequencies sum to different values

### ISSUE THREAD

**Issue by loverend** [liulab-dfci/TRUST4#93]
Hello!

I have run TRUST4 on a large number of RNAseq samples (~900) and have been concatenating the _report.tsv" files together to allow me to do some summary plots. I have separated them into sub groups of different chains e.g.

(outs_files) is a list of 900 report.tsv files to iterate through. 

analysis <- foreach(i = 1:length(outs_files), .combine=rbind, .packages='tidyverse') %dopar% {
	file_name <- outs_files[i]
	fileid <- outs_files[i]
	fileid <- read.delim(fileid, sep="\t", header=TRUE)
	sample_id <- str_split(file_name, "/")
	sample_id <- unlist(sample_id)
	sample_id <- sample_id[length(sample_id)]
	sample_id <- gsub("_report.tsv", "", sample_id)
	fileid$sample <- sample_id
	return(fileid)
}
heavy_chain <- analysis[analysis$V %like% "IGH" | analysis$D %like% "IGH" |analysis$J %like% "IGH", ]
light_chain <- analysis[analysis$V %like% "IGL" | analysis$V %like% "IGK" |analysis$D %like% "IGL" | analysis$D %like% "IGK" |analysis$J %like% "IGL" | analysis$J %like% "IGK" , ]
TCRA <- analysis[analysis$V %like% "TRA" | analysis$D %like% "TRA" | analysis$J %like% "TRA",]
TCRB <- analysis[analysis$V %like% "TRB" | analysis$D %like% "TRB" | analysis$J %like% "TRB",]

However when I look at the sum of the frequencies within each chain for an individual sample I get the sum to be different e.g. 
> sum(heavy_chain$frequency[heavy_chain$sample=="gains8033355"])
[1] 3
> sum(heavy_chain$frequency[heavy_chain$sample=="gains8033357"])
[1] 2

I would have though they should all be normalised to the same value? I have tried with BCR combining both chains etc. Please could you explain what these frequencies are - I assumed it was proportion of RNAseq reads mapping to that VDJ. If so why does the range vary for different samples? What would be the best way to concatenate reads from just a BCR chain and normalise them so that they are comparable across samples. 

Thank you!

**Comment by loverend** [comment]
Can I check - how do you determine how to call those sequences where for example they have a TCRA chain but V(D or J) called to TRD for example? Or vice versa? Will you call based on the constant gene? What happens if the constant gene is '.' (undetermined).  
For example: 
 TGTGCTCTTGGGGAACTTGGTCCTGGAGGCTTCAAAACTATC  CALGELGPGGFKTI TRDV1*01 TRDD3*01  TRAJ9*01 . (undetermined)

**Comment by mourisl** [comment]
I usually priortize J gene and constant gene over V gene. Though the alpha chain should not have D gene, I still put it here just in case the strategy is wrong.
